### ISSUE TITLE
exception when "sbt clean dist"

### ISSUE THREAD

**Issue by tanbamboo** [yahoo/kafka-manager#117]
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* org.webjars:jquery:(2.1.3, 1.11.1) -> 2.1.4
[warn] Run 'evicted' to see detailed eviction warnings

java.lang.NoSuchMethodError: spray.json.JsArray.<init>(Lscala/collection/immutable/List;)V
	at com.typesafe.sbt.less.SbtLess$$anonfun$2.apply(SbtLess.scala:64)
	at com.typesafe.sbt.less.SbtLess$$anonfun$2.apply(SbtLess.scala:55)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (web-assets:less::jstaskJsOptions) java.lang.NoSuchMethodError: spray.json.JsArray.<init>(Lscala/collection/immutable/List;)V

**Comment by patelh** [comment]
Not sure what this error is about.  Try cleaning your ivy cache:
```
rm -Rf ~/.ivy2/cache
```

And then do a pull on master to make sure you have latest and try again.

**Comment by patelh** [comment]
Any update here?  Can this be closed?

**Comment by tanbamboo** [comment]
Sorry, i have try to rm ivy2 cache, and update sbt, it just doesn't work.
