### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by bwwinthehouse** [yahoo/kafka-manager#120]
```
! Internal server error, for (GET) [/] ->

java.lang.ExceptionInInitializerError: null
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$1.apply(routes_routing.scala:354) ~[kafka-manager.kafka-manager-1.2.8.jar:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$1.apply(routes_routing.scala:354) ~[kafka-manager.kafka-manager-1.2.8.jar:na]
	at play.core.Router$HandlerInvokerFactory$$anon$13$$anon$14.call(Router.scala:217) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
	at play.core.Router$Routes$TaggingInvoker.call(Router.scala:464) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$1.apply(routes_routing.scala:354) ~[kafka-manager.kafka-manager-1.2.8.jar:na]
Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'application.features'
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124) ~[com.typesafe.config-1.2.1.jar:na]
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145) ~[com.typesafe.config-1.2.1.jar:na]
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151) ~[com.typesafe.config-1.2.1.jar:na]
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159) ~[com.typesafe.config-1.2.1.jar:na]
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164) ~[com.typesafe.config-1.2.1.jar:na]
[error] application - Error while rendering default error page
scala.MatchError: java.lang.ExceptionInInitializerError (of class java.lang.ExceptionInInitializerError)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:148) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:206) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
	at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:63) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
	at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:73) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
	at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:71) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
```

I get this error when I attempt to load the homepage. Is it because of my version of play or java?

**Comment by bwwinthehouse** [comment]
This is new 

```

You can optionally enable/disable the following functionality by modifying the default list in application.conf :

application.features=["KMClusterManagerFeature","KMTopicManagerFeature","KMPreferredReplicaElectionFeature","KMReassignPartitionsFeature"]
KMClusterManagerFeature - allows adding, updating, deleting cluster from Kafka Manager
KMTopicManagerFeature - allows adding, updating, deleting topic from a Kafka cluster
KMPreferredReplicaElectionFeature - allows running of preferred replica election for a Kafka cluster
KMReassignPartitionsFeature - allows generating partition assignments and reassigning partitions

```
