### ISSUE TITLE
sbt fails

### ISSUE THREAD

**Issue by ChristianKniep** [yahoo/kafka-manager#121]
Hey there,

I am trying to build the kafka-manager but I get the following error:
```
$ dbuild qnib/kafka-manager
Sending build context to Docker daemon    64 kB
Sending build context to Docker daemon
Step 0 : FROM qnib/java7
 ---> 242fbe64e348
Step 1 : RUN yum install -y bsdtar sbt
 ---> Using cache
 ---> 940c1b2756ef
Step 2 : RUN curl -fsL https://github.com/yahoo/kafka-manager/archive/master.zip |bsdtar xf - -C /opt/ &&     mv /opt/kafka-manager-master /opt/kafka-manager/
 ---> Using cache
 ---> cb9d2fbad8b0
Step 3 : RUN cd /opt/kafka-manager/ && sbt clean dist
 ---> Running in 21086c047481
Getting org.scala-sbt sbt 0.13.9 ...
downloading http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.9/jars/sbt.jar ...
	[SUCCESSFUL ] org.scala-sbt#sbt;0.13.9!sbt.jar (2607ms)
*snip*
info] Loading project definition from /opt/kafka-manager/project
/opt/kafka-manager/build.sbt:47: error: not found: value PlayScala
lazy val root = (project in file(".")).enablePlugins(PlayScala)
                                                     ^
sbt.compiler.EvalException: Type error in expression
	at sbt.compiler.Eval.checkError(Eval.scala:343)
	at sbt.compiler.Eval.compileAndLoad(Eval.scala:165)
	at sbt.compiler.Eval.evalCommon(Eval.scala:135)
	at sbt.compiler.Eval.evalDefinitions(Eval.scala:109)
	at sbt.EvaluateConfigurations$.evaluateDefinitions(EvaluateConfigurations.scala:125)
	at sbt.EvaluateConfigurations$.evaluateSbtFile(EvaluateConfigurations.scala:48)
	at sbt.Load$.sbt$Load$$loadSettingsFile$1(Load.scala:502)
	at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:497)
	at sbt.Load$$anonfun$sbt$Load$$memoLoadSettingsFile$1$1.apply(Load.scala:496)
	at scala.Option.getOrElse(Option.scala:120)
	at sbt.Load$.sbt$Load$$memoLoadSettingsFile$1(Load.scala:496)
	at sbt.Load$$anonfun$loadSettings$1$2.apply(Load.scala:495)
	at sbt.Load$$anonfun$loadSettings$1$2.apply(Load.scala:495)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbt.Load$.loadSettings$1(Load.scala:495)
	at sbt.Load$.sbt$Load$$expand$1(Load.scala:508)
	at sbt.Load$.loadSettings(Load.scala:512)
	at sbt.Load$.sbt$Load$$loadSbtFiles$1(Load.scala:466)
	at sbt.Load$.defaultLoad$1(Load.scala:472)
	at sbt.Load$.loadTransitive(Load.scala:475)
	at sbt.Load$.loadProjects$1(Load.scala:421)
	at sbt.Load$.loadUnit(Load.scala:422)
	at sbt.Load$$anonfun$15$$anonfun$apply$11.apply(Load.scala:258)
	at sbt.Load$$anonfun$15$$anonfun$apply$11.apply(Load.scala:258)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:93)
	at sbt.BuildLoader$$anonfun$componentLoader$1$$anonfun$apply$4$$anonfun$apply$5$$anonfun$apply$6.apply(BuildLoader.scala:92)
FROM qnib/java7
	at sbt.BuildLoader.apply(BuildLoader.scala:143)
	at sbt.Load$.loadAll(Load.scala:314)
	at sbt.Load$.loadURI(Load.scala:266)
	at sbt.Load$.load(Load.scala:262)
	at sbt.Load$.load(Load.scala:253)
	at sbt.Load$.apply(Load.scala:137)
	at sbt.Load$.defaultLoad(Load.scala:40)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:451)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:445)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:445)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
	at sbt.Command$.process(Command.scala:95)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
	at sbt.State$$anon$1.process(State.scala:179)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.MainLoop$.next(MainLoop.scala:100)
	at sbt.MainLoop$.run(MainLoop.scala:93)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:71)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:66)
	at sbt.Using.apply(Using.scala:25)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:66)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:49)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:33)
	at sbt.MainLoop$.runLogged(MainLoop.scala:25)
	at sbt.StandardMain$.runManaged(Main.scala:57)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
	at xsbt.boot.Launch$.run(Launch.scala:57)
	at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
	at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
	at xsbt.boot.Launch$.launch(Launch.scala:65)
	at xsbt.boot.Launch$.explicit(Launch.scala:45)
	at xsbt.boot.Launch$.initialized(Launch.scala:41)
	at xsbt.boot.Launch$.parsed(Launch.scala:34)
	at xsbt.boot.Launch$.configured(Launch.scala:24)
	at xsbt.boot.Launch$.apply(Launch.scala:19)
	at xsbt.boot.Launch$.apply(Launch.scala:16)
	at xsbt.boot.Boot$.runImpl(Boot.scala:32)
	at xsbt.boot.Boot$.run(Boot.scala:26)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
[error] sbt.compiler.EvalException: Type error in expression
[error] Use 'last' for the full log.
```

The Dockerfile can be found here:
https://github.com/qnib/docker-kafka-manager

**Comment by patelh** [comment]
Try java 8.

**Comment by ChristianKniep** [comment]
Same error w/ 1.8.0.
```
[info] Loading project definition from /opt/kafka-manager/project
/opt/kafka-manager/build.sbt:47: error: not found: value PlayScala
lazy val root = (project in file(".")).enablePlugins(PlayScala)
```

```
RUN yum install -y java-1.8.0-openjdk-headless
ENV JAVA_HOME /usr/lib/jvm/jre-1.8.0

RUN yum install -y bsdtar sbt
ENV KMGR_VER=1.2.7
RUN curl -fsL https://github.com/yahoo/kafka-manager/archive/${KMGR_VER}.zip |bsdtar xf - -C /opt/ && \
    mv /opt/kafka-manager-${KMGR_VER} /opt/kafka-manager/
RUN cd /opt/kafka-manager/ && sbt clean dist
```

**Comment by ChristianKniep** [comment]
Got the same outcome using CentOS7 and `java-1.8.0-openjdk`.

**Comment by ChristianKniep** [comment]
And fedora22 + java-1.8...

**Comment by ChristianKniep** [comment]
I guess my scala version was wrong. :)
