### ISSUE TITLE
default pidfile directory /var/run/kafka-manager is deleted after reboot

### ISSUE THREAD

**Issue by zmstone** [yahoo/kafka-manager#122]
Tried to build / install RPM in centos7.
Initial install worked, but it failed recovering from os reboot.
Below is want found in daemon.log

````
Exception in thread "main" java.io.FileNotFoundException: /var/run/kafka-manager/play.pid (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at play.core.server.NettyServer$$anonfun$createServer$1.apply(NettyServer.scala:242)
        at play.core.server.NettyServer$$anonfun$createServer$1.apply(NettyServer.scala:230)
        at scala.Option.map(Option.scala:146)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:230)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
        at scala.Option.map(Option.scala:146)
        at play.core.server.NettyServer$.main(NettyServer.scala:284)
        at play.core.server.NettyServer.main(NettyServer.scala)
````

I'll work if I manually create a /var/run/kafka-manager and change owner to user kafka-manager

**Comment by zmshi** [comment]
In src/etc-default, why PIDFILE is required in src/etc-template when '-Dpidfile.path=/var/run/${{app_name}}/play.pid'  is given in JAVA_OPTS ?

**Comment by quizac-** [comment]
This is due to:
# mount
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)

# ll /var/run
lrwxrwxrwx. 1 root root 6 Oct 12  2012 /var/run -> ../run

So, /var/run/kafka-manager directory is lost after reboot. Although, it's delivered in rpm, it's being deleted and init script doesn't reinstate it like i.e. rabbitmq-server does:
ensure_pid_dir () {
    PID_DIR=`dirname ${PID_FILE}`
    if [ ! -d ${PID_DIR} ] ; then
        mkdir -p ${PID_DIR}
        chown -R ${USER}:${USER} ${PID_DIR}
        chmod 755 ${PID_DIR}
    fi
}

This function is called before daemon in start().

**Comment by quizac-** [comment]
I've checked out current master and the issue with pid file directory still persists.
