### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by zmstone** [yahoo/kafka-manager#123]
I have installed the RPM version 1.2.8 in centos7.
It worked at fresh new installation.
but if I reboot the os I get below error.
(first there was the pidfile issue #122 , so i changed -Dpidfile to /tmp dir, then this).

````
2015-09-02 17:48:12,658 - [ERROR] - from application in New I/O worker #1


! Internal server error, for (GET) [/] ->

java.lang.NoClassDefFoundError: Could not initialize class controllers.Application$
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$1.apply(routes_routing.scala:354) ~[kafka-manager.kafka-manager-1.2.9.jar:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$1.apply(routes_routing.scala:354) ~[kafka-manager.kafka-manager-1.2.9.jar:na]
        at play.core.Router$HandlerInvokerFactory$$anon$13$$anon$14.call(Router.scala:217) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.Router$Routes$TaggingInvoker.call(Router.scala:464) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$1.apply(routes_routing.scala:354) ~[kafka-manager.kafka-manager-1.2.9.jar:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$1.apply(routes_routing.scala:354) ~[kafka-manager.kafka-manager-1.2.9.jar:na]
        at play.core.Router$Routes$class.call(Router.scala:326) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at Routes$.call(routes_routing.scala:17) ~[kafka-manager.kafka-manager-1.2.9.jar:na]
        at Routes$$anonfun$routes$1.applyOrElse(routes_routing.scala:353) ~[kafka-manager.kafka-manager-1.2.9.jar:na]
        at Routes$$anonfun$routes$1.applyOrElse(routes_routing.scala:349) ~[kafka-manager.kafka-manager-1.2.9.jar:na]
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at play.core.Router$Routes$class.handlerFor(Router.scala:454) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at Routes$.handlerFor(routes_routing.scala:17) ~[kafka-manager.kafka-manager-1.2.9.jar:na]
        at play.api.GlobalSettings$$anonfun$onRouteRequest$1$$anonfun$apply$1.apply(GlobalSettings.scala:128) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.api.GlobalSettings$$anonfun$onRouteRequest$1$$anonfun$apply$1.apply(GlobalSettings.scala:127) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at scala.Option.flatMap(Option.scala:171) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at play.api.GlobalSettings$$anonfun$onRouteRequest$1.apply(GlobalSettings.scala:126) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.api.GlobalSettings$$anonfun$onRouteRequest$1.apply(GlobalSettings.scala:126) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at scala.Option.flatMap(Option.scala:171) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at play.api.GlobalSettings$class.onRouteRequest(GlobalSettings.scala:126) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.api.DefaultGlobal$.onRouteRequest(GlobalSettings.scala:206) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.api.GlobalSettings$class.onRequestReceived(GlobalSettings.scala:81) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.api.DefaultGlobal$.onRequestReceived(GlobalSettings.scala:206) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.Server$$anonfun$sendHandler$1$1.apply(Server.scala:40) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.Server$$anonfun$sendHandler$1$1.apply(Server.scala:39) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.util.Try$.apply(Try.scala:192) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.util.Success.map(Try.scala:237) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at play.core.server.Server$class.sendHandler$1(Server.scala:39) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:72) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:71) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at scala.util.Either$RightProjection.flatMap(Either.scala:522) [org.scala-lang.scala-library-2.11.7.jar:na]
        at play.core.server.Server$class.getHandlerFor(Server.scala:71) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:39) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$10.apply(PlayDefaultUpstreamHandler.scala:157) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$10.apply(PlayDefaultUpstreamHandler.scala:157) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at scala.util.Either.fold(Either.scala:99) [org.scala-lang.scala-library-2.11.7.jar:na]
        at play.core.server.netty.PlayDefaultUpstreamHandler.messageReceived(PlayDefaultUpstreamHandler.scala:142) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [io.netty.netty-3.9.9.Final.jar:na]
        at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:62) [com.typesafe.netty.netty-http-pipelining-1.1.2.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [io.netty.netty-3.9.9.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
2015-09-02 17:48:12,659 - [ERROR] - from application in New I/O worker #1
Error while rendering default error page
scala.MatchError: java.lang.NoClassDefFoundError: Could not initialize class controllers.Application$ (of class java.lang.NoClassDefFoundError)
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:148) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.api.DefaultGlobal$.onError(GlobalSettings.scala:206) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:63) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:73) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:71) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at scala.util.Either$RightProjection.flatMap(Either.scala:522) [org.scala-lang.scala-library-2.11.7.jar:na]
        at play.core.server.Server$class.getHandlerFor(Server.scala:71) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:39) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$10.apply(PlayDefaultUpstreamHandler.scala:157) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$10.apply(PlayDefaultUpstreamHandler.scala:157) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at scala.util.Either.fold(Either.scala:99) [org.scala-lang.scala-library-2.11.7.jar:na]
        at play.core.server.netty.PlayDefaultUpstreamHandler.messageReceived(PlayDefaultUpstreamHandler.scala:142) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [io.netty.netty-3.9.9.Final.jar:na]
        at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:62) [com.typesafe.netty.netty-http-pipelining-1.1.2.jar:na]
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [io.netty.netty-3.9.9.Final.jar:na]
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [io.netty.netty-3.9.9.Final.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
````

**Comment by zmstone** [comment]
duplicated to #120 
fixed by adding this line in application.conf

````
application.features=["KMClusterManagerFeature","KMTopicManagerFeature","KMPreferredReplicaElectionFeature","KMReassignPartitionsFeature"]
````
