### ISSUE TITLE
"Unresolved dependencies path:" when building master 

### ISSUE THREAD

**Issue by sambit19** [yahoo/kafka-manager#147]
I followed the README. Is there anything that needs to be done?

The exception message:

[info] Loading project definition from /home/sti5kor/Software/kafka-manager/project
[info] Set current project to kafka-manager (in build file:/home/sti5kor/Software/kafka-manager/)
[success] Total time: 0 s, completed Oct 28, 2015 11:47:10 AM
[info] Updating {file:/home/sti5kor/Software/kafka-manager/}root...
[info] Packaging /home/sti5kor/Software/kafka-manager/target/scala-2.11/kafka-manager_2.11-1.2.9.10-sources.jar ...
[info] Wrote /home/sti5kor/Software/kafka-manager/target/scala-2.11/kafka-manager_2.11-1.2.9.10.pom
[info] Done packaging.
[info] Resolving com.typesafe.netty#netty-http-pipelining;1.1.2 ...
[error] Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target url=https://repo.typesafe.com/typesafe/releases/com/typesafe/netty/netty-http-pipelining/1.1.2/netty-http-pipelining-1.1.2.pom
[warn] 	module not found: com.typesafe.netty#netty-http-pipelining;1.1.2
[warn] ==== local: tried
[warn]   /home/sti5kor/.ivy2/local/com.typesafe.netty/netty-http-pipelining/1.1.2/ivys/ivy.xml
[warn] ==== sbt-releases-repo: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.netty/netty-http-pipelining/1.1.2/ivys/ivy.xml
[warn] ==== sbt-plugins-repo: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.netty/netty-http-pipelining/1.1.2/ivys/ivy.xml
[warn] ==== maven-central: tried
[warn]   http://repo1.maven.org/maven2/com/typesafe/netty/netty-http-pipelining/1.1.2/netty-http-pipelining-1.1.2.pom
[warn] ==== Typesafe Releases Repository: tried
[warn]   https://repo.typesafe.com/typesafe/releases/com/typesafe/netty/netty-http-pipelining/1.1.2/netty-http-pipelining-1.1.2.pom
[info] Resolving com.typesafe.play#play-doc_2.11;1.1.0 ...
[error] Server access Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target url=https://repo.typesafe.com/typesafe/releases/com/typesafe/play/play-doc_2.11/1.1.0/play-doc_2.11-1.1.0.pom
[warn] 	module not found: com.typesafe.play#play-doc_2.11;1.1.0
[warn] ==== local: tried
[warn]   /home/sti5kor/.ivy2/local/com.typesafe.play/play-doc_2.11/1.1.0/ivys/ivy.xml
[warn] ==== sbt-releases-repo: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.play/play-doc_2.11/1.1.0/ivys/ivy.xml
[warn] ==== sbt-plugins-repo: tried
[warn]   http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.play/play-doc_2.11/1.1.0/ivys/ivy.xml
[warn] ==== maven-central: tried
[warn]   http://repo1.maven.org/maven2/com/typesafe/play/play-doc_2.11/1.1.0/play-doc_2.11-1.1.0.pom
[warn] ==== Typesafe Releases Repository: tried
[warn]   https://repo.typesafe.com/typesafe/releases/com/typesafe/play/play-doc_2.11/1.1.0/play-doc_2.11-1.1.0.pom
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.netty#netty-http-pipelining;1.1.2: not found
[warn] 	:: com.typesafe.play#play-doc_2.11;1.1.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.typesafe.netty:netty-http-pipelining:1.1.2
[warn] 		  +- com.typesafe.play:play_2.11:2.3.10 ((play.PlaySettings) PlaySettings.scala#L78)
[warn] 		  +- com.typesafe.play:play-docs_2.11:2.3.10 ((play.PlaySettings) PlaySettings.scala#L89)
[warn] 		  +- kafka-manager:kafka-manager_2.11:1.2.9.10
[warn] 		com.typesafe.play:play-doc_2.11:1.1.0
[warn] 		  +- com.typesafe.play:play-docs_2.11:2.3.10 ((play.PlaySettings) PlaySettings.scala#L89)
[warn] 		  +- kafka-manager:kafka-manager_2.11:1.2.9.10
sbt.ResolveException: unresolved dependency: com.typesafe.netty#netty-http-pipelining;1.1.2: not found
unresolved dependency: com.typesafe.play#play-doc_2.11;1.1.0: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:294)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:127)
	at sbt.IvySbt.withIvy(Ivy.scala:124)
	at sbt.IvySbt$Module.withModule(Ivy.scala:155)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1392)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1388)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1422)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1420)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1425)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1419)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1442)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1371)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1325)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.typesafe.netty#netty-http-pipelining;1.1.2: not found
[error] unresolved dependency: com.typesafe.play#play-doc_2.11;1.1.0: not found
[error] Total time: 7 s, completed Oct 28, 2015 11:47:17 AM

**Comment by sambit19** [comment]
I managed to fix this issue by doing the steps below:

1. Set the proxy for sbt

export JAVA_OPTS="$JAVA_OPTS -Dhttp.proxyHost=ip of proxy -Dhttp.proxyPort=8080 -Dhttp.proxyUser=user -Dhttp.proxyPassword=pissword"

2. added the following to ~/.sbt/repositories file

[repositories]
  local
  sbt-releases-repo: http://repo.typesafe.com/typesafe/ivy-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  sbt-plugins-repo: http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  maven-central: http://repo1.maven.org/maven2/
  maven-sbt-release: http://repo.typesafe.com/typesafe/maven-releases/
  sonatype-releases: https://oss.sonatype.org/content/repositories/releases
  sonatype-snapshots: https://oss.sonatype.org/content/repositories/snapshots
  JBoss repository: https://repository.jboss.org/nexus/content/repositories
  Scalaz Bintray Repo: http://dl.bintray.com/scalaz/releases
  bintray/non: http://dl.bintray.com/non/maven

3. Run the command below to build

sbt -Dsbt.override.build.repos=true clean dist
