### ISSUE TITLE
HELP! java.util.concurrent.ThreadPoolExecutor

### ISSUE THREAD

**Issue by TimeEraser** [yahoo/kafka-manager#157]
##it really hit me that the app always comes with exceptions  When i run the application
when i use the application （1.2.9） to manager the kafka ， I found that it always can not run perfectly 。
Firstly，when I use the passsive offsetcash （pathchildcash），it will tell me that ask timeout 。。。。。even I double or ripled the timeout 。 。。。
Secondly，when I use the active offsetcash （treecash）， it will come out perfectly from the beginning，which makes me pretty excited . However , some description-data disappear with the time going  ...

To deal with the problem , I debug the application and find the following exceptions (active or passive): 
-------------------------------------------------------------------------------------------------------------------------------------------
$10.apply(KafkaStateActor.scala:668)
	at scala.Option.fold(Option.scala:158)
	at kafka.manager.KafkaStateActor.processQueryRequest(KafkaStateActor.scala:668)
	at kafka.manager.BaseQueryCommandActor.processActorRequest(BaseQueryCommandActor.scala:17)
	at kafka.manager.BaseActor$$anonfun$receive$1.applyOrElse(BaseActor.scala:24)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at kafka.manager.BaseActor.aroundReceive(BaseActor.scala:14)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable@7d11880b rejected from java.util.concurrent.ThreadPoolExecutor@7ab6a050[Running, pool size = 4, active threads = 4, queued tasks = 1000, completed tasks = 185]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:109)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$KeptPromise.onComplete(Promise.scala:333)
	at scala.concurrent.Future$class.onFailure(Future.scala:134)
	at scala.concurrent.impl.Promise$KeptPromise.onFailure(Promise.scala:322)
	at kafka.manager.OffsetCache$class.kafka$manager$OffsetCache$$loadPartitionOffsets(KafkaStateActor.scala:109)
	at kafka.manager.OffsetCache$$anon$1.load(KafkaStateActor.scala:51)
	at kafka.manager.OffsetCache$$anon$1.load(KafkaStateActor.scala:49)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at kafka.manager.OffsetCache$class.getTopicPartitionOffsets(KafkaStateActor.scala:123)
	at kafka.manager.OffsetCacheActive.getTopicPartitionOffsets(KafkaStateActor.scala:134)
	at kafka.manager.KafkaStateActor$$anonfun$getTopicDescription$2$$anonfun$apply$29.apply(KafkaStateActor.scala:548)
	at kafka.manager.KafkaStateActor$$anonfun$getTopicDescription$2$$anonfun$apply$29.apply(KafkaStateActor.scala:543)
	at scala.Option$WithFilter.map(Option.scala:207)
	at kafka.manager.KafkaStateActor$$anonfun$getTopicDescription$2.apply(KafkaStateActor.scala:543)
	at kafka.manager.KafkaStateActor$$anonfun$getTopicDescription$2.apply(KafkaStateActor.scala:541)
	at scala.Option.flatMap(Option.scala:171)
	at kafka.manager.KafkaStateActor.getTopicDescription(KafkaStateActor.scala:541)
	at kafka.manager.KafkaStateActor$$anonfun$processQueryRequest$10$$anonfun$apply$35.apply(KafkaStateActor.scala:669)
	at kafka.manager.KafkaStateActor$$anonfun$processQueryRequest$10$$anonfun$apply$35.apply(KafkaStateActor.scala:669)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at kafka.manager.KafkaStateActor$$anonfun$processQueryRequest$10.apply(KafkaStateActor.scala:669)
	at kafka.manager.KafkaStateActor$$anonfun$processQueryRequest$10.apply(KafkaStateActor.scala:668)
	at scala.Option.fold(Option.scala:158)
	at kafka.manager.KafkaStateActor.processQueryRequest(KafkaStateActor.scala:668)
	at kafka.manager.BaseQueryCommandActor.processActorRequest(BaseQueryCommandActor.scala:17)
	at kafka.manager.BaseActor$$anonfun$receive$1.applyOrElse(BaseActor.scala:24)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at kafka.manager.BaseActor.aroundReceive(BaseActor.scala:14)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

many....................many....................many like this
------------------------------------------------------------------------
so what is the really problem ? Or I make some stupid mistakes.

**Comment by TimeEraser** [comment]
I found that the offsetcash hardly effect the performance when the cluster becomes large ! How to deal with it ? it makes me so worried

**Comment by TimeEraser** [comment]
when I use the 1.2.9 online I found  interesting results 
Firstly let's see the KSGetAllTopicDescriptions request 
2015-11-19T17:26:39.422+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/kafka-state#-1492611530]--KSGetAllTopicDescriptions(None)
2015-11-19T17:26:41.887+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/onlinekafka/kafka-state#263831922]--KSGetAllTopicDescriptions(None)
2015-11-19T17:26:48.705+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/onlinekafka/kafka-state#263831922]--KSGetAllTopicDescriptions(Some(1447925198699))
2015-11-19T17:26:48.756+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/kafka-state#-1492611530]--KSGetAllTopicDescriptions(Some(1447925198706))
2015-11-19T17:26:58.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/kafka-state#-1492611530]--KSGetAllTopicDescriptions(Some(1447925198706))
2015-11-19T17:26:58.754+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/onlinekafka/kafka-state#263831922]--KSGetAllTopicDescriptions(Some(1447925198699))
2015-11-19T17:27:08.714+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/onlinekafka/kafka-state#263831922]--KSGetAllTopicDescriptions(Some(1447925198699))
2015-11-19T17:27:08.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/kafka-state#-1492611530]--KSGetAllTopicDescriptions(Some(1447925198706))
2015-11-19T17:27:18.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/kafka-state#-1492611530]--KSGetAllTopicDescriptions(Some(1447925198706))
2015-11-19T17:27:18.725+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/onlinekafka/kafka-state#263831922]--KSGetAllTopicDescriptions(Some(1447925198699))
2015-11-19T17:27:28.714+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/onlinekafka/kafka-state#263831922]--KSGetAllTopicDescriptions(Some(1447925198699))
2015-11-19T17:27:28.726+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/kafka-state#-1492611530]--KSGetAllTopicDescriptions(Some(1447925198706))
2015-11-19T17:27:38.725+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/onlinekafka/kafka-state#263831922]--KSGetAllTopicDescriptions(Some(1447925198699))
2015-11-19T17:27:38.725+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/kafka-state#-1492611530]--KSGetAllTopicDescriptions(Some(1447925198706))
2015-11-19T17:27:48.714+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/onlinekafka/kafka-state#263831922]--KSGetAllTopicDescriptions(Some(1447925198699))
2015-11-19T17:27:48.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/kafka-state#-1492611530]--KSGetAllTopicDescriptions(Some(1447925198706))
2015-11-19T17:27:58.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/kafka-state#-1492611530]--KSGetAllTopicDescriptions(Some(1447925198706))
2015-11-19T17:28:08.725+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/kafka-state#-1492611530]--KSGetAllTopicDescriptions(Some(1447925198706))
2015-11-19T17:28:18.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/kafka-state#-1492611530]--KSGetAllTopicDescriptions(Some(1447925198706))
2015-11-19T17:28:28.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/kafka-state#-1492611530]--KSGetAllTopicDescriptions(Some(1447925198706))
2015-11-19T17:28:38.725+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/kafka-state#-1492611530]--KSGetAllTopicDescriptions(Some(1447925198706))
2015-11-19T17:28:48.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/kafka-state#-1492611530]--KSGetAllTopicDescriptions(Some(1447925198706))
2015-11-19T17:28:58.725+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/kafka-state#-1492611530]--KSGetAllTopicDescriptions(Some(1447925198706))
--------------------------------------------------------------------------------------------------
secondly let's see BVForceUpdate
2015-11-19T17:26:38.708+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/broker-view#-2047212123]--BVForceUpdate
2015-11-19T17:26:48.704+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/onlinekafka/broker-view#960180325]--BVForceUpdate
2015-11-19T17:26:48.755+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/broker-view#-2047212123]--BVForceUpdate
2015-11-19T17:26:58.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/broker-view#-2047212123]--BVForceUpdate
2015-11-19T17:26:58.754+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/onlinekafka/broker-view#960180325]--BVForceUpdate
2015-11-19T17:27:08.714+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/onlinekafka/broker-view#960180325]--BVForceUpdate
2015-11-19T17:27:08.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/broker-view#-2047212123]--BVForceUpdate
2015-11-19T17:27:18.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/broker-view#-2047212123]--BVForceUpdate
2015-11-19T17:27:18.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/onlinekafka/broker-view#960180325]--BVForceUpdate
2015-11-19T17:27:28.714+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/onlinekafka/broker-view#960180325]--BVForceUpdate
2015-11-19T17:27:28.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/broker-view#-2047212123]--BVForceUpdate
2015-11-19T17:27:38.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/onlinekafka/broker-view#960180325]--BVForceUpdate
2015-11-19T17:27:38.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/broker-view#-2047212123]--BVForceUpdate
2015-11-19T17:27:48.714+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/onlinekafka/broker-view#960180325]--BVForceUpdate
2015-11-19T17:27:48.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/broker-view#-2047212123]--BVForceUpdate
2015-11-19T17:27:58.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/broker-view#-2047212123]--BVForceUpdate
2015-11-19T17:28:08.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/broker-view#-2047212123]--BVForceUpdate
2015-11-19T17:28:18.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/broker-view#-2047212123]--BVForceUpdate
2015-11-19T17:28:28.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/broker-view#-2047212123]--BVForceUpdate
2015-11-19T17:28:38.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/broker-view#-2047212123]--BVForceUpdate
2015-11-19T17:28:48.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/broker-view#-2047212123]--BVForceUpdate
2015-11-19T17:28:58.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/broker-view#-2047212123]--BVForceUpdate
2015-11-19T17:29:08.724+08:00:Actor[akka://kafka-manager-system/user/kafka-manager/pigeon/broker-view#-2047212123]--BVForceUpdate


we can conclude that after 2015-11-19T17:27:48 the onlinekafka's brokerviewCasheActor is blocked .
