### ISSUE TITLE
sbt clean dist

### ISSUE THREAD

**Issue by 467754239** [yahoo/kafka-manager#177]
$ sudo sbt clean dist
Getting org.scala-sbt sbt 0.13.9 ...

:: problems summary ::
:::: WARNINGS
	problem while downloading module descriptor: https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml: Connection timed out (38037ms)

		module not found: org.scala-sbt#sbt;0.13.9

	==== local: tried

	  /root/.ivy2/local/org.scala-sbt/sbt/0.13.9/ivys/ivy.xml

	  -- artifact org.scala-sbt#sbt;0.13.9!sbt.jar:

	  /root/.ivy2/local/org.scala-sbt/sbt/0.13.9/jars/sbt.jar

	==== jcenter: tried

**Comment by DavidLiuXh** [comment]
use vpn or proxy

**Comment by Penguicannotfly** [comment]
add ***export SBT_OPTS="$SBT_OPTS -Dhttp.proxyHost=myproxy -Dhttp.proxyPort=myport*** in file sbt

**Comment by patelh** [comment]
Give, it would be great if you could contribute to the README :)

**Comment by saurabhmishra** [comment]
What i am doing wrong here...tried sbt 0.13.9 and 0.13.8 both errors out.

 PATH="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/":$PATH \
>   JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home" \
>   /usr/local/bin/sbt -v -java-home "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home" rpm:packageBin
[process_args] java_version = '1.8.0_65'
# Executing command line:
"/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java"
-Xms1024m
-Xmx1024m
-XX:ReservedCodeCacheSize=128m
-XX:MaxMetaspaceSize=256m
-jar
/usr/local/Cellar/sbt/0.13.9/bin/sbt-launch.jar
rpm:packageBin

[info] Loading project definition from /Users/saurabh_mishra/Downloads/kafka-manager-master/project
Missing bintray credentials /Users/saurabh_mishra/.bintray/.credentials. Some bintray features depend on this.
[info] Set current project to kafka-manager (in build file:/Users/saurabh_mishra/Downloads/kafka-manager-master/)
[warn] Credentials file /Users/saurabh_mishra/.bintray/.credentials does not exist
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/saurabh_mishra/.ivy2/cache/org.slf4j/slf4j-nop/jars/slf4j-nop-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/saurabh_mishra/.ivy2/cache/org.slf4j/slf4j-simple/jars/slf4j-simple-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.helpers.NOPLoggerFactory]
[info] Updating {file:/Users/saurabh_mishra/Downloads/kafka-manager-master/}root...
[info] Wrote /Users/saurabh_mishra/Downloads/kafka-manager-master/target/scala-2.11/kafka-manager_2.11-1.3.0.4.pom
[info] Resolving javax.inject#javax.inject;1 ...
Warning: node.js detection failed, sbt will use the Rhino based Trireme JavaScript engine instead to run JavaScript assets compilation, which in some cases may be orders of magni[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* org.webjars:jquery:1.11.1 -> 2.1.4
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 120 Scala sources and 2 Java sources to /Users/saurabh_mishra/Downloads/kafka-manager-master/target/scala-2.11/classes...
[info] Packaging /Users/saurabh_mishra/Downloads/kafka-manager-master/target/scala-2.11/kafka-manager_2.11-1.3.0.4-web-assets.jar ...
[info] Done packaging.
[error] (compile:compileIncremental) javac returned nonzero exit code
[error] Total time: 26 s, completed Jan 7, 2016 5:27:31 PM

**Comment by emmanuel** [comment]
@saurabhmishra it looks like you're trying to use an installation of the JRE to perform the build. You need a full JDK, since the JRE does not include `javac` (the Java compiler).

**Comment by tarunsas** [comment]
Hi emmanuel,

I use JDK 1.8 and still cannot build.

but in boot/update.log i see

impossible to define new type: class not found: org.apache.ivy.plugins.resolver.VfsResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.plugins.resolver.JarResolver in [] nor Ivy classloader
impossible to define new type: class not found: org.apache.ivy.osgi.obr.OBRResolver in [] nor Ivy classloader
impossible to define glob matcher: org.apache.ivy.plugins.matcher.GlobPatternMatcher was not found.
setting 'jline.esc.timeout' to '0'
setting 'java.runtime.name' to 'Java(TM) SE Runtime Environment'
setting 'sun.boot.library.path' to '/usr/lib/jvm/java-8-oracle/jre/lib/amd64'
setting 'java.vm.version' to '25.60-b23'

:: problems summary ::
:::: ERRORS
        org.scala-lang#scala-reflect;2.10.5!scala-reflect.jar origin location must be absolute: file:/home/parallels/.m2/repository/org/scala-lang/sca$

Any help please.

**Comment by waltari2001** [comment]
Having the same issue. Any of you guys has found a solution?

**Comment by adsizzler** [comment]
Getting error

java.io.IOException: Cannot run program "/bin/javac" (in directory "/opt/kafka-manager"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
	at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:128)
	at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
	at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
	at sbt.compiler.javac.JavacLogger.buffer(JavacProcessLogger.scala:31)
	at sbt.AbstractProcessBuilder.runBuffered(ProcessImpl.scala:159)
	at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:156)
	at sbt.compiler.javac.ForkedJava$$anonfun$launch$1.apply(ForkedJava.scala:24)
	at sbt.compiler.javac.ForkedJava$$anonfun$launch$1.apply(ForkedJava.scala:17)
	at sbt.compiler.javac.ForkedJava$$anonfun$withArgumentFile$1.apply(ForkedJava.scala:47)
	at sbt.compiler.javac.ForkedJava$$anonfun$withArgumentFile$1.apply(ForkedJava.scala:44)
	at sbt.IO$.withTemporaryDirectory(IO.scala:291)
	at sbt.compiler.javac.ForkedJava$.withArgumentFile(ForkedJava.scala:44)
	at sbt.compiler.javac.ForkedJava$.launch(ForkedJava.scala:17)
	at sbt.compiler.javac.ForkedJavaCompiler.run(ForkedJava.scala:68)
	at sbt.compiler.javac.JavaCompilerAdapter.compileWithReporter(JavaCompilerAdapter.scala:31)
	at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply$mcV$sp(AnalyzingJavaCompiler.scala:65)
	at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply(AnalyzingJavaCompiler.scala:65)
	at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply(AnalyzingJavaCompiler.scala:65)
	at sbt.compiler.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:93)
	at sbt.compiler.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:64)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:61)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply(MixedAnalyzingCompiler.scala:61)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply(MixedAnalyzingCompiler.scala:61)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:75)
	at sbt.compiler.MixedAnalyzingCompiler.compileJava$1(MixedAnalyzingCompiler.scala:60)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:65)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:62)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:61)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:89)
	at sbt.inc.Incremental$.compile(Incremental.scala:61)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:128)
	at sbt.Compiler$.compile(Compiler.scala:114)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:829)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:820)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:818)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
	at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:128)
	at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
	at sbt.AbstractProcessBuilder$$anonfun$runBuffered$1.apply(ProcessImpl.scala:159)
	at sbt.compiler.javac.JavacLogger.buffer(JavacProcessLogger.scala:31)
	at sbt.AbstractProcessBuilder.runBuffered(ProcessImpl.scala:159)
	at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:156)
	at sbt.compiler.javac.ForkedJava$$anonfun$launch$1.apply(ForkedJava.scala:24)
	at sbt.compiler.javac.ForkedJava$$anonfun$launch$1.apply(ForkedJava.scala:17)
	at sbt.compiler.javac.ForkedJava$$anonfun$withArgumentFile$1.apply(ForkedJava.scala:47)
	at sbt.compiler.javac.ForkedJava$$anonfun$withArgumentFile$1.apply(ForkedJava.scala:44)
	at sbt.IO$.withTemporaryDirectory(IO.scala:291)
	at sbt.compiler.javac.ForkedJava$.withArgumentFile(ForkedJava.scala:44)
	at sbt.compiler.javac.ForkedJava$.launch(ForkedJava.scala:17)
	at sbt.compiler.javac.ForkedJavaCompiler.run(ForkedJava.scala:68)
	at sbt.compiler.javac.JavaCompilerAdapter.compileWithReporter(JavaCompilerAdapter.scala:31)
	at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply$mcV$sp(AnalyzingJavaCompiler.scala:65)
	at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply(AnalyzingJavaCompiler.scala:65)
	at sbt.compiler.javac.AnalyzingJavaCompiler$$anonfun$compile$1.apply(AnalyzingJavaCompiler.scala:65)
	at sbt.compiler.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:93)
	at sbt.compiler.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:64)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:61)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply(MixedAnalyzingCompiler.scala:61)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileJava$1$1.apply(MixedAnalyzingCompiler.scala:61)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:75)
	at sbt.compiler.MixedAnalyzingCompiler.compileJava$1(MixedAnalyzingCompiler.scala:60)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:65)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:62)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:61)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:89)
	at sbt.inc.Incremental$.compile(Incremental.scala:61)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:128)
	at sbt.Compiler$.compile(Compiler.scala:114)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:829)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:820)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:818)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (compile:compileIncremental) java.io.IOException: Cannot run program "/bin/javac" (in directory "/opt/kafka-manager"): error=2, No such file or directory

**Comment by mapattacker** [comment]
same issue as @ranjeetranjan . Anyone can help?

**Comment by mapattacker** [comment]
Hi all, managed to execute the sbt clean dist properly now. The issue is that javac is not installed in the java version. Just follow this tutorial to reinstall https://www3.ntu.edu.sg/home/ehchua/programming/howto/JDK_Howto.html. It should do fine after that.

**Comment by disizjay** [comment]
I have uploaded the build files, RPM and DEB packages. Hope that's useful!
https://github.com/disizjay/kafka-manager
