### ISSUE TITLE
Broker Metrics not being shown up in the UI

### ISSUE THREAD

**Issue by suhas22** [yahoo/kafka-manager#186]
Hi Team,
First of all thanks for putting up a great application, it's really useful to understand what's going with 100 odd brokers that we have in our cluster :)

I am however facing a few issues while trying to view the broker metrics.
1) I have setup the latest version of kafka manager, i.e  1.3.0.4.
2) Was able to add our prod zk/brokers successfully.
3) But when i try to view the broker information such as combined metrics, nothing shows up, but i go to the topics page, i can view the different topics available and the size of the data coming in.

Brokers home page:
![image](https://cloud.githubusercontent.com/assets/16332828/12205556/816ab280-b661-11e5-836c-0cb1d1dfeafd.png)

Topics home page : 
![image](https://cloud.githubusercontent.com/assets/16332828/12205582/a2fe8ade-b661-11e5-9c36-332fca338aea.png)

I browsed through a couple of issues related to this, and it was said that the issue was resolved in the master build, but looks like it isn't.(https://github.com/yahoo/kafka-manager/issues/69)
Any help here would be greatly appreciated.

**Comment by rphillips** [comment]
I ran across the same issue with a 3 node cluster.

**Comment by patelh** [comment]
Do you have JMX enabled for kafka brokers?  If so, did you enable JMX polling in the configuration of the cluster in Kafka Manager?

**Comment by rphillips** [comment]
I do not have JMX enabled. Is this a requirement?

**Comment by suhas22** [comment]
Yes, I have JMX enabled for the brokers and also have enabled jmx polling
while configuring the cluster on kafka manager.

**Comment by patelh** [comment]
@rphillips Yes, you need to enable JMX for metrics.  No other way right now.

@suhas22 What version of Kafka?

**Comment by suhas22** [comment]
Hi,
I am using Kafka 0.8.2

**Comment by patelh** [comment]
@suhas22 Do you see any errors in the logs?  Are you using 0.8.2.0, 0.8.2.1, or 0.8.2.2 ?

**Comment by suhas22** [comment]
Hi,
Sorry, It was a typo while mentioning the version, I am currently on
0.8.2.1.
I don't see any specific errors to this issue.
Part information is see though  like Topic related information is seen such
as offsets, leaders etc, but the metrics is not be seen as a whole.

**Comment by patelh** [comment]
Are you using Oracle JDK8 or OpenJDK8 ?

**Comment by suhas22** [comment]
Oracle JDK8

**Comment by patelh** [comment]
Hm, it is odd that you don't see any exceptions related to connecting to JMX or something similar.  Are you able to connect to the broker and see the metrics using JConsole ?  Did you configure a custom metrics reporter in your kafka server.properties ?

**Comment by suhas22** [comment]
I have a distributed system setup all on cloud, am running kafka manager on
Zookeeper cluster where i have oracle java 8 installed, but my brokers are
on java 7.
Jconsole just doesn't start on the zookeeper.
I did not understand this statement"Did you configure a custom metrics
reporter in your kafka server.properties"  What do we need to do to
configure custom metrics reporter ?

When i access the kafka manager UI, it lists all the brokers that the
zookeepers are connected to and gives the details of all the topics like
offsets, partitions etc but gives nothing for brokers.
So is the java version a issue here ?

**Comment by suhas22** [comment]
Hi,
I did a brand new setup, and saw that we have a new version now, but again I am seeing the same issue .
Here are the errors that's showing up now , it says connection refused to port 9997.
But I have jmx port 9997 opened up and Kafka is listening at this port.

[error] k.m.j.KafkaJMX$ - Failed to connect to service:jmx:rmi:///jndi/rmi://kafka-2-broker-24:9997/jmxrmi
java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is: 
        java.net.ConnectException: Connection refused
        at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[na:1.8.0_74]
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216) ~[na:1.8.0_74]
        at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202) ~[na:1.8.0_74]
        at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:130) ~[na:1.8.0_74]
        at javax.management.remote.rmi.RMIServerImpl_Stub.newClient(Unknown Source) ~[na:1.8.0_74]
        at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2430) ~[na:1.8.0_74]
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:308) ~[na:1.8.0_74]
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[na:1.8.0_74]
        at kafka.manager.jmx.KafkaJMX$.doWithConnection(KafkaJMX.scala:50) ~[kafka-manager.kafka-manager-1.3.0.4-sans-externalized.jar:na]
        at kafka.manager.actor.cluster.BrokerViewCacheActor$$anonfun$kafka$manager$actor$cluster$BrokerViewCacheActor$$updateBrokerTopicPartitionsSize$1$$anonfun$apply$29$$anonfun$apply$4.apply$mcV$sp(BrokerViewCacheActor.scala:382) [kafka-manager.kafka-manager-1.3.0.4-sans-externalized.jar:na]
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_74]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_74]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_74]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_74]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_74]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_74]
        at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_74]
        at java.net.Socket.<init>(Socket.java:434) ~[na:1.8.0_74]
        at java.net.Socket.<init>(Socket.java:211) ~[na:1.8.0_74]
        at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40) ~[na:1.8.0_74]


And here is the screenshot of my kafka process and port 9997 opened up and kafka is listening to it.

![image](https://cloud.githubusercontent.com/assets/16332828/13741420/3c870bd6-e9fc-11e5-9b22-31a1036c7205.png)

**Comment by suhas22** [comment]
The more I see the error, I get to think it's due to the Java version difference.
I have my broker's and ZK's running on java 7, where as just for Kakfa manager I installed Java 8, as it won't install with Java 7.
And the error also points to java 1.8 RMI connector stuff, Is my assumption correct ?

**Comment by xavierpayne** [comment]
I had a similar problem. The cause is the initial port 9997 is just the port that starts the connection. After the initial connection JMX negotiates a random port and uses that for the rest of the communication.

This article explains it better than I can:
https://olegz.wordpress.com/2009/03/23/jmx-connectivity-through-the-firewall/

Unfortunately the solution is to open the entire range that it picks it's random port numbers from.

**Comment by keithjpaulson** [comment]
JDK7_45(?) and later should support -Dcom.sun.management.jmxremote.rmi.port=xxxx so the RMI port is not randomly chosen (I have not yet tried this).

**Comment by krishna81m** [comment]
Same here, as a newbie, setup a Open JDK 1.7.0_101 Kafka 0.9.0.1 cluster and started kafka manager with JMX enabled as I can see kafka-manager picked up the JMX port but the bytes is 0 everywere.

**Comment by 1ambda** [comment]
the JMX server which is running on broker will open the RMI port, you might need to specify RMI port also (`-Dcom.sun.management.jmxremote.rmi.port=10000`)

For example, 

```
JMX_PORT=9999 KAFKA_JMX_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=10000 -Djava.rmi.server.hostname=$HOSTNAME" ./bin/kafka-server-start.sh -daemon ./config/server.properties
```

**Comment by WillCup** [comment]
This happens to me too. Kafka broker based on JDK1.8.0_60.
And I use a kafka-manager docker container : https://hub.docker.com/r/sheepkiller/kafka-manager/~/dockerfile/

The problem is all the same with this issue. And I have tried the JConsole connection, it do work, I can see all the jmx metrics from JConsole.


![image](https://user-images.githubusercontent.com/7053864/29199468-c61d3104-7e7f-11e7-828b-3b022b8fb294.png)


![image](https://user-images.githubusercontent.com/7053864/29199457-b4306fba-7e7f-11e7-9908-89673ea1d550.png)

**Comment by shades198** [comment]
adding -Djava.rmi.server.hostname option didn't change anything. It seems as if this option is not taking any effect. Please help. I also have the same scenario wherein I have 3 brokers and kafka-manager is able to read metrics only from the server on which it is running.

**Comment by jimymodi** [comment]
@shades198 Did you found a fix around it ?

**Comment by funkol2007** [comment]
I enabled KAFKA_JMX_OPTS and the settings are followings:
JMX_PORT='23311'
KAFKA_JMX_OPTS='-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=23311'

But I still can't get Combined Metrics 
![image](https://user-images.githubusercontent.com/3076515/69215962-ef44e300-0ba5-11ea-99aa-2ce469b3a312.png)
