### ISSUE TITLE
kafka-manager can't start after crash due to " requirement failed: No jmx port but jmx polling enabled"

### ISSUE THREAD

**Issue by zousheng** [yahoo/kafka-manager#203]
Recently I ticked the jmx pooling in the web UI, but after application crash, the kafka-manager can't start any more, I can't find a place to remote jmx pooling config. is there any way to handle this error?

thanks

**Comment by zousheng** [comment]
The error message is as below:

2016-02-29 10:54:16,521 - [ERROR] - from kafka.manager.BrokerViewCacheActor in kafka-manager-system-akka.actor.default-dispatcher-39
Failed to get broker metrics for BrokerIdentity(2,kefu-ali-hangzhou-kfkafka3,9092,-1)
java.lang.IllegalArgumentException: requirement failed: No jmx port but jmx polling enabled!
        at scala.Predef$.require(Predef.scala:219) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at kafka.manager.KafkaJMX$.doWithConnection(KafkaJMX.scala:43) ~[kafka-manager.kafka-manager-1.2.9.14.jar:1.2.9.14]

**Comment by patelh** [comment]
This should not cause the application to crash.  It would just print the error message.  Do you see anything else in the logs?

**Comment by zousheng** [comment]
Thanks, already found the root cause, the vps had no bandwidth suddenly, after paying for the bandwidth, it's working again.
