### ISSUE TITLE
i cannot use database in kafka manager, because kafka manager cannot specify the database

### ISSUE THREAD

**Issue by universally2** [yahoo/kafka-manager#206]
i want to use Mysql in kafka manager, so i try to specify the database in application.conf:
db.test.driver=com.mysql.jdbc.Driver
db.test.url="jdbc:mysql://*******"
db.test.username=**
db.test.password=**

But it come to 
[InstantiationException: play.api.db.DBApi]
Caused by: java.lang.InstantiationException: play.api.db.DBApi
	at java.lang.Class.newInstance(Class.java:427) ~[na:1.8.0_71]
	at play.api.inject.NewInstanceInjector$.instanceOf(Injector.scala:49) ~[play_2.11-2.4.4.jar:2.4.4]
	at play.api.inject.SimpleInjector$$anonfun$instanceOf$1.apply(Injector.scala:85) ~[play_2.11-2.4.4.jar:2.4.4]
	at scala.collection.MapLike$class.getOrElse(MapLike.scala:128) ~[scala-library-2.11.7.jar:na]
	at scala.collection.AbstractMap.getOrElse(Map.scala:59) ~[scala-library-2.11.7.jar:na]
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:85) ~[play_2.11-2.4.4.jar:2.4.4]
	at play.api.inject.SimpleInjector.instanceOf(Injector.scala:80) ~[play_2.11-2.4.4.jar:2.4.4]
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:235) ~[play_2.11-2.4.4.jar:2.4.4]
	at play.api.Application$$anonfun$instanceCache$1.apply(Application.scala:235) ~[play_2.11-2.4.4.jar:2.4.4]
	at play.utils.InlineCache.fresh(InlineCache.scala:69) ~[play_2.11-2.4.4.jar:2.4.4]
	at play.utils.InlineCache.apply(InlineCache.scala:55) ~[play_2.11-2.4.4.jar:2.4.4]
	at play.api.db.DB$.db(DB.scala:22) ~[play-jdbc_2.11-2.4.4.jar:2.4.4]
	at play.api.db.DB$.withConnection(DB.scala:61) ~[play-jdbc_2.11-2.4.4.jar:2.4.4]
	at models.Authority$.getUserAuthority(Authority.scala:23) ~[classes/:na]
	at controllers.Application$$anonfun$index$1$$anonfun$apply$6$$anonfun$apply$7.apply(Application.scala:91) ~[classes/:na]
	at controllers.Application$$anonfun$index$1$$anonfun$apply$6$$anonfun$apply$7.apply(Application.scala:90) ~[classes/:na]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.7.jar:na]
	at controllers.Application$$anonfun$index$1$$anonfun$apply$6.apply(Application.scala:90) ~[classes/:na]
	at controllers.Application$$anonfun$index$1$$anonfun$apply$6.apply(Application.scala:89) ~[classes/:na]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[scala-library-2.11.7.jar:na]
	at scala.util.Try$.apply(Try.scala:192) [scala-library-2.11.7.jar:na]
	at scala.util.Success.map(Try.scala:237) ~[scala-library-2.11.7.jar:na]
	... 15 common frames omitted

at "
DB.withConnection("test") { implicit c =>
     SQL("select * from task").as(task *)
 } "
or "
object DB {

  private val dbCache = Application.instanceCache[MyDBApi]
  private def db(implicit app: Application): MyDBApi = {
    dbCache(app)        //here
  }
  ......
} " in DB.scala

i think kafka manager never used the setting .
can i use Mysql in kafka manager?
what should i do when i want to use Mysql in kafka manager?

**Comment by patelh** [comment]
Kafka manager does not use any database so you don't need to specify it.  It stores all state in ZooKeeper.  Hence there is no mention of DB configuration in our README.

**Comment by universally2** [comment]
thank you , i have found the solution.
http://blog.csdn.net/thewolf2
