### ISSUE TITLE
Build error on master

### ISSUE THREAD

**Issue by KurtYoung** [yahoo/kafka-manager#234]
I got this error when build from the master:

com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: /Users/ykt/IdeaProjects/kafka-manager/project/target/node-modules/webjars/less/lib/less/index.js:13
        functions: require('./functions')(environment),
                                         ^

TypeError: require(...) is not a function
    at module.exports (/Users/ykt/IdeaProjects/kafka-manager/project/target/node-modules/webjars/less/lib/less/index.js:13:42)
    at Object.<anonymous> (/Users/ykt/IdeaProjects/kafka-manager/project/target/node-modules/webjars/less/lib/less-node/index.js:5:12)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/ykt/IdeaProjects/kafka-manager/project/target/node-modules/webjars/less/index.js:1:80)
    at Module._compile (module.js:425:26)

	at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:195)
	at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:167)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by KurtYoung** [comment]
My bad, i used a wrong version of java and it caused this problem.
Need to delete project/project and project/target, and all things work fine.
