### ISSUE TITLE
support for 0.10.0.0?

### ISSUE THREAD

**Issue by hengheng0haha** [yahoo/kafka-manager#238]

**Comment by weand** [comment]
Getting continuously WARNINGS like this when connecting to Kafka 0.10.0

```
[warn] k.c.ConsumerFetcherManager$LeaderFinderThread - [KafkaManagerOffsetCache_04160b48ba5b-1464964908716-d110efc9-leader-finder-thread], Failed to find leader for Set([__consumer_offsets,16], [__consumer_offsets,2], [__consumer_offsets,39], [__consumer_offsets,15], [__consumer_offsets,33], [__consumer_offsets,38], [__consumer_offsets,9], [__consumer_offsets,7], [__consumer_offsets,31], [__consumer_offsets,48], [__consumer_offsets,24], [__consumer_offsets,19], [__consumer_offsets,11], [__consumer_offsets,22], [__consumer_offsets,26], [__consumer_offsets,17], [__consumer_offsets,10], [__consumer_offsets,35], [__consumer_offsets,36], [__consumer_offsets,34], [__consumer_offsets,49], [__consumer_offsets,44], [__consumer_offsets,23], [__consumer_offsets,40], [__consumer_offsets,47], [__consumer_offsets,45], [__consumer_offsets,43], [__consumer_offsets,46], [__consumer_offsets,37], [__consumer_offsets,28], [__consumer_offsets,27], [__consumer_offsets,25], [__consumer_offsets,6], [__consumer_offsets,5], [__consumer_offsets,3], [__consumer_offsets,18], [__consumer_offsets,14], [__consumer_offsets,41], [__consumer_offsets,42], [__consumer_offsets,4], [__consumer_offsets,12], [__consumer_offsets,21], [__consumer_offsets,30], [__consumer_offsets,1], [__consumer_offsets,32], [__consumer_offsets,13], [__consumer_offsets,8], [__consumer_offsets,20], [__consumer_offsets,0], [__consumer_offsets,29])
kafka.common.KafkaException: fetching topic metadata for topics [Set(__consumer_offsets)] from broker [ArrayBuffer(BrokerEndPoint(0,localhost,9092))] failed
        at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:73) ~[org.apache.kafka.kafka_2.11-0.9.0.1.jar:na]
        at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:94) ~[org.apache.kafka.kafka_2.11-0.9.0.1.jar:na]
        at kafka.consumer.ConsumerFetcherManager$LeaderFinderThread.doWork(ConsumerFetcherManager.scala:66) ~[org.apache.kafka.kafka_2.11-0.9.0.1.jar:na]
        at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63) [org.apache.kafka.kafka_2.11-0.9.0.1.jar:na]
Caused by: java.nio.channels.ClosedChannelException: null
        at kafka.network.BlockingChannel.send(BlockingChannel.scala:110) ~[org.apache.kafka.kafka_2.11-0.9.0.1.jar:na]
        at kafka.producer.SyncProducer.liftedTree1$1(SyncProducer.scala:75) ~[org.apache.kafka.kafka_2.11-0.9.0.1.jar:na]
        at kafka.producer.SyncProducer.kafka$producer$SyncProducer$$doSend(SyncProducer.scala:74) ~[org.apache.kafka.kafka_2.11-0.9.0.1.jar:na]
        at kafka.producer.SyncProducer.send(SyncProducer.scala:119) ~[org.apache.kafka.kafka_2.11-0.9.0.1.jar:na]
        at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:59) ~[org.apache.kafka.kafka_2.11-0.9.0.1.jar:na]
        ... 3 common frames omitted
[warn] k.c.ClientUtils$ - Fetching topic metadata with correlation id 247 for topics [Set(__consumer_offsets)] from broker [BrokerEndPoint(0,localhost,9092)] failed
java.nio.channels.ClosedChannelException: null
        at kafka.network.BlockingChannel.send(BlockingChannel.scala:110) ~[org.apache.kafka.kafka_2.11-0.9.0.1.jar:na]
        at kafka.producer.SyncProducer.liftedTree1$1(SyncProducer.scala:75) ~[org.apache.kafka.kafka_2.11-0.9.0.1.jar:na]
        at kafka.producer.SyncProducer.kafka$producer$SyncProducer$$doSend(SyncProducer.scala:74) ~[org.apache.kafka.kafka_2.11-0.9.0.1.jar:na]
        at kafka.producer.SyncProducer.send(SyncProducer.scala:119) ~[org.apache.kafka.kafka_2.11-0.9.0.1.jar:na]
        at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:59) [org.apache.kafka.kafka_2.11-0.9.0.1.jar:na]
        at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:94) [org.apache.kafka.kafka_2.11-0.9.0.1.jar:na]
        at kafka.consumer.ConsumerFetcherManager$LeaderFinderThread.doWork(ConsumerFetcherManager.scala:66) [org.apache.kafka.kafka_2.11-0.9.0.1.jar:na]
        at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63) [org.apache.kafka.kafka_2.11-0.9.0.1.jar:na]
```

**Comment by bwzhang2011** [comment]
any update with such issue ? as such new kafka version has been released. by they way, is there any plan to have more metric option to monitor each topic counter.

**Comment by twtiyb** [comment]
Consumers consuming from this topic
is null.

for 0.10.0.0 with jmx

**Comment by sambit19** [comment]
I recently upgraded the kafka cluster to 0.10. But in Kafka-Manager it gives me a option to select 0.8.2.X as the kafka version. How do you access a kafka 0.10 cluster?

**Comment by sambit19** [comment]
kafka manager docs say that it supports 0.8.x and 0.9 of kafka. So 0.10 won't work.

**Comment by hakanilter** [comment]
When do you plan to add 0.10 support?

**Comment by RodrigoLimasss** [comment]
Forecast for 0.10 support ? Thanks

**Comment by zhjt80** [comment]
+1

**Comment by KulikovaLidia** [comment]
+1

**Comment by jantoniucci** [comment]
+1

**Comment by patelh** [comment]
I would guess it shouldn't be too difficult.  Just need to create shaded jars for kafka 0.9.0.1 and 0.10.0.0 so both are supported.  Will work on it this month.

**Comment by hakanilter** [comment]
Do you have any updates for this issue?

**Comment by seua** [comment]
+1

**Comment by nwolff** [comment]
Newest version is 0.10.0.1 . It would be great to support that as well :)

**Comment by qfissler** [comment]
@nwolff - PR #282 includes support for 0.10.0.1 (though I've only tested on 0.10.0.0).

**Comment by nwolff** [comment]
@qfissler Just tested your fork on 0.10.0.1 and it works well. Thanks a lot.

**Comment by emclab** [comment]
Does anyway know if I can see the client producers instance(s) within a cluster and for a given topic. jmx metrics exists like kafka.server-->Produce --> byte-rate

**Comment by BDeus** [comment]
+1

**Comment by jenciso** [comment]
+1

**Comment by dezka** [comment]
+1

**Comment by heartbeat2013** [comment]
when support 0.10 +1

**Comment by JordyMoos** [comment]
Is yahoo still working on this?

**Comment by daddesio** [comment]
+1

**Comment by aries-zhang** [comment]
+1

**Comment by petermoore14** [comment]
+1

**Comment by kwankin-yau** [comment]
+1

**Comment by jan-zajic** [comment]
+1

**Comment by olegtarapata** [comment]
+1

**Comment by heipacker** [comment]
when support 0.10.2？

**Comment by schmichri** [comment]
+1

**Comment by hengheng0haha** [comment]
README.md updated 3 months ago, so close this issue.

Requirements

Kafka 0.8.1.1 or 0.8.2.* or 0.9.0.* or 0.10.0.*
Java 8+
