### ISSUE TITLE
ssl endpoints?

### ISSUE THREAD

**Issue by dmead** [yahoo/kafka-manager#245]
Hi, i'm trying to look at stats on a cluster with ssl enabled. i get this stack trace, but it's unclear how to fix it

```
kafka.common.BrokerEndPointNotAvailableException: End point PLAINTEXT not found for broker 1
        at kafka.cluster.Broker.getBrokerEndPoint(Broker.scala:141) ~[org.apache.kafka.kafka_2.11-0.9.0.1.jar:na]
        at kafka.utils.ZkUtils$$anonfun$getAllBrokerEndPointsForChannel$1.apply(ZkUtils.scala:180) ~[org.apache.kafka.kafka_2.11-0.9.0.1.jar:na]
        at kafka.utils.ZkUtils$$anonfun$getAllBrokerEndPointsForChannel$1.apply(ZkUtils.scala:180) ~[org.apache.kafka.kafka_2.11-0.9.0.1.jar:na]
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.collection.AbstractTraversable.map(Traversable.scala:104) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at kafka.utils.ZkUtils.getAllBrokerEndPointsForChannel(ZkUtils.scala:180) ~[org.apache.kafka.kafka_2.11-0.9.0.1.jar:na]

```

**Comment by dmead** [comment]
i've also got this error.

`[error] k.m.a.c.KafkaStateActor - Failed to parse broker config NonEmptyList(UnexpectedJSONError(JNull,class org.json4s.JsonAST$JString))`

**Comment by thirumalrao** [comment]
I am also getting this error

[error] k.m.a.c.KafkaStateActor - Failed to parse broker config NonEmptyList(UnexpectedJSONError(JNull,class org.json4s.JsonAST$JString))

**Comment by patelh** [comment]
I have just created a PR for adding support for secured kafka.

**Comment by patelh** [comment]
You'll see the new setting for providing a properties files for consumer properties:

kafka-manager.consumer.properties.file=${?CONSUMER_PROPERTIES_FILE}

**Comment by tbsf** [comment]
@patelh Can you give an example of this files usage?

**Comment by Ashish123gs** [comment]
Any example how to use kafka-manager.consumer.properties.file to pull offsets ?

**Comment by johnjang** [comment]
Is this still in progress? Only thing stopping us from using kafka manager is no support for ssl enabled clusters. T.T

**Comment by sshantveer** [comment]
Is this issue resolved ?

**Comment by patelh** [comment]
Yes, we are using with SSL in prod.
