### ISSUE TITLE
Runaway logging fills up disk

### ISSUE THREAD

**Issue by patricklucas** [yahoo/kafka-manager#25]
The 16GB root device of the machine I'm running this on ran out of space due to /var/log/upstart/kafka-manager.log. These logs are rotated daily, so it must have logged a lot in a short time.

The main content appears to be blocks like this:

```
[INFO] [02/14/2015 13:30:53.858] [kafka-manager-system-akka.actor.default-dispatcher-161] [akka://kafka-manager-system/user/kafka-manager/<cluster>/broker-view] Stopped actor akka://kafka-manager-system/user/kafka-manager/<cluster>/broker-view
[INFO] [02/14/2015 13:30:53.858] [kafka-manager-system-akka.actor.default-dispatcher-161] [akka://kafka-manager-system/user/kafka-manager/<cluster>/broker-view] Cancelling updater...
[INFO] [02/14/2015 13:30:53.858] [kafka-manager-system-akka.actor.default-dispatcher-161] [akka://kafka-manager-system/user/kafka-manager/<cluster>/broker-view] Started actor akka://kafka-manager-system/user/kafka-manager/<cluster>/broker-view
[INFO] [02/14/2015 13:30:53.858] [kafka-manager-system-akka.actor.default-dispatcher-161] [akka://kafka-manager-system/user/kafka-manager/<cluster>/broker-view] Scheduling updater for 10 seconds
[INFO] [02/14/2015 13:30:53.859] [kafka-manager-system-akka.actor.default-dispatcher-161] [akka://kafka-manager-system/user/kafka-manager/<cluster>/broker-view] Updating broker view...
[ERROR] [02/14/2015 13:30:53.860] [kafka-manager-system-akka.actor.default-dispatcher-160] [akka://kafka-manager-system/user/kafka-manager/<cluster>/broker-view] null
java.lang.ArithmeticException
```

Blocks like this appear every few milliseconds in the log file.

**Comment by patelh** [comment]
Can you provide the stack trace?

**Comment by patricklucas** [comment]
The only relevant messages in /var/log/kafka-manager/application.log are about connection problems to a target Kafka cluster's ZooKeeper.

```
2015-02-13 16:21:06,907 - [ERROR] - from org.apache.curator.ConnectionState in CuratorFramework-0
Connection timed out for connection string (10.1.2.3:2181/kafka) and timeout (15000) / elapsed (26629)
org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
        at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:197) [org.apache.curator.curator-client-2.7.0.jar:na]
        at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:87) [org.apache.curator.curator-client-2.7.0.jar:na]
        at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:115) [org.apache.curator.curator-client-2.7.0.jar:na]
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:816) [org.apache.curator.curator-framework-2.7.0.jar:na]
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:802) [org.apache.curator.curator-framework-2.7.0.jar:na]
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$400(CuratorFrameworkImpl.java:61) [org.apache.curator.curator-framework-2.7.0.jar:na]
        at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:272) [org.apache.curator.curator-framework-2.7.0.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_20]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_20]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_20]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
```

**Comment by patelh** [comment]
Is this still an issue?  Can we close?

**Comment by patricklucas** [comment]
Well, I actually just let it run with a totally full disk for the last few months. I'll kill it and upgrade to latest and see if it still happens.

**Comment by patelh** [comment]
Hi Patrick, please let us know if this is still a problem.  Thanks!

**Comment by patricklucas** [comment]
It hasn't happened again since my report. I'll close this and reopen if I have any more issues.
