### ISSUE TITLE
Startup fails because of Logger timeout on a busy machine

### ISSUE THREAD

**Issue by splix** [yahoo/kafka-manager#256]
I'm using Kafka Manager inside a small Docker cluster used for development and testing. During startup the docker spins a lot of vms in parallel, including few Kafkas, Zookeepers and others, besides Kafka Manager. The thing that it's a slow process and Kafka Manager usually fail to start because it was unable to start logger in 5000ms:

````
kafka-manager_1 | [WARN] [06/22/2016 15:13:58.525] [main] [EventStream(akka://kafka-manager-system)] Logger log1-Slf4jLogger did not respond within Timeout(5000 milliseconds) to InitializeLogger(bus)
kafka-manager_1 | error while starting up loggers
kafka-manager_1 | akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [akka.event.Logging$LoggerInitializationException: Logger log1-Slf4jLogger did not respond with LoggerInitialized, sent instead [TIMEOUT]]
kafka-manager_1 | 	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:116)
kafka-manager_1 | 	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:115)
kafka-manager_1 | 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
kafka-manager_1 | 	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
kafka-manager_1 | 	at scala.util.Try$.apply(Try.scala:192)
kafka-manager_1 | 	at scala.util.Failure.recover(Try.scala:216)
kafka-manager_1 | 	at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:115)
kafka-manager_1 | 	at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:110)
kafka-manager_1 | Oops, cannot start the server.
````

I'm able to start it after few tries, but it still annoying. Especially because of the fact that it fails just because of some Logger configuration. 

And I don't see any configuration for Slf4jLogger timeout. I don't think there should be such conf option, actually. Maybe it's better to set it to 10000ms by default?

**Comment by frankgu** [comment]
According to [link](https://stackoverflow.com/questions/27910526/logger-log1-slf4jlogger-did-not-respond-within-timeout5000-milliseconds-to-ini), I have change the configuration file in `kafka-manager-1.3.3.6/target/universal/kafka-manager-1.3.3.6/conf/application.conf` from
```
akka {
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel = "INFO"
}
```
to
```
akka {
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel = "INFO"
  logger-startup-timeout = 30s
}
```
and run the manager with this configuration file which could solve this problem .

**Comment by BrainMonkey** [comment]
Adjusting the timeout for me worked. Thank you very much
