### ISSUE TITLE
NoClassDefFoundError: kafka/manager/utils/TopicConfigs$

### ISSUE THREAD

**Issue by cattywampus** [yahoo/kafka-manager#258]
I'm having trouble getting kafka-manager up and running on my system. I've built the application using the instructions provided in the README however when I start the service I am unable to access the application on the specified port. Digging into the logs reveals only the following error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: kafka/manager/utils/TopicConfigs$
        at controllers.Topic.<init>(Topic.scala:48)
        at loader.ApplicationComponents.topicC$lzycompute(KafkaManagerLoader.scala:35)
        at loader.ApplicationComponents.topicC(KafkaManagerLoader.scala:35)
        at loader.ApplicationComponents.<init>(KafkaManagerLoader.scala:52)
        at loader.KafkaManagerLoader.load(KafkaManagerLoader.scala:25)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:52)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: java.lang.ClassNotFoundException: kafka.manager.utils.TopicConfigs$
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 8 more
```

I'm running on RedHat Enterprise 6.8 with Oracle Java 1.8.0_65. Here are the steps I followed to get it running:

```
git clone https://github.com/yahoo/kafka-manager.git
cd kafka-manager
git checkout 1.3.0.8.1
./sbt clean dist
./sbt rpm:packageBuild
sudo rpm -ivh target/rpm/RPMS/noarch/kafka-manager-1.3.0.8-1.noarch.rpm
# now I update /etc/kafka-manager/application.conf & /etc/default/kafka-manager
sudo service kafka-manager start
```

The source code for the missing class is under `app/kafka/manager/utils/TopicConfigs.scala` however I can't seem to find the contents of that `app` directory. From what I can tell, kafka-manager was installed to /usr/share/kafka-manager however I don't see an `app` folder in there and I can't find the contents of the `app` directory in any of the jars in the `lib` directory. 

Are there steps that I'm missing during the build/installation process? Any help on this would be greatly appreciated.

**Comment by patelh** [comment]
Please try latest version.
