### ISSUE TITLE
start failed while previous start fails by port binding error.

### ISSUE THREAD

**Issue by jongsuny** [yahoo/kafka-manager#269]
1. first start failed by port binding fail
[log]
play.api.Play - Application started (Prod)
Oops, cannot start the server.
org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:20099
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
	at play.core.server.NettyServer$$anonfun$1.apply(NettyServer.scala:132)
	at play.core.server.NettyServer$$anonfun$1.apply(NettyServer.scala:129)
	at scala.Option.map(Option.scala:146)
	at play.core.server.NettyServer.<init>(NettyServer.scala:129)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:200)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:199)
	at play.core.server.ServerProvider$class.createServer(ServerProvider.scala:24)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:199)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:58)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2. and next start fails leaving below message.
This application is already running (Or delete ${user.home}/apps/kafka-manager-1.3.0.8/RUNNING_PID file).

Should this be an issue? After delete RUNNING_PID file,works fine.

**Comment by PiotrBB** [comment]
Got the exact same error. Haven't found the solution yet. Not sure why it's trying to bind to 0.0.0.0
