### ISSUE TITLE
Are you kafka-manager shell is ok?

### ISSUE THREAD

**Issue by FunkyYang** [yahoo/kafka-manager#293]
I  get a problem when I install kafka-manager in mine,the kafaka-manager shell couldn't find the JAVA_HOME,but i saw it's right when I used kafka-manager -h verbose,this is my infomation at blow

`hadoop@datanode06:/usr/kafka-manager-1.3.1.8/bin$ ./kafka-manager -h
Usage:  [options]

  -h | -help         print this message
  -v | -verbose      this runner is chattier
  -d | -debug        set sbt log level to debug
  -no-version-check  Don't run the java version check.
  -main <classname>  Define a custom main class
  -jvm-debug <port>  Turn on JVM debugging, open at the given port.

  # java version (default: java from PATH, currently java version "1.8.0_60")
  -java-home <path>         alternate JAVA_HOME

  # jvm options and output control
  JAVA_OPTS          environment variable, if unset uses ""
  -Dkey=val          pass -Dkey=val directly to the java runtime
  -J-X               pass option -X directly to the java runtime
                     (-J is stripped)

  # special option
  --                 To stop parsing built-in commands from the rest of the command-line.
                     e.g.) enabling debug and sending -d as app argument
                     $ ./start-script -d -- -d

In the case of duplicated or conflicting options, basically the order above
shows precedence: JAVA_OPTS lowest, command line options highest except "--".
hadoop@datanode06:/usr/kafka-manager-1.3.1.8/bin$ ./kafka-manager -Dconfig.file=../conf/application.conf
Oops, cannot start the server.
java.io.FileNotFoundException: /usr/kafka-manager-1.3.1.8/RUNNING_PID (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at play.core.server.ProdServerStart$.createPidFile(ProdServerStart.scala:131)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:45)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
hadoop@datanode06:/usr/kafka-manager-1.3.1.8/bin$ sudo ./kafka-manager -Dconfig.file=../conf/application.conf

No java installations was detected.
Please go to http://www.java.com/getjava/ and download

hadoop@datanode06:/usr/kafka-manager-1.3.1.8/bin$ 
`
is there any wrong with the kafka-manager shell?

**Comment by FunkyYang** [comment]
I used ./kafka-manager -Dconfig.file=../config/application.conf -java-home $JAVA_HOME is working,but Why it's woring when I don't append -java-home options
