### ISSUE TITLE
NullPointerException processing message from offset topic

### ISSUE THREAD

**Issue by ernestojpg** [yahoo/kafka-manager#296]
Hi,

In certain cases I'm getting this NullPointerException from Kafka Manager:

```
[warn] k.m.a.c.KafkaManagedOffsetCache - Failed to process a message from offset topic!
java.lang.NullPointerException: null
       	at java.nio.ByteBuffer.wrap(ByteBuffer.java:396) ~[na:1.8.0_91]
       	at kafka.manager.actor.cluster.KafkaManagedOffsetCache$$anonfun$run$3.apply(KafkaStateActor.scala:285) [kafka-manager.kafka-manager-1.3.1.8-sans-externalized.jar:na]
       	at kafka.manager.actor.cluster.KafkaManagedOffsetCache$$anonfun$run$3.apply(KafkaStateActor.scala:235) [kafka-manager.kafka-manager-1.3.1.8-sans-externalized.jar:na]
       	at scala.util.Success.foreach(Try.scala:236) [org.scala-lang.scala-library-2.11.8.jar:na]
       	at kafka.manager.actor.cluster.KafkaManagedOffsetCache.run(KafkaStateActor.scala:235) [kafka-manager.kafka-manager-1.3.1.8-sans-externalized.jar:na]
       	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
```

Kafka Manager version: 1.3.1.8
Kafka Version: 2.11-0.10.0.1
Zookeeper version: 3.4.6

**Comment by DavidLiuXh** [comment]
I changed this "run" function at 225 line in the KafkaStateActor.scala file:
`                case GroupMetadataKey(version, key) =>
                      if (null != messageAndMetadata &&
                        null != messageAndMetadata.message()) {
                          val value: GroupMetadata = readGroupMessageValue(key, ByteBuffer.wrap(messageAndMetadata.message()))
                          value.allMemberMetadata.foreach {
                            mm =>
                              mm.assignment.foreach {
                                case (topic, part) =>
                                  groupTopicPartitionMemberMap += (key, topic, part) -> mm
                              }
                          }
                        } else {
                          groupTopicPartitionMemberMap.foreach {
                            case ((group, topic, part), mmd) =>
                              if (group == key) {
                                var tmp = mmd
                                tmp.memberId = ""
                                tmp.clientHost = ""
                                groupTopicPartitionMemberMap += (key, topic, part) -> tmp 
                              }
                          }
                        }
              }
`

**Comment by DavidLiuXh** [comment]
I changed this "run" function at 225 line in the KafkaStateActor.scala file:
case GroupMetadataKey(version, key) =>
                      if (null != messageAndMetadata &&
                        null != messageAndMetadata.message()) {
                          val value: GroupMetadata = readGroupMessageValue(key, ByteBuffer.wrap(messageAndMetadata.message()))
                          value.allMemberMetadata.foreach {
                            mm =>
                              mm.assignment.foreach {
                                case (topic, part) =>
                                  groupTopicPartitionMemberMap += (key, topic, part) -> mm
                              }
                          }
                        } else {
                          groupTopicPartitionMemberMap.foreach {
                            case ((group, topic, part), mmd) =>
                              if (group == key) {
                                var tmp = mmd
                                tmp.memberId = ""
                                tmp.clientHost = ""
                                groupTopicPartitionMemberMap += (key, topic, part) -> tmp 
                              }
                          }
                        }
`
`

**Comment by Ashish123gs** [comment]
I am having the same problem .

Any workaround ?

**Comment by Ashish123gs** [comment]
Can the above change be merged please ?
