### ISSUE TITLE
Unable to start kafka-manager

### ISSUE THREAD

**Issue by tutunci** [yahoo/kafka-manager#298]
Hi,
after building package I've unzipped the generated file, setup into application.conf the list of Zookeeper nodes and than started but this error happen.
Can you please help me on fixing

```
[root@server08 kafka-manager-1.3.1.6]# bin/kafka-manager -Dconfig.file=/usr/local/kafka_manager/kafka-manager-1.3.1.6/config/application.conf -Dhttp.port=8287
03:56:15,676 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
03:56:15,677 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
03:56:15,677 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/usr/local/kafka_manager/kafka-manager-1.3.1.6/conf/logback.xml]
03:56:15,768 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
03:56:15,769 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word coloredLevel with class [play.api.Logger$ColoredLevel]
03:56:15,769 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
03:56:15,774 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
03:56:15,797 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
03:56:15,841 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@18:27 - no applicable action for [totalSizeCap], current ElementPath  is [[configuration][appender][rollingPolicy][totalSizeCap]]
03:56:15,845 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
03:56:15,846 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern application.home_IS_UNDEFINED/logs/application.%d{yyyy-MM-dd}.log for the active file
03:56:15,849 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern 'application.home_IS_UNDEFINED/logs/application.%d{yyyy-MM-dd}.log'.
03:56:15,849 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
03:56:15,852 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Thu Sep 15 03:51:15 EDT 2016
03:56:15,854 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: application.home_IS_UNDEFINED/logs/application.log
03:56:15,854 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [application.home_IS_UNDEFINED/logs/application.log]
03:56:15,855 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
03:56:15,856 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
03:56:15,857 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
03:56:15,858 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
03:56:15,860 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ASYNCFILE]
03:56:15,860 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to ch.qos.logback.classic.AsyncAppender[ASYNCFILE]
03:56:15,860 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNCFILE] - Attaching appender named [FILE] to AsyncAppender.
03:56:15,860 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNCFILE] - Setting discardingThreshold to 51
03:56:15,860 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
03:56:15,861 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ASYNCSTDOUT]
03:56:15,861 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to ch.qos.logback.classic.AsyncAppender[ASYNCSTDOUT]
03:56:15,861 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNCSTDOUT] - Attaching appender named [STDOUT] to AsyncAppender.
03:56:15,861 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNCSTDOUT] - Setting discardingThreshold to 51
03:56:15,861 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [play] to INFO
03:56:15,861 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [application] to INFO
03:56:15,861 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [kafka.manager] to INFO
03:56:15,861 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.avaje.ebean.config.PropertyMapLoader] to OFF
03:56:15,861 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.avaje.ebeaninternal.server.core.XmlConfigLoader] to OFF
03:56:15,861 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.avaje.ebeaninternal.server.lib.BackgroundThread] to OFF
03:56:15,861 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.gargoylesoftware.htmlunit.javascript] to OFF
03:56:15,861 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.zookeeper] to INFO
03:56:15,862 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
03:56:15,862 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNCFILE] to Logger[ROOT]
03:56:15,862 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNCSTDOUT] to Logger[ROOT]
03:56:15,862 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
03:56:15,862 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@c86b9e3 - Registering current configuration as safe fallback point

03:56:15,676 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
03:56:15,677 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
03:56:15,677 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/usr/local/kafka_manager/kafka-manager-1.3.1.6/conf/logback.xml]
03:56:15,768 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
03:56:15,769 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word coloredLevel with class [play.api.Logger$ColoredLevel]
03:56:15,769 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
03:56:15,774 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
03:56:15,797 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
03:56:15,841 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@18:27 - no applicable action for [totalSizeCap], current ElementPath  is [[configuration][appender][rollingPolicy][totalSizeCap]]
03:56:15,845 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
03:56:15,846 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern application.home_IS_UNDEFINED/logs/application.%d{yyyy-MM-dd}.log for the active file
03:56:15,849 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern 'application.home_IS_UNDEFINED/logs/application.%d{yyyy-MM-dd}.log'.
03:56:15,849 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
03:56:15,852 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Thu Sep 15 03:51:15 EDT 2016
03:56:15,854 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: application.home_IS_UNDEFINED/logs/application.log
03:56:15,854 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [application.home_IS_UNDEFINED/logs/application.log]
03:56:15,855 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
03:56:15,856 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
03:56:15,857 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
03:56:15,858 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
03:56:15,860 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ASYNCFILE]
03:56:15,860 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to ch.qos.logback.classic.AsyncAppender[ASYNCFILE]
03:56:15,860 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNCFILE] - Attaching appender named [FILE] to AsyncAppender.
03:56:15,860 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNCFILE] - Setting discardingThreshold to 51
03:56:15,860 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
03:56:15,861 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ASYNCSTDOUT]
03:56:15,861 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to ch.qos.logback.classic.AsyncAppender[ASYNCSTDOUT]
03:56:15,861 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNCSTDOUT] - Attaching appender named [STDOUT] to AsyncAppender.
03:56:15,861 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNCSTDOUT] - Setting discardingThreshold to 51
03:56:15,861 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [play] to INFO
03:56:15,861 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [application] to INFO
03:56:15,861 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [kafka.manager] to INFO
03:56:15,861 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.avaje.ebean.config.PropertyMapLoader] to OFF
03:56:15,861 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.avaje.ebeaninternal.server.core.XmlConfigLoader] to OFF
03:56:15,861 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.avaje.ebeaninternal.server.lib.BackgroundThread] to OFF
03:56:15,861 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.gargoylesoftware.htmlunit.javascript] to OFF
03:56:15,861 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.zookeeper] to INFO
03:56:15,862 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
03:56:15,862 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNCFILE] to Logger[ROOT]
03:56:15,862 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNCSTDOUT] to Logger[ROOT]
03:56:15,862 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
03:56:15,862 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@c86b9e3 - Registering current configuration as safe fallback point
03:56:15,881 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNCFILE] - Worker thread will flush remaining events before exiting. 
03:56:15,881 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNCFILE] - Queue flush finished successfully within timeout.
03:56:15,881 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNCSTDOUT] - Worker thread will flush remaining events before exiting. 
03:56:15,881 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNCSTDOUT] - Queue flush finished successfully within timeout.
03:56:15,884 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
03:56:15,884 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word coloredLevel with class [play.api.Logger$ColoredLevel]
03:56:15,884 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
03:56:15,884 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
03:56:15,885 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
03:56:15,886 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@14:21 - no applicable action for [totalSizeCap], current ElementPath  is [[configuration][appender][rollingPolicy][totalSizeCap]]
03:56:15,888 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
03:56:15,888 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern /usr/local/kafka_manager/kafka-manager-1.3.1.6/logs/application.%d{yyyy-MM-dd}.log for the active file
03:56:15,889 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/usr/local/kafka_manager/kafka-manager-1.3.1.6/logs/application.%d{yyyy-MM-dd}.log'.
03:56:15,889 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
03:56:15,889 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Thu Sep 15 03:51:16 EDT 2016
03:56:15,889 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: /usr/local/kafka_manager/kafka-manager-1.3.1.6/logs/application.log
03:56:15,889 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [/usr/local/kafka_manager/kafka-manager-1.3.1.6/logs/application.log]
03:56:15,890 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [play] to INFO
03:56:15,890 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [application] to DEBUG
03:56:15,890 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.avaje.ebean.config.PropertyMapLoader] to OFF
03:56:15,890 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.avaje.ebeaninternal.server.core.XmlConfigLoader] to OFF
03:56:15,890 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.avaje.ebeaninternal.server.lib.BackgroundThread] to OFF
03:56:15,890 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.gargoylesoftware.htmlunit.javascript] to OFF
03:56:15,890 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.zookeeper] to INFO
03:56:15,890 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [akka] to INFO
03:56:15,890 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [kafka] to INFO
03:56:15,890 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
03:56:15,890 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
03:56:15,890 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
03:56:15,890 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@76f2bbc1 - Registering current configuration as safe fallback point

Oops, cannot start the server.
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Could not find a suitable constructor in controllers.Application. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at controllers.Application.class(Application.scala:16)
  while locating controllers.Application
    for parameter 1 at router.Routes.<init>(Routes.scala:63)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

2) Could not find a suitable constructor in controllers.Cluster. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at controllers.Cluster.class(Cluster.scala:28)
  while locating controllers.Cluster
    for parameter 2 at router.Routes.<init>(Routes.scala:63)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

3) Could not find a suitable constructor in controllers.Consumer. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at controllers.Consumer.class(Consumer.scala:16)
  while locating controllers.Consumer
    for parameter 5 at router.Routes.<init>(Routes.scala:63)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

4) Could not find a suitable constructor in controllers.Logkafka. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at controllers.Logkafka.class(Logkafka.scala:33)
  while locating controllers.Logkafka
    for parameter 4 at router.Routes.<init>(Routes.scala:63)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

5) Could not find a suitable constructor in controllers.PreferredReplicaElection. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at controllers.PreferredReplicaElection.class(PreferredReplicaElection.scala:26)
  while locating controllers.PreferredReplicaElection
    for parameter 6 at router.Routes.<init>(Routes.scala:63)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

6) Could not find a suitable constructor in controllers.ReassignPartitions. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at controllers.ReassignPartitions.class(ReassignPartitions.scala:28)
  while locating controllers.ReassignPartitions
    for parameter 7 at router.Routes.<init>(Routes.scala:63)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

7) Could not find a suitable constructor in controllers.Topic. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at controllers.Topic.class(Topic.scala:34)
  while locating controllers.Topic
    for parameter 3 at router.Routes.<init>(Routes.scala:63)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

8) Could not find a suitable constructor in controllers.api.KafkaStateCheck. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at controllers.api.KafkaStateCheck.class(KafkaStateCheck.scala:19)
  while locating controllers.api.KafkaStateCheck
    for parameter 8 at router.Routes.<init>(Routes.scala:63)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

8 errors
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
        at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:321)
        at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:316)
        at play.api.Application$class.routes(Application.scala:112)
        at play.api.DefaultApplication.routes(Application.scala:241)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:90)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:87)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:87)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:87)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:54)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:27)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```

Thanks
Maurizio

**Comment by tpurcell** [comment]
Same issue. Other than timestamps I get exactly the same output as the log entered by Maurizio.

**Comment by tpurcell** [comment]
Okay, I solved my problem.  The readme says to start the application as follows:

`bin/kafka-manager -Dconfig.file=/path/to/application.conf -Dhttp.port=8080`

I did that with an application.conf file that only specified the kafka-manager.zkhosts property. I thought that was the only thing I needed to change and that I'd take the defaults for the rest.

That did not work. I got the error messages indicated above. 

I fixed it by updating the default config file (conf/application.conf) with my kafka-manager.zkhosts values. and then starting the application this way:

`bin/kafka-manager `

The application started and all the "Could not find a suitable constructor" messages went away. 

But there was still a problem. My logs wound up in a directory called "application.home_IS_UNDEFINED". 

I tried adding a "application.home" property to the application.conf file but that did not work.

So I tried starting the server this way:
`bin/kafka-manager -Dapplication.home=.`

That worked. The server started and the logs directory got created in the application's root directory.

**Comment by MannuRawat** [comment]
after bin\kafka-manager
i'm getting
The system cannot find the file C:\Users\USER1\Desktop\kafka-manager-1.3.0.7\bin\\\..\KAFKA_MANAGER_config.txt.

**Comment by abhit011** [comment]
I am also getting the exact error like system can \KAFKA_MANAGER_config.txt does not exist

**Comment by lanmo** [comment]
Same issue

**Comment by Chillmatik** [comment]
Same issue

**Comment by fflatorre** [comment]
Same issue

**Comment by saikiran-beeravelly** [comment]
any solution for this issue ?
