### ISSUE TITLE
Exception in Kafka (0.8.2.1)- Client version mismatch with broker

### ISSUE THREAD

**Issue by dandujaipalreddy** [yahoo/kafka-manager#329]
Hello,

We are getting the following exception while using kafka-manager(1.3.6) with Kafka 0.8.2.1
```
ERROR Closing socket for /XX.XX.XX.XX because of error (kafka.network.Processor)
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'topics': java.nio.BufferUnderflowException
        at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:66)
        at org.apache.kafka.common.requests.JoinGroupRequest.parse(JoinGroupRequest.java:85)
        at kafka.api.JoinGroupRequestAndHeader$.readFrom(JoinGroupRequestAndHeader.scala:29)
        at kafka.api.RequestKeys$$anonfun$12.apply(RequestKeys.scala:50)
        at kafka.api.RequestKeys$$anonfun$12.apply(RequestKeys.scala:50)
        at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
        at kafka.network.Processor.read(SocketServer.scala:450)
        at kafka.network.Processor.run(SocketServer.scala:340)
        at java.lang.Thread.run(Thread.java:74
```
By looking at the exception,We can infer that there is version mismatch between kafka-manager and broker.
So,How to fix this issue? Is there any parameter in kafka-manager to specify this?
In UI, I gave the version similar to broker still I am getting this.

**Comment by thunderstumpges** [comment]
Just wanted to bump this and add a +1. We upgraded to 1.3.6 recently and are getting this same error message in log. It is fierce (tight loop) many per second. Any ideas on a solution? Should we downgrade? Upgrade?

**Comment by myusuf3** [comment]
same here – to my understanding the client they are using internally isn't compatible anymore with 0.8.X.X.

Is this true or have you guys found a fix @thunderstumpges @dandujaipalreddy

**Comment by Baozhb** [comment]
kafka_2.10-0.8.2.0, kafka-manager-1.3.3.0, same Exception.  But kafka_2.11-0.8.2.0 with no problem. I think it is a problem of scala version dismatch. But how to change the scalaVersion. Or other solution ?

**Comment by padilo** [comment]
I'm having this same problem using 2.10-0.8.2.2

**Comment by padilo** [comment]
The strange think is that we have a preproduction environment that is exactly the same as our production environment.
The preproduction environemnt works fine, but the production is throwing the ERROR over and over.

Do you have any clue why this is happening?

**Comment by M2shad0w** [comment]
i'm having the same eroor, but seems just error on some machines of cluster.

**Comment by M2shad0w** [comment]
when i lanuch the kafka manager, get this warn 

```
[warn] k.m.a.c.KafkaManagedOffsetCache - Failed to process a message from offset topic on cluster pro-kafka!
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'brokers': Error reading field 'host': Error reading string of length 29548, only 1656 bytes available
        at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:73) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na]

```

**Comment by M2shad0w** [comment]
@padilo @Baozhb 
downgrade to this version
https://github.com/M2shad0w/kafka-manager/releases/tag/support-kafka-0.8.2.x
