### ISSUE TITLE
some consumer groups not shown in Consumer section

### ISSUE THREAD

**Issue by donalduk** [yahoo/kafka-manager#358]
I am using latest kafka manager 1.3.3.1 and the version of kafka cluster is 2.11_0.9.0.1. I have written one test KafkaConsumer based 0.9.0.1 client library to consume message. And I can consume the message sucesssfully, but the consumer group I am using is not shown in Consumer section. 

Could anyone advise me what causes the problem?

**Comment by sjp00556** [comment]
I met the same problem as you,use kafka-manager-V1.3.1.8 can solve this problem,it works for kafka2.11_0.9.0.1.

I found that kafka-manager-1.3.3.1 use  org.apache.kafka.0.10.0.1.jar sdk  to get the kafka offset msg,but it incompatible with kafka0.9.0.1  V1.3.1.8 use org.apache.kafka.0.9.0.1.jar sdk,so it works

**Comment by lonely7345** [comment]
i have the  same problem

**Comment by maxenced** [comment]
Hello here, I think I also have the same pb. I have 4 identical hosts with 4 instances of kafka-manager. Kafka-manager is in version 1.3.0.8. I also have tested last version 1.3.3.6.

What I can't explain is that only one of the 4 instances (a 1.3.0.8 one) works correctly. A request to  : 
```
0:9000/clusters/MyCluster/consumers/myconsumergroup/topic/mytopic/type/KF
```

correctly shows my 4 customers with their respective partition, offsets and "consumer instance owner".

On the 3 others, no matter the version, I don't see the consumergroup in the list, and if I access the above url directly, I get my 4 entries with : 

 * correct partition
 * correct logsize
 * consumer offset set to -1
 * empty lag
 * empty consumer instance owner

Hope it helps.

Maxence

**Comment by dwo** [comment]
I don't think there's a way to get the 0.10 client working against older brokers. I'm not sure what the options are here: go back 0.9 client, or use different client versions based on what cluster is being consumed from?

We got this stack trace trying to consume offsets from a 0.9 cluster with the 0.10 client in kafka-manager.
```
k.m.a.c.KafkaManagedOffsetCache - Failed to process a message from offset topic on cluster! org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'brokers': Error reading field 'host': Error reading string of length 25955, only 3540 bytes available at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:73) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na] at org.apache.kafka.clients.NetworkClient.parseResponse(NetworkClient.java:380) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na] at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:449) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na] at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:269) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na] at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.clientPoll(ConsumerNetworkClient.java:360) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na] at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na] at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:192) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na] at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:163) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na] at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:179) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na] at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:974) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na]
```

**Comment by longtian** [comment]
Same problem as @dwo met

- kafka: 0.9.0.1
- kafka-manager: 1.3.3.6

```
manager2_1          | [warn] k.m.a.c.KafkaManagedOffsetCache - Failed to process a message from offset topic on cluster production!
manager2_1          | org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'brokers': Error reading field 'host': Error reading string of length 12592, only 2166 bytes available
manager2_1          | 	at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:73) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na]
manager2_1          | 	at org.apache.kafka.clients.NetworkClient.parseResponse(NetworkClient.java:380) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na]
manager2_1          | 	at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:449) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na]
manager2_1          | 	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:269) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na]
manager2_1          | 	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.clientPoll(ConsumerNetworkClient.java:360) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na]
manager2_1          | 	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na]
manager2_1          | 	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:192) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na]
manager2_1          | 	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:163) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na]
manager2_1          | 	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:179) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na]
manager2_1          | 	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:974) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na]
```

**Comment by george-jin** [comment]
we are using 
    kafka 0.10.2.0 
    kafka-manager 1.3.3.6
and facing the same issue here

Any idea if this issue is resolved in any newer releases? 
Thanks!
