### ISSUE TITLE
JMX enpoint connection issue

### ISSUE THREAD

**Issue by arun-a-nayagam** [yahoo/kafka-manager#364]
Hi,

Kafka version : kafka_2.11-0.10.2.0
Kafka Manager : kafka-manager-1.3.3.4

I have enabled JMX on the brokers. netstat on the broker does list port 9997 (JMX Port)
`tcp        0      0 0.0.0.0:9997                0.0.0.0:*                   LISTEN      23479/java `

Kafka manager is able to connect to the brokers and list topics and consumers fine. 
But it keeps throwing this connection refused error on the JMX port and so is not able to give the metrics.
```
[error] k.m.j.KafkaJMX$ - Failed to connect to service:jmx:rmi:///jndi/rmi://kafka002.sys.net:9997/jmxrmi
java.rmi.ConnectException: Connection refused to host: kafka002.sys.net; nested exception is: 
	java.net.ConnectException: Operation timed out (Connection timed out)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619) ~[na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216) ~[na:1.8.0_121]
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202) ~[na:1.8.0_121]
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:130) ~[na:1.8.0_121]
	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:227) ~[na:1.8.0_121]
	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:179) ~[na:1.8.0_121]
	at com.sun.proxy.$Proxy6.newClient(Unknown Source) ~[na:na]
	at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2430) ~[na:1.8.0_121]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:308) ~[na:1.8.0_121]
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[na:1.8.0_121]
Caused by: java.net.ConnectException: Operation timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_121]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_121]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_121]
	at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_121]
	at java.net.Socket.<init>(Socket.java:434) ~[na:1.8.0_121]
	at java.net.Socket.<init>(Socket.java:211) ~[na:1.8.0_121]
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40) ~[na:1.8.0_121]
```

I am even able telnet to the server on the JMX port from the kafka-manager host machine.
```
arun$ telnet kafka002.sys.net 9997
Trying 16.45.45.454...
Connected to kafka002.sys.net.
Escape character is '^]'.
```

Any help is much appreciated.

Thanks,
Arun

**Comment by arun-a-nayagam** [comment]
Found the issue, apart from 9997 I believe there are other internal ports that JMX requires. 
I installed kafka-manager on the same subnet and it got access to the other ports and its working now.

Thanks,
Arun

**Comment by ondrejchmelar** [comment]
Can someone specify which ports exactly are needed? Netstat shows a wide range being used (32000-50000).
I find it very disappointing that besides settable ports (brokers, zookeeper, jmx_port), non-configurable ones are used and it is not mentioned in the docs.
