### ISSUE TITLE
Kafka-manager does not do zookeeper re-connect

### ISSUE THREAD

**Issue by sanjeevtripurari** [yahoo/kafka-manager#366]
If Zookeeper is broken from kafka-manager, it does not retry, and connection is broken forever

Do we have retry options, after few mins?

> 2017-03-03 04:12:54,057 - [ERROR] - from org.apache.curator.ConnectionState in Curator-Framework-0
> Connection timed out for connection string (zookeeper01.my.home.net:2181,zookeeper02.my.home.net:2181,zookeeper03.my.home.net:2181/kafka) and timeout (15000) / elapsed (15021)
> org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
>         at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:197) [org.apache.curator.curator-client-2.10.0.jar:na]
>         at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:88) [org.apache.curator.curator-client-2.10.0.jar:na]
>         at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:116) [org.apache.curator.curator-client-2.10.0.jar:na]
>         at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:835) [org.apache.curator.curator-framework-2.10.0.jar:na]
>         at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:809) [org.apache.curator.curator-framework-2.10.0.jar:na]
>         at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:64) [org.apache.curator.curator-framework-2.10.0.jar:na]
>         at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:267) [org.apache.curator.curator-framework-2.10.0.jar:na]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_05]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_05]
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_05]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_05]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_05]
>         at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
>

**Comment by sundhaug92** [comment]
Looks like a dupe of #16, which also links to #11
