### ISSUE TITLE
upgrade to scalaVersion 2.12.1

### ISSUE THREAD

**Issue by sreev** [yahoo/kafka-manager#382]
modify build.sbt and add **scalaVersion := "2.12.1"**, build fails with the following console output.

documenting for the purpose that, this can used as a trigger for upgrade and reference when upgrading.

`
$ sbt clean dist
[info] Loading global plugins from ~/.sbt/0.13/plugins
[info] Loading project definition from ~/kafka-manager/project
[info] Set current project to kafka-manager (in build file:~/kafka-manager/)
[success] Total time: 0 s, completed Apr 17, 2017 7:31:41 PM
[info] Updating {file:~/kafka-manager/}root...
[info] Packaging ~/kafka-manager/target/scala-2.12/kafka-manager_2.12-1.3.3.5-sources.jar ...
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:~/.ivy2/cache/org.slf4j/slf4j-nop/jars/slf4j-nop-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:~/.ivy2/cache/org.slf4j/slf4j-simple/jars/slf4j-simple-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.helpers.NOPLoggerFactory]
[info] Wrote ~/kafka-manager/target/scala-2.12/kafka-manager_2.12-1.3.3.5.pom
[info] Done packaging.
[info] Resolving com.typesafe.play#twirl-api_2.12;1.1.1 ...
[warn] 	module not found: com.typesafe.play#twirl-api_2.12;1.1.1
[warn] ==== local: tried
[warn]   ~/.ivy2/local/com.typesafe.play/twirl-api_2.12/1.1.1/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   ~/.sbt/preloaded/com.typesafe.play/twirl-api_2.12/1.1.1/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:///~/.sbt/preloaded/com/typesafe/play/twirl-api_2.12/1.1.1/twirl-api_2.12-1.1.1.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/play/twirl-api_2.12/1.1.1/twirl-api_2.12-1.1.1.pom
[info] Resolving com.typesafe.play#play-server_2.12;2.4.6 ...
[warn] 	module not found: com.typesafe.play#play-server_2.12;2.4.6
[warn] ==== local: tried
[warn]   ~/.ivy2/local/com.typesafe.play/play-server_2.12/2.4.6/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   ~/.sbt/preloaded/com.typesafe.play/play-server_2.12/2.4.6/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:///~/.sbt/preloaded/com/typesafe/play/play-server_2.12/2.4.6/play-server_2.12-2.4.6.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/play/play-server_2.12/2.4.6/play-server_2.12-2.4.6.pom
[info] Resolving com.typesafe.play#play-netty-server_2.12;2.4.6 ...
[warn] 	module not found: com.typesafe.play#play-netty-server_2.12;2.4.6
[warn] ==== local: tried
[warn]   ~/.ivy2/local/com.typesafe.play/play-netty-server_2.12/2.4.6/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   ~/.sbt/preloaded/com.typesafe.play/play-netty-server_2.12/2.4.6/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:///~/.sbt/preloaded/com/typesafe/play/play-netty-server_2.12/2.4.6/play-netty-server_2.12-2.4.6.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/play/play-netty-server_2.12/2.4.6/play-netty-server_2.12-2.4.6.pom
[info] Resolving com.typesafe.akka#akka-actor_2.12;2.3.14 ...
[warn] 	module not found: com.typesafe.akka#akka-actor_2.12;2.3.14
[warn] ==== local: tried
[warn]   ~/.ivy2/local/com.typesafe.akka/akka-actor_2.12/2.3.14/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   ~/.sbt/preloaded/com.typesafe.akka/akka-actor_2.12/2.3.14/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:///~/.sbt/preloaded/com/typesafe/akka/akka-actor_2.12/2.3.14/akka-actor_2.12-2.3.14.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.3.14/akka-actor_2.12-2.3.14.pom
[info] Resolving com.typesafe.akka#akka-slf4j_2.12;2.3.14 ...
[warn] 	module not found: com.typesafe.akka#akka-slf4j_2.12;2.3.14
[warn] ==== local: tried
[warn]   ~/.ivy2/local/com.typesafe.akka/akka-slf4j_2.12/2.3.14/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   ~/.sbt/preloaded/com.typesafe.akka/akka-slf4j_2.12/2.3.14/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:///~/.sbt/preloaded/com/typesafe/akka/akka-slf4j_2.12/2.3.14/akka-slf4j_2.12-2.3.14.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/akka/akka-slf4j_2.12/2.3.14/akka-slf4j_2.12-2.3.14.pom
[info] Resolving org.webjars#webjars-play_2.12;2.4.0-2 ...
[warn] 	module not found: org.webjars#webjars-play_2.12;2.4.0-2
[warn] ==== local: tried
[warn]   ~/.ivy2/local/org.webjars/webjars-play_2.12/2.4.0-2/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   ~/.sbt/preloaded/org.webjars/webjars-play_2.12/2.4.0-2/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:///~/.sbt/preloaded/org/webjars/webjars-play_2.12/2.4.0-2/webjars-play_2.12-2.4.0-2.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/webjars/webjars-play_2.12/2.4.0-2/webjars-play_2.12-2.4.0-2.pom
[info] Resolving org.json4s#json4s-jackson_2.12;3.4.0 ...
[warn] 	module not found: org.json4s#json4s-jackson_2.12;3.4.0
[warn] ==== local: tried
[warn]   ~/.ivy2/local/org.json4s/json4s-jackson_2.12/3.4.0/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   ~/.sbt/preloaded/org.json4s/json4s-jackson_2.12/3.4.0/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:///~/.sbt/preloaded/org/json4s/json4s-jackson_2.12/3.4.0/json4s-jackson_2.12-3.4.0.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/json4s/json4s-jackson_2.12/3.4.0/json4s-jackson_2.12-3.4.0.pom
[info] Resolving org.json4s#json4s-scalaz_2.12;3.4.0 ...
[warn] 	module not found: org.json4s#json4s-scalaz_2.12;3.4.0
[warn] ==== local: tried
[warn]   ~/.ivy2/local/org.json4s/json4s-scalaz_2.12/3.4.0/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   ~/.sbt/preloaded/org.json4s/json4s-scalaz_2.12/3.4.0/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:///~/.sbt/preloaded/org/json4s/json4s-scalaz_2.12/3.4.0/json4s-scalaz_2.12-3.4.0.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/json4s/json4s-scalaz_2.12/3.4.0/json4s-scalaz_2.12-3.4.0.pom
[info] Resolving com.adrianhurt#play-bootstrap3_2.12;0.4.5-P24 ...
[warn] 	module not found: com.adrianhurt#play-bootstrap3_2.12;0.4.5-P24
[warn] ==== local: tried
[warn]   ~/.ivy2/local/com.adrianhurt/play-bootstrap3_2.12/0.4.5-P24/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   ~/.sbt/preloaded/com.adrianhurt/play-bootstrap3_2.12/0.4.5-P24/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:///~/.sbt/preloaded/com/adrianhurt/play-bootstrap3_2.12/0.4.5-P24/play-bootstrap3_2.12-0.4.5-P24.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/adrianhurt/play-bootstrap3_2.12/0.4.5-P24/play-bootstrap3_2.12-0.4.5-P24.pom
[info] Resolving org.clapper#grizzled-slf4j_2.12;1.0.2 ...
[warn] 	module not found: org.clapper#grizzled-slf4j_2.12;1.0.2
[warn] ==== local: tried
[warn]   ~/.ivy2/local/org.clapper/grizzled-slf4j_2.12/1.0.2/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   ~/.sbt/preloaded/org.clapper/grizzled-slf4j_2.12/1.0.2/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:///~/.sbt/preloaded/org/clapper/grizzled-slf4j_2.12/1.0.2/grizzled-slf4j_2.12-1.0.2.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/clapper/grizzled-slf4j_2.12/1.0.2/grizzled-slf4j_2.12-1.0.2.pom
[info] Resolving org.apache.kafka#kafka_2.12;0.10.0.1 ...
[warn] 	module not found: org.apache.kafka#kafka_2.12;0.10.0.1
[warn] ==== local: tried
[warn]   ~/.ivy2/local/org.apache.kafka/kafka_2.12/0.10.0.1/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   ~/.sbt/preloaded/org.apache.kafka/kafka_2.12/0.10.0.1/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:///~/.sbt/preloaded/org/apache/kafka/kafka_2.12/0.10.0.1/kafka_2.12-0.10.0.1.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/apache/kafka/kafka_2.12/0.10.0.1/kafka_2.12-0.10.0.1.pom
[info] Resolving com.beachape#enumeratum_2.12;1.4.4 ...
[warn] 	module not found: com.beachape#enumeratum_2.12;1.4.4
[warn] ==== local: tried
[warn]   ~/.ivy2/local/com.beachape/enumeratum_2.12/1.4.4/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   ~/.sbt/preloaded/com.beachape/enumeratum_2.12/1.4.4/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:///~/.sbt/preloaded/com/beachape/enumeratum_2.12/1.4.4/enumeratum_2.12-1.4.4.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/beachape/enumeratum_2.12/1.4.4/enumeratum_2.12-1.4.4.pom
[info] Resolving com.typesafe.play#play-test_2.12;2.4.6 ...
[warn] 	module not found: com.typesafe.play#play-test_2.12;2.4.6
[warn] ==== local: tried
[warn]   ~/.ivy2/local/com.typesafe.play/play-test_2.12/2.4.6/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   ~/.sbt/preloaded/com.typesafe.play/play-test_2.12/2.4.6/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:///~/.sbt/preloaded/com/typesafe/play/play-test_2.12/2.4.6/play-test_2.12-2.4.6.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/play/play-test_2.12/2.4.6/play-test_2.12-2.4.6.pom
[info] Resolving org.scalatest#scalatest_2.12;2.2.1 ...
[warn] 	module not found: org.scalatest#scalatest_2.12;2.2.1
[warn] ==== local: tried
[warn]   ~/.ivy2/local/org.scalatest/scalatest_2.12/2.2.1/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   ~/.sbt/preloaded/org.scalatest/scalatest_2.12/2.2.1/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:///~/.sbt/preloaded/org/scalatest/scalatest_2.12/2.2.1/scalatest_2.12-2.2.1.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scalatest/scalatest_2.12/2.2.1/scalatest_2.12-2.2.1.pom
[info] Resolving org.scoverage#scalac-scoverage-runtime_2.12;1.1.1 ...
[warn] 	module not found: org.scoverage#scalac-scoverage-runtime_2.12;1.1.1
[warn] ==== local: tried
[warn]   ~/.ivy2/local/org.scoverage/scalac-scoverage-runtime_2.12/1.1.1/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   ~/.sbt/preloaded/org.scoverage/scalac-scoverage-runtime_2.12/1.1.1/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:///~/.sbt/preloaded/org/scoverage/scalac-scoverage-runtime_2.12/1.1.1/scalac-scoverage-runtime_2.12-1.1.1.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scoverage/scalac-scoverage-runtime_2.12/1.1.1/scalac-scoverage-runtime_2.12-1.1.1.pom
[info] Resolving org.scoverage#scalac-scoverage-plugin_2.12;1.1.1 ...
[warn] 	module not found: org.scoverage#scalac-scoverage-plugin_2.12;1.1.1
[warn] ==== local: tried
[warn]   ~/.ivy2/local/org.scoverage/scalac-scoverage-plugin_2.12/1.1.1/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   ~/.sbt/preloaded/org.scoverage/scalac-scoverage-plugin_2.12/1.1.1/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:///~/.sbt/preloaded/org/scoverage/scalac-scoverage-plugin_2.12/1.1.1/scalac-scoverage-plugin_2.12-1.1.1.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scoverage/scalac-scoverage-plugin_2.12/1.1.1/scalac-scoverage-plugin_2.12-1.1.1.pom
[info] Resolving com.typesafe.play#play-omnidoc_2.12;2.4.6 ...
[warn] 	module not found: com.typesafe.play#play-omnidoc_2.12;2.4.6
[warn] ==== local: tried
[warn]   ~/.ivy2/local/com.typesafe.play/play-omnidoc_2.12/2.4.6/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   ~/.sbt/preloaded/com.typesafe.play/play-omnidoc_2.12/2.4.6/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:///~/.sbt/preloaded/com/typesafe/play/play-omnidoc_2.12/2.4.6/play-omnidoc_2.12-2.4.6.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/play/play-omnidoc_2.12/2.4.6/play-omnidoc_2.12-2.4.6.pom
[info] Resolving jline#jline;2.14.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.play#twirl-api_2.12;1.1.1: not found
[warn] 	:: com.typesafe.play#play-server_2.12;2.4.6: not found
[warn] 	:: com.typesafe.play#play-netty-server_2.12;2.4.6: not found
[warn] 	:: com.typesafe.akka#akka-actor_2.12;2.3.14: not found
[warn] 	:: com.typesafe.akka#akka-slf4j_2.12;2.3.14: not found
[warn] 	:: org.webjars#webjars-play_2.12;2.4.0-2: not found
[warn] 	:: org.json4s#json4s-jackson_2.12;3.4.0: not found
[warn] 	:: org.json4s#json4s-scalaz_2.12;3.4.0: not found
[warn] 	:: com.adrianhurt#play-bootstrap3_2.12;0.4.5-P24: not found
[warn] 	:: org.clapper#grizzled-slf4j_2.12;1.0.2: not found
[warn] 	:: org.apache.kafka#kafka_2.12;0.10.0.1: not found
[warn] 	:: com.beachape#enumeratum_2.12;1.4.4: not found
[warn] 	:: com.typesafe.play#play-test_2.12;2.4.6: not found
[warn] 	:: org.scalatest#scalatest_2.12;2.2.1: not found
[warn] 	:: org.scoverage#scalac-scoverage-runtime_2.12;1.1.1: not found
[warn] 	:: org.scoverage#scalac-scoverage-plugin_2.12;1.1.1: not found
[warn] 	:: com.typesafe.play#play-omnidoc_2.12;2.4.6: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.clapper:grizzled-slf4j_2.12:1.0.2 (~/kafka-manager/build.sbt#L22-46)
[warn] 		  +- kafka-manager:kafka-manager_2.12:1.3.3.5
[warn] 		com.typesafe.play:play-netty-server_2.12:2.4.6 ((play.sbt.PlayNettyServer) Play.scala#L68)
[warn] 		  +- kafka-manager:kafka-manager_2.12:1.3.3.5
[warn] 		com.typesafe.play:play-server_2.12:2.4.6 ((play.sbt.PlaySettings) PlaySettings.scala#L55)
[warn] 		  +- kafka-manager:kafka-manager_2.12:1.3.3.5
[warn] 		org.json4s:json4s-scalaz_2.12:3.4.0 (~/kafka-manager/build.sbt#L22-46)
[warn] 		  +- kafka-manager:kafka-manager_2.12:1.3.3.5
[warn] 		com.typesafe.akka:akka-actor_2.12:2.3.14 (~/kafka-manager/build.sbt#L22-46)
[warn] 		  +- kafka-manager:kafka-manager_2.12:1.3.3.5
[warn] 		org.scalatest:scalatest_2.12:2.2.1 (~/kafka-manager/build.sbt#L22-46)
[warn] 		  +- kafka-manager:kafka-manager_2.12:1.3.3.5
[warn] 		com.typesafe.akka:akka-slf4j_2.12:2.3.14 (~/kafka-manager/build.sbt#L22-46)
[warn] 		  +- kafka-manager:kafka-manager_2.12:1.3.3.5
[warn] 		org.apache.kafka:kafka_2.12:0.10.0.1 (~/kafka-manager/build.sbt#L22-46)
[warn] 		  +- kafka-manager:kafka-manager_2.12:1.3.3.5
[warn] 		org.json4s:json4s-jackson_2.12:3.4.0 (~/kafka-manager/build.sbt#L22-46)
[warn] 		  +- kafka-manager:kafka-manager_2.12:1.3.3.5
[warn] 		org.scoverage:scalac-scoverage-plugin_2.12:1.1.1 ((scoverage.ScoverageSbtPlugin) ScoverageSbtPlugin.scala#L30)
[warn] 		  +- kafka-manager:kafka-manager_2.12:1.3.3.5
[warn] 		com.typesafe.play:play-test_2.12:2.4.6 ((play.sbt.PlaySettings) PlaySettings.scala#L63)
[warn] 		  +- kafka-manager:kafka-manager_2.12:1.3.3.5
[warn] 		org.scoverage:scalac-scoverage-runtime_2.12:1.1.1 ((scoverage.ScoverageSbtPlugin) ScoverageSbtPlugin.scala#L30)
[warn] 		  +- kafka-manager:kafka-manager_2.12:1.3.3.5
[warn] 		com.beachape:enumeratum_2.12:1.4.4 (~/kafka-manager/build.sbt#L22-46)
[warn] 		  +- kafka-manager:kafka-manager_2.12:1.3.3.5
[warn] 		com.typesafe.play:twirl-api_2.12:1.1.1 ((play.twirl.sbt.SbtTwirl) SbtTwirl.scala#L71)
[warn] 		  +- kafka-manager:kafka-manager_2.12:1.3.3.5
[warn] 		org.webjars:webjars-play_2.12:2.4.0-2 (~/kafka-manager/build.sbt#L22-46)
[warn] 		  +- kafka-manager:kafka-manager_2.12:1.3.3.5
[warn] 		com.typesafe.play:play-omnidoc_2.12:2.4.6 ((play.sbt.PlaySettings) PlaySettings.scala#L69)
[warn] 		  +- kafka-manager:kafka-manager_2.12:1.3.3.5
[warn] 		com.adrianhurt:play-bootstrap3_2.12:0.4.5-P24 (~/kafka-manager/build.sbt#L22-46)
[warn] 		  +- kafka-manager:kafka-manager_2.12:1.3.3.5
sbt.ResolveException: unresolved dependency: com.typesafe.play#twirl-api_2.12;1.1.1: not found
unresolved dependency: com.typesafe.play#play-server_2.12;2.4.6: not found
unresolved dependency: com.typesafe.play#play-netty-server_2.12;2.4.6: not found
unresolved dependency: com.typesafe.akka#akka-actor_2.12;2.3.14: not found
unresolved dependency: com.typesafe.akka#akka-slf4j_2.12;2.3.14: not found
unresolved dependency: org.webjars#webjars-play_2.12;2.4.0-2: not found
unresolved dependency: org.json4s#json4s-jackson_2.12;3.4.0: not found
unresolved dependency: org.json4s#json4s-scalaz_2.12;3.4.0: not found
unresolved dependency: com.adrianhurt#play-bootstrap3_2.12;0.4.5-P24: not found
unresolved dependency: org.clapper#grizzled-slf4j_2.12;1.0.2: not found
unresolved dependency: org.apache.kafka#kafka_2.12;0.10.0.1: not found
unresolved dependency: com.beachape#enumeratum_2.12;1.4.4: not found
unresolved dependency: com.typesafe.play#play-test_2.12;2.4.6: not found
unresolved dependency: org.scalatest#scalatest_2.12;2.2.1: not found
unresolved dependency: org.scoverage#scalac-scoverage-runtime_2.12;1.1.1: not found
unresolved dependency: org.scoverage#scalac-scoverage-plugin_2.12;1.1.1: not found
unresolved dependency: com.typesafe.play#play-omnidoc_2.12;2.4.6: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:294)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:127)
	at sbt.IvySbt.withIvy(Ivy.scala:124)
	at sbt.IvySbt$Module.withModule(Ivy.scala:155)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1392)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1388)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1422)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1420)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1425)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1419)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1442)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1371)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1325)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.typesafe.play#twirl-api_2.12;1.1.1: not found
[error] unresolved dependency: com.typesafe.play#play-server_2.12;2.4.6: not found
[error] unresolved dependency: com.typesafe.play#play-netty-server_2.12;2.4.6: not found
[error] unresolved dependency: com.typesafe.akka#akka-actor_2.12;2.3.14: not found
[error] unresolved dependency: com.typesafe.akka#akka-slf4j_2.12;2.3.14: not found
[error] unresolved dependency: org.webjars#webjars-play_2.12;2.4.0-2: not found
[error] unresolved dependency: org.json4s#json4s-jackson_2.12;3.4.0: not found
[error] unresolved dependency: org.json4s#json4s-scalaz_2.12;3.4.0: not found
[error] unresolved dependency: com.adrianhurt#play-bootstrap3_2.12;0.4.5-P24: not found
[error] unresolved dependency: org.clapper#grizzled-slf4j_2.12;1.0.2: not found
[error] unresolved dependency: org.apache.kafka#kafka_2.12;0.10.0.1: not found
[error] unresolved dependency: com.beachape#enumeratum_2.12;1.4.4: not found
[error] unresolved dependency: com.typesafe.play#play-test_2.12;2.4.6: not found
[error] unresolved dependency: org.scalatest#scalatest_2.12;2.2.1: not found
[error] unresolved dependency: org.scoverage#scalac-scoverage-runtime_2.12;1.1.1: not found
[error] unresolved dependency: org.scoverage#scalac-scoverage-plugin_2.12;1.1.1: not found
[error] unresolved dependency: com.typesafe.play#play-omnidoc_2.12;2.4.6: not found
[error] Total time: 2 s, completed Apr 17, 2017 7:31:43 PM
`

**Comment by Airmanbzh** [comment]
Do you find a solution ?
