### ISSUE TITLE
 Will not attempt to authenticate using SASL (unknown error)

### ISSUE THREAD

**Issue by zaqwsxa** [yahoo/kafka-manager#395]
kafka's are in cluster between 2 servers on this server I have 3 instances kafka with different port
IOS: oracle linux  4.1.12-61.1.18.el7uek.x86_64

- kafka conf/server.properties
added:
host.name=x.x.x.x
zookeeper.connect=x.x.x.x:6081,x.x.x.x:6081
other things are basic configuraton

- kafka conf/zookeeper.properties
changed data dir
custer zookeeper
server.3=x.x.x.x:6088:6089
server.4=x.x.x.x:6088:6089

also I added a file with myid (each instances has diffrent number)

- kafka manager config 
only changed 
kafka-manager.zkhosts="x.x.x.x:6081"

How I'm running kafka manager
./bin/kafka-manager -Dconfig.file=conf/application.conf -Dkafka-manager.zkhosts="x.x.x.x:6081" -Dhttp.port=80

- kafka manager logs

[info] o.a.z.ZooKeeper - Client environment:user.dir=/app/kafka-manager-1.3.3.4
[info] o.a.z.ZooKeeper - Initiating client connection, connectString=x.x.x.x:6081 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@75973366
[info] o.a.z.ClientCnxn - Opening socket connection to server x.x.x.x/x.x.x.x:6081. Will not attempt to authenticate using SASL (unknown error)
[info] o.a.z.ClientCnxn - Socket connection established to x.x.x.x/x.x.x.x:6081, initiating session
[info] o.a.z.ClientCnxn - Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect
[info] k.m.a.KafkaManagerActor - zk=x.x.x.x:6081
[info] k.m.a.KafkaManagerActor - baseZkPath=/kafka-manager
[info] play.api.Play - Application started (Prod)
[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:80
[info] o.a.z.ClientCnxn - Opening socket connection to server x.x.x.x/x.x.x.x:6081. Will not attempt to authenticate using SASL (unknown error)
[info] o.a.z.ClientCnxn - Socket connection established to x.x.x.x/x.x.x.x:6081, initiating session
[info] o.a.z.ClientCnxn - Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect
[info] o.a.z.ClientCnxn - Opening socket connection to server x.x.x.x/x.x.x.x:6081. Will not attempt to authenticate using SASL (unknown error)
[info] o.a.z.ClientCnxn - Socket connection established to x.x.x.x/x.x.x.x:6081, initiating session
[info] o.a.z.ClientCnxn - Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect
[info] o.a.z.ClientCnxn - Opening socket connection to server x.x.x.x/x.x.x.x:6081. Will not attempt to authenticate using SASL (unknown error)
[info] o.a.z.ClientCnxn - Socket connection established to x.x.x.x/x.x.x.x:6081, initiating session
[info] o.a.z.ClientCnxn - Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect
[info] o.a.z.ClientCnxn - Opening socket connection to server x.x.x.x/x.x.x.x:6081. Will not attempt to authenticate using SASL (unknown error)
[info] o.a.z.ClientCnxn - Socket connection established to x.x.x.x/x.x.x.x:6081, initiating session
[info] o.a.z.ClientCnxn - Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect
[info] o.a.z.ClientCnxn - Opening socket connection to server x.x.x.x/x.x.x.x:6081. Will not attempt to authenticate using SASL (unknown error)
[info] o.a.z.ClientCnxn - Socket connection established to x.x.x.x/x.x.x.x:6081, initiating session
[info] o.a.z.ClientCnxn - Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect
[error] k.m.ApiError$ - error : Ask timed out on [ActorSelection[Anchor(akka://kafka-manager-system/), Path(/user/kafka-manager)]] after [5000 ms]
akka.pattern.AskTimeoutException: Ask timed out on [ActorSelection[Anchor(akka://kafka-manager-system/), Path(/user/kafka-manager)]] after [5000 ms]
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334) ~[com.typesafe.akka.akka-actor_2.11-2.3.14.jar:na]
	at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117) ~[com.typesafe.akka.akka-actor_2.11-2.3.14.jar:na]
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467) ~[com.typesafe.akka.akka-actor_2.11-2.3.14.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419) ~[com.typesafe.akka.akka-actor_2.11-2.3.14.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423) ~[com.typesafe.akka.akka-actor_2.11-2.3.14.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375) ~[com.typesafe.akka.akka-actor_2.11-2.3.14.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
[info] o.a.z.ClientCnxn - Opening socket connection to server x.x.x.x/x.x.x.x:6081. Will not attempt to authenticate using SASL (unknown error)
[info] o.a.z.ClientCnxn - Socket connection established to x.x.x.x/x.x.x.x:6081, initiating session
[info] o.a.z.ClientCnxn - Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect
[info] o.a.z.ClientCnxn - Opening socket connection to server x.x.x.x/x.x.x.x:6081. Will not attempt to authenticate using SASL (unknown error)
[info] o.a.z.ClientCnxn - Socket connection established to x.x.x.x/x.x.x.x:6081, initiating session
[info] o.a.z.ClientCnxn - Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect
[info] o.a.z.ClientCnxn - Opening socket connection to server x.x.x.x/x.x.x.x:6081. Will not attempt to authenticate using SASL (unknown error)
[info] o.a.z.ClientCnxn - Socket connection established to x.x.x.x/x.x.x.x:6081, initiating session
[info] o.a.z.ClientCnxn - Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect
[info] o.a.z.ClientCnxn - Opening socket connection to server x.x.x.x/x.x.x.x:6081. Will not attempt to authenticate using SASL (unknown error)
[info] o.a.z.ClientCnxn - Socket connection established to x.x.x.x/x.x.x.x:6081, initiating session
[info] o.a.z.ClientCnxn - Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect
[info] o.a.z.ClientCnxn - Opening socket connection to server x.x.x.x/x.x.x.x:6081. Will not attempt to authenticate using SASL (unknown error)
[info] o.a.z.ClientCnxn - Socket connection established to x.x.x.x/x.x.x.x:6081, initiating session
[info] o.a.z.ClientCnxn - Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect

- important
- Other instances on port x.x.x.x:9081 in cluster are working propertly, everything is fine

**Comment by gygesM** [comment]
so do i

**Comment by fantine16** [comment]
so do i

**Comment by Dougoc** [comment]
so do i

**Comment by prasanjit-** [comment]
so do i :)

**Comment by coolspring1293** [comment]
so do i

**Comment by mrromadon** [comment]
so do i 👍

**Comment by csarora** [comment]
I am also getting same error, any solution ? works ok when i have one zookeeper server but for more than one zookeeper to connect then Kafka fails to connect.

```
[2018-02-16 12:32:43,864] INFO Socket connection established to 10.32.0.110/10.32.0.110:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2018-02-16 12:32:43,866] INFO Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
..

2018-02-16 12:32:49,027] FATAL Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server '10.32.0.108:2181,10.32.0.110:2181,10.32.0.111:2181' with timeout of 9000 ms
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1233)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:157)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:131)
	at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:106)
	at kafka.utils.ZkUtils$.apply(ZkUtils.scala:88)
	at kafka.server.KafkaServer.initZk(KafkaServer.scala:326)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:187)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:39)
	at kafka.Kafka$.main(Kafka.scala:67)
	at kafka.Kafka.main(Kafka.scala)
[2018-02-16 12:32:49,030] INFO shutting down (kafka.server.KafkaServer)
```

**Comment by RymMichaut** [comment]
So do I but with Zookeeper and Druid

**Comment by boisde** [comment]
So do I.

**Comment by saeedsh** [comment]
So do I in Druid for Zookeeper cluster

**Comment by mohithg** [comment]
Any updates here?

**Comment by msalihkarakasli** [comment]
So do I?

**Comment by melwynjensen** [comment]
So do I.

**Comment by ZeinabAshjaei** [comment]
So do I.

**Comment by swapneeldatta** [comment]
So do I

**Comment by pulyavin** [comment]
So do I

**Comment by AftabVirtual** [comment]
So do I

**Comment by pulyavin** [comment]
I set `maxClientCnxns=1000` in ZooKeeper conf and it helps me

**Comment by arumoy** [comment]
> So do I.
> 
> ::Update:: Found the issue, it was an internal communication problem with Kafka to Zookeeper as it was not able to reach the node. Reassigned the nodes properly and it was up and running.

How did you re-assign the nodes?

**Comment by MagicJohnJang** [comment]
Finally work! 
You got to create the cluster in Zookeeper first, then start Kafka!

Because you give Kafka multiple zookeeper addresses, which means you tell Kafka to connect a cluster.

**Comment by mitchell0000** [comment]
so do i :slightly_smiling_face:

**Comment by MCKad** [comment]
So do I.

**Comment by subatheesh** [comment]
so do i

**Comment by sl2026** [comment]
俺也一样!

**Comment by realzhangqingwei** [comment]
俺也一样

**Comment by Maxtaoge** [comment]
so do i

**Comment by JonnyLewis** [comment]
so do i

**Comment by batmanneverdie** [comment]
俺也一样

**Comment by become-nice** [comment]
俺也一样

**Comment by Best1s** [comment]
so di i

**Comment by Best1s** [comment]
so do i

**Comment by binaryjerry** [comment]
so do i

**Comment by gulsenbi** [comment]
Same error, still continue in 2021.

**Comment by qzwlinux** [comment]
Same error, still continue in 2021.

**Comment by forwardxao** [comment]
so do i

**Comment by forwardxao** [comment]
you are very not good

**Comment by sxiii** [comment]
Same here, any solutions? :)

**Comment by jinjin9527** [comment]
So do I...

**Comment by longruiran** [comment]
So do I

**Comment by daeyoungwon-dev** [comment]
So do I

**Comment by Shavakan** [comment]
So do I

**Comment by jungnoh** [comment]
So do I

**Comment by Tangsonghuai** [comment]
so do I ,

**Comment by petermok-1213** [comment]
So do I

**Comment by ChuanGoing** [comment]
俺也一样

**Comment by qianghong000** [comment]
社区问题没人搭理了吗
