### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by zweite** [yahoo/kafka-manager#404]
```
[warn] k.m.a.c.KafkaManagedOffsetCache - Failed to process a message from offset topic on cluster toutiao!
java.lang.NullPointerException: null
	at java.nio.ByteBuffer.wrap(ByteBuffer.java:396) ~[na:1.8.0_131]
	at kafka.manager.actor.cluster.KafkaManagedOffsetCache$$anonfun$run$3.apply(KafkaStateActor.scala:293) [kafka-manager.kafka-manager-1.3.3.7-sans-externalized.jar:na]
	at kafka.manager.actor.cluster.KafkaManagedOffsetCache$$anonfun$run$3.apply(KafkaStateActor.scala:243) [kafka-manager.kafka-manager-1.3.3.7-sans-externalized.jar:na]
	at scala.util.Success.foreach(Try.scala:236) [org.scala-lang.scala-library-2.11.8.jar:na]
	at kafka.manager.actor.cluster.KafkaManagedOffsetCache.run(KafkaStateActor.scala:243) [kafka-manager.kafka-manager-1.3.3.7-sans-externalized.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```

kafka version: 2.10-0.10.0.0
kafka manager version: 1.3.3.7

**Comment by simplesteph** [comment]
same here, using latest version
