### ISSUE TITLE
start kafka-manager  server error?

### ISSUE THREAD

**Issue by LynnYuanInspur** [yahoo/kafka-manager#416]
1. start shell script:
[lynn@lynn kafka-manager-1.3.3.8]$ more start.sh 
#!/bin/bash
app_home=`pwd`
${app_home}/bin/kafka-manager -Dconfig.file=${app_home}/config/application.conf -Dhttp.port=9000

2. JAVA Environment:
[lynn@lynn kafka-manager-1.3.3.8]$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
[lynn@lynn kafka-manager-1.3.3.8]$ javac -version
javac 1.8.0_121

3. LOG ERRORS:
Oops, cannot start the server.
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Could not find a suitable constructor in controllers.ApiHealth. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at controllers.ApiHealth.class(ApiHealth.scala:6)
  while locating controllers.ApiHealth
    for parameter 11 at router.Routes.<init>(Routes.scala:67)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

2) Could not find a suitable constructor in controllers.Application. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at controllers.Application.class(Application.scala:16)
  while locating controllers.Application
    for parameter 1 at router.Routes.<init>(Routes.scala:67)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

**Comment by LynnYuanInspur** [comment]
the config file application.conf 's path is wrong!!!
${app_home}/bin/kafka-manager -Dconfig.file=${app_home}/conf/application.conf -Dhttp.port=9000
