### ISSUE TITLE
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode Error

### ISSUE THREAD

**Issue by fjosemarquina** [yahoo/kafka-manager#427]
Hi,

I just compiled and started the last version of kafka manager. Config property kafka-manager.zkhosts is set with a cluster of three zookeepers in that way _kafka-manager.zkhosts="zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"_.

But when I start kafka manager I get this error ...

[error] a.a.OneForOneStrategy - KeeperErrorCode = NoNode for /config/topics
akka.actor.ActorInitializationException: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:166) ~[com.typesafe.akka.akka-actor_2.11-2.3.14.jar:na]
	at akka.actor.ActorCell.create(ActorCell.scala:596) ~[com.typesafe.akka.akka-actor_2.11-2.3.14.jar:na]
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456) ~[com.typesafe.akka.akka-actor_2.11-2.3.14.jar:na]
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478) ~[com.typesafe.akka.akka-actor_2.11-2.3.14.jar:na]
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263) ~[com.typesafe.akka.akka-actor_2.11-2.3.14.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:219) ~[com.typesafe.akka.akka-actor_2.11-2.3.14.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /config/topics
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111) ~[org.apache.zookeeper.zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51) ~[org.apache.zookeeper.zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1590) ~[org.apache.zookeeper.zookeeper-3.4.6.jar:3.4.6-1569965]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:214) ~[org.apache.curator.curator-framework-2.10.0.jar:na]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:203) ~[org.apache.curator.curator-framework-2.10.0.jar:na]
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:108) ~[org.apache.curator.curator-client-2.10.0.jar:na]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:200) ~[org.apache.curator.curator-framework-2.10.0.jar:na]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:191) ~[org.apache.curator.curator-framework-2.10.0.jar:na]
	at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:38) ~[org.apache.curator.curator-framework-2.10.0.jar:na]
	at org.apache.curator.framework.recipes.cache.PathChildrenCache.rebuild(PathChildrenCache.java:330) ~[org.apache.curator.curator-recipes-2.10.0.jar:na]

The conectivity from the kafka-manager host to zookeeper hosts are ok.
My zookeeper node for Kafka is /kafka so the nodes for topics are in /kafka/node/topics, I guess that's the problem. But then, how can change in kafka-manager the default node path?

It's not possible I supose that I have to change my zookeeper.connect property in kafka server.properties from zookeeper.connect=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181/kafka to zookeeper.connect=zookeeper1:2181,zookeeper2:2181,zookeeper3:2181

Thanks.

**Comment by rehevkor5** [comment]
`kafka-manager.zkhosts` should provide the connection string (including chroot) for Kafka-manager's internal state. Everything kafka-manager stores will be underneath the node "/kafka-manager" as defined in `KafkaManagerActor$ZkRoot`.

The error you are describing, about difficulty with "NoNode for /config/topics" must be happening during initialization of `ClusterManagerActor` for a specific Kafka cluster. That will use the Zookeeper connection string (with chroot) that you have provided when you added the cluster to Kafka-manager in the UI. So, double check that the "Cluster Zookeeper Hosts" config for your cluster is correct. The connection string you wrote looks correct.

That said, you may have done everything right, but you can still encounter that problem. When I run kafka-manager it frequently (maybe half the time) thinks that a Zookeeper node (either for kafka-manager or for my kafka cluster) doesn't exist, even though it definitely does, and even though the Curator client is fully connected. I don't know why it does this yet. If you re-launch the software, eventually it will succeed.

Sadly, the design of the software means that if an agent fails to initialize, the software will continue to run and serve pages, but all Akka requests handled by that agent will time out. It seems like it would be better for the software to either fail-fast (so that health checks can take corrective action) or attempt to restart the agent when it fails.
