### ISSUE TITLE
Failed to parse endpoint - key not found / support for 0.10.2.1+ ?

### ISSUE THREAD

**Issue by ct16k** [yahoo/kafka-manager#433]
Hello,

We're getting the following errors logged for each interface of each broker in a 0.11.0.0 test cluster (so quite a lot of errors):
```
[error] k.m.m.ActorModel$BrokerIdentity$ - Failed to parse endpoint : INTERNAL_PLAINTEXT://192.168.145.14:9092
java.util.NoSuchElementException: key not found: INTERNAL_PLAINTEXT
        at scala.collection.MapLike$class.default(MapLike.scala:228) ~[org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.collection.AbstractMap.default(Map.scala:59) ~[org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.collection.MapLike$class.apply(MapLike.scala:141) ~[org.scala-lang.scala-library-2.11.11.jar:na]
        at scala.collection.AbstractMap.apply(Map.scala:59) ~[org.scala-lang.scala-library-2.11.11.jar:na]
        at kafka.manager.model.SecurityProtocol$.apply(model.scala:410) ~[kafka-manager.kafka-manager-1.3.3.13-sans-externalized.jar:na]
        at kafka.manager.model.ActorModel$BrokerIdentity$$anonfun$6$$anonfun$apply$6$$anonfun$7$$anonfun$apply$7.apply(ActorModel.scala:262) ~[kafka-manager.kafka-manager-1.3.3.13-sans-externalized.jar:na]
        at kafka.manager.model.ActorModel$BrokerIdentity$$anonfun$6$$anonfun$apply$6$$anonfun$7$$anonfun$apply$7.apply(ActorModel.scala:259) ~[kafka-manager.kafka-manager-1.3.3.13-sans-externalized.jar:na]
        at scalaz.Validation$.fromTryCatchNonFatal(Validation.scala:397) ~[org.scalaz.scalaz-core_2.11-7.2.4.jar:na]
        at kafka.manager.model.ActorModel$BrokerIdentity$$anonfun$6$$anonfun$apply$6$$anonfun$7.apply(ActorModel.scala:259) [kafka-manager.kafka-manager-1.3.3.13-sans-externalized.jar:na]
        at kafka.manager.model.ActorModel$BrokerIdentity$$anonfun$6$$anonfun$apply$6$$anonfun$7.apply(ActorModel.scala:258) [kafka-manager.kafka-manager-1.3.3.13-sans-externalized.jar:na
```
We're using the following config:
```
inter.broker.listener.name=INTERNAL_PLAINTEXT
listener.security.protocol.map=EXTERNAL_PLAINTEXT:PLAINTEXT,INTERNAL_PLAINTEXT:PLAINTEXT
listeners=INTERNAL_PLAINTEXT://192.168.145.14:9092,EXTERNAL_PLAINTEXT://192.168.130.106:9093
```
From having a similar issue with another tool, we found out versions above 0.10.2.0 use a newer format when registering with zookeeper, which is probably why we're encountering this error.

Unfortunately, simply modifying `build.sbt` to build kafka-manager with a newer kafka version (I used 0.10.2.1) doesn't work:
```
[error] /root/kafka-manager/app/kafka/manager/actor/cluster/KafkaStateActor.scala:114: value describeGroup is not a member of kafka.admin.AdminClient
[error]                       val summary = client.describeGroup(group)
[error]                                            ^
```
Any tips?

Thank you!

**Comment by sshantveer** [comment]
Did you get it working ? I am facing similar issue.
java.util.NoSuchElementException: key not found: OUTSIDE

**Comment by cecchisandrone** [comment]
+1

**Comment by ct16k** [comment]
Unfortunately I left that project before finding a solution and have no way of telling if they did fix it somehow or not.
