### ISSUE TITLE
HA for kafka manager

### ISSUE THREAD

**Issue by tanuj83** [yahoo/kafka-manager#437]
How can I configure kafka Manager on 2 nodes for same kafka Clusters?
If I configure a separate KM with different ZK for same kafka cluster, then both KM portal shows different metrics and different consumers, which looks like due to KafkaManagedOffsetCache is shared in that case.

KM1/ZK1 -> MyCluster1, MyCluster2, MyCluster3......,MyCluster20
KM2/ZK2 -> MyCluster1, MyCluster2, MyCluster3......,MyCluster20

Looking to keep KM available in case one of my KM node crashes

**Comment by tanuj83** [comment]
any idea on this?

**Comment by patelh** [comment]
Not sure why u can't already run 2 KM instances at same time.  Each instance will haven its own offset cache.

**Comment by tanuj83** [comment]
@patelh will KafkaManagedOffsetCache cause any issue like conflict as using same kafka cluster by two different KM?

**Comment by tanuj83** [comment]
The below design is working with no issue 

KM1/ZK1 -> MyCluster1, MyCluster2, MyCluster3......,MyCluster20
KM2/ZK2 -> MyCluster1, MyCluster2, MyCluster3......,MyCluster20

now need two types of instances, one is readonly and other admin access. as KM doesn't support RBAC, so I created 2 instances by copying to new home directory and able to restart successfully

KM**1**/ZK1 -> MyCluster1, MyCluster2, MyCluster3......,MyCluster20
KM**2**/ZK1 -> MyCluster1, MyCluster2, MyCluster3......,MyCluster20
But on accessing the KM GUI, only 1 of them works and other gets error

`
! @75mekbfcn - Internal server error, for (GET) [/km/] ->

play.api.UnexpectedException: Unexpected exception[IllegalStateException: cannot enqueue after timer shutdown]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:151) [com.typesafe.play.play-netty-server_2.11-2.4.6.jar:2.4.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:148) [com.typesafe.play.play-netty-server_2.11-2.4.6.jar:2.4.6]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.util.Try$.apply(Try.scala:192) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.util.Failure.recover(Try.scala:216) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326) [org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326) [org.scala-lang.scala-library-2.11.8.jar:na]
Caused by: java.lang.IllegalStateException: cannot enqueue after timer shutdown
	at akka.actor.LightArrayRevolverScheduler.scheduleOnce(Scheduler.scala:277) ~[com.typesafe.akka.akka-actor_2.11-2.3.14.jar:na]
	at akka.actor.Scheduler$class.scheduleOnce(Scheduler.scala:117) ~[com.typesafe.akka.akka-actor_2.11-2.3.14.jar:na]
	at akka.actor.LightArrayRevolverScheduler.scheduleOnce(Scheduler.scala:182) ~[com.typesafe.akka.akka-actor_2.11-2.3.14.jar:na]
	at akka.pattern.PromiseActorRef$.apply(AskSupport.scala:333) ~[com.typesafe.akka.akka-actor_2.11-2.3.14.jar:na]
	at akka.pattern.AskableActorSelection$.ask$extension(AskSupport.scala:158) ~[com.typesafe.akka.akka-actor_2.11-2.3.14.jar:na]
	at kafka.manager.KafkaManager.kafka$manager$KafkaManager$$tryWithKafkaManagerActor(KafkaManager.scala:195) ~[kafka-manager.kafka-manager-1.3.3.14-sans-externalized.jar:na]
	at kafka.manager.KafkaManager.getClusterList(KafkaManager.scala:580) ~[kafka-manager.kafka-manager-1.3.3.14-sans-externalized.jar:na]
	at controllers.Application$$anonfun$index$1.apply(Application.scala:24) ~[kafka-manager.kafka-manager-1.3.3.14-sans-externalized.jar:na]
	at controllers.Application$$anonfun$index$1.apply(Application.scala:24) ~[kafka-manager.kafka-manager-1.3.3.14-sans-externalized.jar:na]
	at play.api.mvc.ActionBuilder$$anonfun$async$1.apply(Action.scala:456) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
`

also see error as  [#401](https://github.com/yahoo/kafka-manager/issues/401)

Is there anyway to run two duplicate instances using same ZK ?

**Comment by DavidLiuXh** [comment]
This problem has been solved in the new version.
```
props.put(org.apache.kafka.clients.consumer.ConsumerConfig.GROUP_ID_CONFIG, s"KMOffsetCache-$hostname")
```

**Comment by yuqili** [comment]
The above solution addresses the problem  of different instances of Kafka Manager on different nodes. 
Could we extend it bit to include port number in the consumer group name?

Currently we run two instances of Kafka Manager(for backup and load sharing) on the same node in Dev environment where resource is limited. And we found each instance just contained partial information about the Kafka cluster because the two instances are in the same group.
