### ISSUE TITLE
Kafka Manager not recognizing Kafka brokers from Kubernetes images

### ISSUE THREAD

**Issue by balavivek143** [yahoo/kafka-manager#455]
Hello, we have Kafka & Zookeeper on Kubernetes server and custom listener.security.protocol.map labels (Ex. **EXTERNAL**, **INTERNAL**) in Kubernetes installation. 
When pointing Kafka-manager (installed outside of Kubernetes environment) to the images in Kubernetes in above set up, we are getting an error stating it can't resolve the label '**EXTERNAL**' map.
Kafka-manager not recognizing kubernete labels. 

We are using correct IP and port for the broker, but the brokers are not showing up in the manager UI as it doesn't resolve the customer protocol map label **EXTERNAL** we are using in kubernetes with node ports and we need to map the listeners like this for it to even work.
 
Please let us know how to either configure Kafka-manager, or what we can do to make it work with our custom mapping.

_**Our Properties in Kubernetes environment**_
- listener.security.protocol.map=INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
- advertised.listeners=INTERNAL://${ADVERTISED_HOST}:9092,EXTERNAL://$EXTERNAL_IP_ADDRESS_NODE:$BROKER_PORT
- listeners=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:$BROKER_PORT
- inter.broker.listener.name=INTERNAL

_**Error log from Kafka-manager**_
[error] k.m.m.ActorModel$BrokerIdentity$ - Failed to parse endpoint : EXTERNAL://XXX.XXX.XX.XX:PPPPP
java.util.NoSuchElementException: key not found: EXTERNAL
        at scala.collection.MapLike$class.default(MapLike.scala:228) ~[org.scala-lang.scala-library-2.11.8.jar:na]
        at scala.collection.AbstractMap.default(Map.scala:59) ~[org.scala-lang.scala-library-2.11.8.jar:na]
        at scala.collection.MapLike$class.apply(MapLike.scala:141) ~[org.scala-lang.scala-library-2.11.8.jar:na]
        at scala.collection.AbstractMap.apply(Map.scala:59) ~[org.scala-lang.scala-library-2.11.8.jar:na]
        at kafka.manager.model.SecurityProtocol$.apply(model.scala:415) ~[kafka-manager.kafka-manager-1.3.3.14-sans-externalized.jar:na]
        at kafka.manager.model.ActorModel$BrokerIdentity$$anonfun$6$$anonfun$apply$6$$anonfun$7$$anonfun$apply$7.apply(ActorModel.scala:262) ~[kafka-manager.kafka-manager-1.3.3.14-sans-externalized.jar:na]
        at kafka.manager.model.ActorModel$BrokerIdentity$$anonfun$6$$anonfun$apply$6$$anonfun$7$$anonfun$apply$7.apply(ActorModel.scala:259) ~[kafka-manager.kafka-manager-1.3.3.14-sans-externalized.jar:na]
        at scalaz.Validation$.fromTryCatchNonFatal(Validation.scala:397) ~[org.scalaz.scalaz-core_2.11-7.2.4.jar:na]
        at kafka.manager.model.ActorModel$BrokerIdentity$$anonfun$6$$anonfun$apply$6$$anonfun$7.apply(ActorModel.scala:259) [kafka-manager.kafka-manager-1.3.3.14-sans-externalized.jar:na]
        at kafka.manager.model.ActorModel$BrokerIdentity$$anonfun$6$$anonfun$apply$6$$anonfun$7.apply(ActorModel.scala:258) [kafka-manager.kafka-manager-1.3.3.14-sans-externalized.jar:na]
[error] k.m.a.c.KafkaStateActor - Failed to parse broker config NonEmpty[UncategorizedError(host,unexpected value : JNull expected : JString,List())]
[error] k.m.a.c.KafkaStateActor - Failed to parse broker config NonEmpty[UncategorizedError(host,unexpected value : JNull expected : JString,List())]
[error] k.m.a.c.KafkaStateActor - Failed to parse broker config NonEmpty[UncategorizedError(host,unexpected value : JNull expected : JString,List())]
[info] k.m.a.KafkaManagerActor - Updating internal state...

**Comment by solsson** [comment]
I think this was fixed by #484, and can be closed. However we have https://github.com/Yolean/kubernetes-kafka/issues/192 now instead, which I think is caused by the wrong listener being selected.
