### ISSUE TITLE
kafka-manager keeps consuming memory (memory leak ?)

### ISSUE THREAD

**Issue by prune998** [yahoo/kafka-manager#458]
Hi,

I have a Kafka Manager deployed in Kubernetes. 
I can see from my monitoring that it keeps using more and more memory.
Nobody is using the interface. It's just running by itself.

![image](https://user-images.githubusercontent.com/1110398/34109698-6cadc2ec-e3d2-11e7-8303-1da24ba8e519.png)

I finally restarted it and it's now taking "only" 412Mo of memory, still without using it.

I'm using kafka-manager-1.3.3.11 
Will try to provide more info but any specific test to do or debug to provide  is welcome.

**Comment by bradenwright** [comment]
Any update on this, I was considering running it in K8s as well, but that's obv not ideal

**Comment by prune998** [comment]
I upgraded to Kafka manger 1.3.3.16 and memory issue seems to still be there...
![image](https://user-images.githubusercontent.com/1110398/38085487-b6f96b1c-331e-11e8-83da-442d983ee8c5.png)

I am building my own image with this Dockerfile (which is based on the same image as yours) : 

```
FROM hseeberger/scala-sbt
# https://hub.docker.com/r/sheepkiller/kafka-manager/~/dockerfile/

MAINTAINER Prune <prune@xxx.xxx>
ARG CI_COMMIT_TAG="none"
ARG CI_COMMIT_SHA="none"
ARG NOW="unknown"
ARG KAFKA_MANAGER_VERSION="1.3.3.16"

ENV ZK_HOSTS=localhost:2181 \
     KM_VERSION=$KAFKA_MANAGER_VERSION

RUN mkdir -p /tmp && \
    cd /tmp && \
    wget https://github.com/yahoo/kafka-manager/archive/${KM_VERSION}.tar.gz && \
    tar xxf ${KM_VERSION}.tar.gz && \
    cd /tmp/kafka-manager-${KM_VERSION} && \
    sbt clean dist && \
    unzip  -d / ./target/universal/kafka-manager-${KM_VERSION}.zip && \
    rm -fr /tmp/${KM_VERSION} /tmp/kafka-manager-${KM_VERSION} && \
    ln -s /kafka-manager-${KM_VERSION} /kafka-manager

WORKDIR /kafka-manager-${KM_VERSION}

EXPOSE 9000
ENTRYPOINT ["./bin/kafka-manager","-Dconfig.file=conf/application.conf"]
```

**Comment by androndo** [comment]
I watched same problem on current release (1.3.3.22)
![image](https://user-images.githubusercontent.com/5849626/51673240-f1223200-1fe6-11e9-8755-9a0f7d6bcccd.png)

**Comment by AttwellBrian** [comment]
I'm also seeing this with `1.3.3.23`. 

In the figure below, you can see the following alternating patterns:
1. periods of escalating memory usage, after which GC is able to reclaim *some* memory
2 periods of escalating memory usage after which the service is restarted

Classic example of a ramped sawtooth pattern caused by a memory leak

<img width="660" alt="Screen Shot 2019-04-12 at 11 46 36 AM" src="https://user-images.githubusercontent.com/549900/56059327-acba4e80-5d18-11e9-98f2-5e32a96dce13.png">

**Comment by mveroone** [comment]
Same here on Docker / Rancher 1.6 using v `1.3.3.22`:
![image](https://user-images.githubusercontent.com/44051537/56424930-764d7800-62b2-11e9-8e76-651865393dd8.png)

**Comment by ucabsdp** [comment]
> Same here on Docker / Rancher 1.6 using v `1.3.3.22`:
> ![image](https://user-images.githubusercontent.com/44051537/56424930-764d7800-62b2-11e9-8e76-651865393dd8.png)
> 
> Note : no JMX polling, 1 cluster of 3 brokers, around 150 topics, 2 consumer groups

Any fix on this, i'm running 5.2.1 and seeing the same issue

**Comment by vicmerlis** [comment]
any updates? i tried several versions but looks like there is a memory leak :\

log error:
`2020-02-17 14:50:16,833 - [ERROR] a.a.ActorSystemImpl - Uncaught error from thread [kafka-manager-system-akka.actor.default-dispatcher-53]: GC overhead limit exceeded, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[kafka-manager-system]
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at scala.collection.immutable.HashSet$HashTrieSet.updated0(HashSet.scala:551)
	at scala.collection.immutable.HashSet$HashTrieSet.updated0(HashSet.scala:548)
	at scala.collection.immutable.HashSet.$plus(HashSet.scala:84)
	at scala.collection.immutable.HashSet.$plus(HashSet.scala:35)
	at scala.collection.mutable.SetBuilder.$plus$eq(SetBuilder.scala:28)
	at scala.collection.mutable.SetBuilder.$plus$eq(SetBuilder.scala:24)
	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$Lambda$123/48361312.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
2020-02-17 14:50:16,852 - [INFO] p.c.s.AkkaHttpServer - Stopping server...`

**Comment by dpajin** [comment]
I am seeing the memory leak with the latest version of CMAK 3.0.0.1 in Docker container... it makes this application unusable, since it grows from ~500MB to 6GB in a day. 
The JMX metric collection is disabled and the single Kafka cluster has negligible number of messages. 

![image](https://user-images.githubusercontent.com/1251740/75466928-3e5f9880-598b-11ea-9466-5f864332e6e0.png)

The logs are show huge amount of these:
```

2020-02-27 09:52:03,301 - [WARN] o.a.k.c.NetworkClient - [Consumer clientId=consumer-KMOffsetCache-ac805b8c58a1-4789, groupId=KMOffsetCache-ac805b8c58a1] 25 partitions have leader brokers without a matching listener, including [__consumer_offsets-9, __consumer_offsets-39, __consumer_offsets-11, __consumer_offsets-31, __consumer_offsets-13, __consumer_offsets-43, __consumer_offsets-29, __consumer_offsets-1, __consumer_offsets-41, __consumer_offsets-27]
2020-02-27 09:52:03,406 - [WARN] o.a.k.c.NetworkClient - [Consumer clientId=consumer-KMOffsetCache-ac805b8c58a1-4789, groupId=KMOffsetCache-ac805b8c58a1] 25 partitions have leader brokers without a matching listener, including [__consumer_offsets-9, __consumer_offsets-39, __consumer_offsets-11, __consumer_offsets-31, __consumer_offsets-13, __consumer_offsets-43, __consumer_offsets-29, __consumer_offsets-1, __consumer_offsets-41, __consumer_offsets-27]
2020-02-27 09:52:03,510 - [WARN] o.a.k.c.NetworkClient - [Consumer clientId=consumer-KMOffsetCache-ac805b8c58a1-4789, groupId=KMOffsetCache-ac805b8c58a1] 25 partitions have leader brokers without a matching listener, including [__consumer_offsets-9, __consumer_offsets-39, __consumer_offsets-11, __consumer_offsets-31, __consumer_offsets-13, __consumer_offsets-43, __consumer_offsets-29, __consumer_offsets-1, __consumer_offsets-41, __consumer_offsets-27]
2020-02-27 09:52:03,619 - [WARN] o.a.k.c.NetworkClient - [Consumer clientId=consumer-KMOffsetCache-ac805b8c58a1-4789, groupId=KMOffsetCache-ac805b8c58a1] 25 partitions have leader brokers without a matching listener, including [__consumer_offsets-9, __consumer_offsets-39, __consumer_offsets-11, __consumer_offsets-31, __consumer_offsets-13, __consumer_offsets-43, __consumer_offsets-29, __consumer_offsets-1, __consumer_offsets-41, __consumer_offsets-27]
2020-02-27 09:52:03,722 - [WARN] o.a.k.c.NetworkClient - [Consumer clientId=consumer-KMOffsetCache-ac805b8c58a1-4789, groupId=KMOffsetCache-ac805b8c58a1] 25 partitions have leader brokers without a matching listener, including [__consumer_offsets-9, __consumer_offsets-39, __consumer_offsets-11, __consumer_offsets-31, __consumer_offsets-13, __consumer_offsets-43, __consumer_offsets-29, __consumer_offsets-1, __consumer_offsets-41, __consumer_offsets-27]
2020-02-27 09:52:03,825 - [WARN] o.a.k.c.NetworkClient - [Consumer clientId=consumer-KMOffsetCache-ac805b8c58a1-4789, groupId=KMOffsetCache-ac805b8c58a1] 25 partitions have leader brokers without a matching listener, including [__consumer_offsets-9, __consumer_offsets-39, __consumer_offsets-11, __consumer_offsets-31, __consumer_offsets-13, __consumer_offsets-43, __consumer_offsets-29, __consumer_offsets-1, __consumer_offsets-41, __consumer_offsets-27]
2020-02-27 09:52:03,932 - [WARN] o.a.k.c.NetworkClient - [Consumer clientId=consumer-KMOffsetCache-ac805b8c58a1-4789, groupId=KMOffsetCache-ac805b8c58a1] 25 partitions have leader brokers without a matching listener, including [__consumer_offsets-9, __consumer_offsets-39, __consumer_offsets-11, __consumer_offsets-31, __consumer_offsets-13, __consumer_offsets-43, __consumer_offsets-29, __consumer_offsets-1, __consumer_offsets-41, __consumer_offsets-27]
2020-02-27 09:52:04,047 - [WARN] o.a.k.c.NetworkClient - [Consumer clientId=consumer-KMOffsetCache-ac805b8c58a1-4789, groupId=KMOffsetCache-ac805b8c58a1] 25 partitions have leader brokers without a matching listener, including [__consumer_offsets-9, __consumer_offsets-39, __consumer_offsets-11, __consumer_offsets-31, __consumer_offsets-13, __consumer_offsets-43, __consumer_offsets-29, __consumer_offsets-1, __consumer_offsets-41, __consumer_offsets-27]


```

Dockerfile:

**Comment by jonbuffington** [comment]
@dpajin We are seeing the same issue. I spent some time cleaning up build.sbt (e.g., `"org.apache.kafka" % "kafka-streams" % "2.4.0" % "test"`)  and applying the following JVM settings for our deployment in a k8s cluster:

```
- -Djdk.nio.maxCachedBufferSize=1048576
- -Dlogger.file=/opt/kafkamanager/etc/logback.xml
- -Dpidfile.path=/dev/null
- -J-server
- -J-Xms256m
- -J-Xmx256m
- -J-Xss256k
- -J-XX:CompressedClassSpaceSize=16m
- -J-XX:ConcGCThreads=2
- -J-XX:+ExitOnOutOfMemoryError
- -J-XX:MaxDirectMemorySize=1m
- -J-XX:MinMetaspaceFreeRatio=50
- -J-XX:MaxMetaspaceFreeRatio=80
- -J-XX:MaxMetaspaceSize=108m
- -J-XX:ParallelGCThreads=2
- -J-XX:ReservedCodeCacheSize=16m
- -J-XX:+UseG1GC
- -J-XX:+UseStringDeduplication
# begin JMX
- -Dcom.sun.management.jmxremote
- -Dcom.sun.management.jmxremote.authenticate=false
- -Dcom.sun.management.jmxremote.ssl=false
- -Dcom.sun.management.jmxremote.local.only=false
- -Dcom.sun.management.jmxremote.port=9999
- -Dcom.sun.management.jmxremote.rmi.port=9999
- -Djava.rmi.server.hostname=127.0.0.1
# end JMX
```

We see a sharp rise in G1 Survivor usage until the heap is full. Most likely a "cache" is not implemented correctly.

**Comment by patelh** [comment]
Hi all, there is an inmemory cache for offset storage.  You can control it via cluster config by setting these two values:

```
kafkaManagedOffsetGroupCacheSize
kafkaManagedOffsetGroupExpireDays
```

Reduce the above two values to reduce memory consumption.

**Comment by patelh** [comment]
We could add off heap on disk with LRU cache to reduce memory consumption if there is enough demand.

**Comment by jonbuffington** [comment]
@patelh Thanks for the reply. We set these two values to:

`kafkaManagedOffsetGroupCacheSize = 10000` (the smallest allowed size)
`kafkaManagedOffsetGroupExpireDays = 1` (the memory leak manifests with 10 mins)

and the leak is unaffected. The larger, default values worked without leaks in v2.0.0.2.

**Comment by patelh** [comment]
That is odd, there is no other cache we use.  Let me look at the kafka 2.4.0 upgrade changes in case i missed something.

**Comment by patelh** [comment]
@jonbuffington Looks like it is caused by kafka consumer in 2.4.0, will need to see how to disable this.
![Screenshot from 2020-03-02 21-53-17](https://user-images.githubusercontent.com/297178/75746897-71c65e00-5cd0-11ea-9565-ceb350c93316.png)

**Comment by patelh** [comment]
@jonbuffington try 3.0.0.4

**Comment by patelh** [comment]
@jonbuffington please try 3.0.0.4

**Comment by jonbuffington** [comment]
@patelh Nice fix! So far we are not seeing the rate of growth we did with 3.0.0.2. I will report back tomorrow after it has run for a day.

**Comment by patelh** [comment]
@jonbuffington let us know if this resolved the leak when you get a chance. ty!

**Comment by jonbuffington** [comment]
@patelh Success! The large increases in heap growth is resolved.

We are looking into a smaller 5MB/hour container memory growth. This smaller growth occurs even when no clusters are configured. Unfortunately, I am not yet familiar with configuring the deployment of a Play framework app.

**Comment by jonbuffington** [comment]
We have had stable k8s container memory usage after applying the following settings:

```
- -Djdk.nio.maxCachedBufferSize=1048576
- -Dlogger.file=/opt/kafkamanager/etc/logback.xml
- -Dpidfile.path=/dev/null
- -J-server
- -J-Xss256k
- -J-XX:CompressedClassSpaceSize=16m
- -J-XX:+ExitOnOutOfMemoryError
- -J-XX:MaxDirectMemorySize=16m
- -J-XX:MaxMetaspaceSize=108m
- -J-XX:MaxRAMPercentage=70
- -J-XX:+PerfDisableSharedMem
- -J-XX:ReservedCodeCacheSize=16m
- -J-XX:-UseBiasedLocking
- -J-XX:+UseStringDeduplication
# begin JMX
- -Dcom.sun.management.jmxremote
- -Dcom.sun.management.jmxremote.authenticate=false
- -Dcom.sun.management.jmxremote.ssl=false
- -Dcom.sun.management.jmxremote.local.only=false
- -Dcom.sun.management.jmxremote.port=9999
- -Dcom.sun.management.jmxremote.rmi.port=9999
- -Djava.rmi.server.hostname=127.0.0.1
# end JMX
```

Note: The above settings require JVM 10+. We are running using JDK 11. The helpful setting was `XX:MaxRAMPercentage` rather than setting heap directly.
