### ISSUE TITLE
Incorrect log when exceptions occur in KafkaStateActor for method KafkaTopicOffsetGetter() 

### ISSUE THREAD

**Issue by mrkjellqvist** [yahoo/kafka-manager#471]
When exceptions occur in KafkaStateActor for method KafkaTopicOffsetGetter() 

You will get:
[error] k.m.a.c.KafkaStateActor - KafkaTopicOffsetGetter exception |  WARNING arguments left: 1

The code is in the class:
https://github.com/yahoo/kafka-manager/blob/master/app/kafka/manager/actor/cluster/KafkaStateActor.scala

....
```
} catch {
        case e: Exception =>
          log.error("KafkaTopicOffsetGetter exception | ", e)
}
```

The log statement should have the exception as first argument:
`log.error(e, "KafkaTopicOffsetGetter exception | ")`

**Comment by DavidLiuXh** [comment]
Commit pull request [https://github.com/yahoo/kafka-manager/pull/473](url)

**Comment by thammuio** [comment]
I have changed it in My code and now I am getting the following error:
i am using Kafka 0.10.2.0 with SASL_SSL. I am able to see all the details except offsets for each topic. Do you have any pointers on this issue?

> [error] k.m.a.c.KafkaStateActor - KafkaTopicOffsetGetter exception |
> java.util.NoSuchElementException: key not found: PLAINTEXT
>         at scala.collection.MapLike$class.default(MapLike.scala:228) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>         at scala.collection.AbstractMap.default(Map.scala:59) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>         at scala.collection.MapLike$class.apply(MapLike.scala:141) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>         at scala.collection.AbstractMap.apply(Map.scala:59) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>         at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7$$anonfun$apply$11$$anonfun$apply$mcV$sp$14.apply(KafkaStateActor.scala:1389) ~[kafka-manager.kafka-manager-1.3.3.16-sans-externalized.jar:na]
>         at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7$$anonfun$apply$11$$anonfun$apply$mcV$sp$14.apply(KafkaStateActor.scala:1383) ~[kafka-manager.kafka-manager-1.3.3.16-sans-externalized.jar:na]
>         at scala.collection.Iterator$class.foreach(Iterator.scala:893) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>         at scala.collection.AbstractIterator.foreach(Iterator.scala:1336) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>         at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:174) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>         at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7$$anonfun$apply$11.apply$mcV$sp(KafkaStateActor.scala:1383) ~[kafka-manager.kafka-manager-1.3.3.16-sans-externalized.jar:na]
>

**Comment by DavidLiuXh** [comment]
@thammuio  Can you help me test it? Thanks~

1389 line :  
val port: Int = broker.endpoints(PLAINTEXT) -> val port : Int = broker.endpoints(config.clusterContext.config.securityProtocol)

**Comment by Gavin-An** [comment]
@mrkjellqvist @DavidLiuXh  I am also getting the same error.  Can you please share the solution to it?  I am running kafka-manager-1.3.3.18 on docker, my Kafka cluster is running SASL_SSL.  Everything seems to be working ok except not getting offset and leadersize for partition of topic.  I am seeing following errors on the log.  Your help is much appreciated.

Regards

Gavin An

[error] k.m.a.c.KafkaStateActor - KafkaTopicOffsetGetter exception 
java.util.NoSuchElementException: key not found: PLAINTEXT
	at scala.collection.MapLike$class.default(MapLike.scala:228) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at scala.collection.AbstractMap.default(Map.scala:59) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at scala.collection.MapLike$class.apply(MapLike.scala:141) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at scala.collection.AbstractMap.apply(Map.scala:59) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7$$anonfun$apply$10$$anonfun$apply$mcV$sp$14.apply(KafkaStateActor.scala:1456) ~[kafka-manager.kafka-manager-1.3.3.18-sans-externalized.jar:na]
	at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7$$anonfun$apply$10$$anonfun$apply$mcV$sp$14.apply(KafkaStateActor.scala:1450) ~[kafka-manager.kafka-manager-1.3.3.18-sans-externalized.jar:na]
	at scala.collection.Iterator$class.foreach(Iterator.scala:891) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:174) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7$$anonfun$apply$10.apply$mcV$sp(KafkaStateActor.scala:1450) ~[kafka-manager.kafka-manager-1.3.3.18-sans-externalized.jar:na]

**Comment by mrkjellqvist** [comment]
This is probably fixed in 1.3.3.21 (not yet a tagged released but the latest commit? in master.)
See https://github.com/yahoo/kafka-manager/pull/532
