### ISSUE TITLE
java.util.NoSuchElementException: key not found: PLAINTEXT

### ISSUE THREAD

**Issue by thammuio** [yahoo/kafka-manager#479]
I am using JDK8, Kafka 0.10.2.0 with SASL_SSL only. Any pointers on this issue?

Can not get the Latest Offset and Leader Size for each topic
Consumers can not get LogSize and lag

I have updated the code to throw correct error from this thread
[https://github.com/yahoo/kafka-manager/issues/471](https://github.com/yahoo/kafka-manager/issues/471)

**Comment by thammuio** [comment]
![untitled](https://user-images.githubusercontent.com/6325610/37122227-539daa56-2225-11e8-816c-a86db676ef4e.jpg)

**Comment by DavidLiuXh** [comment]
@thammuio Can you help me test it? Thanks~

1389 line :
val port: Int = broker.endpoints(PLAINTEXT) -> val port : Int = broker.endpoints(config.clusterContext.config.securityProtocol)

**Comment by thammuio** [comment]
@DavidLiuXh Thanks for the reply. I have tried that and it did not work. In fact I have also tried replacing PLAINTEXT to SASL_SSL since i'm using only that protocol. There seems to be more code needs to be changed to make it work with only SASL_SSL.

**Comment by DavidLiuXh** [comment]
@thammuio show your error log. Thanks~

**Comment by thammuio** [comment]
I have masked the IP and FQDN's...

[info] o.a.z.ZooKeeper - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
[info] o.a.z.ZooKeeper - Client environment:java.io.tmpdir=/tmp
[info] o.a.z.ZooKeeper - Client environment:java.compiler=<NA>
[info] o.a.z.ZooKeeper - Client environment:os.name=Linux
[info] o.a.z.ZooKeeper - Client environment:os.arch=amd64
[info] o.a.z.ZooKeeper - Client environment:os.version=3.10.0-693.2.2.el7.x86_64
[info] o.a.z.ZooKeeper - Client environment:user.name=thammuio
[info] o.a.z.ZooKeeper - Client environment:user.home=/home/thammuio
[info] o.a.z.ZooKeeper - Client environment:user.dir=/home/thammuio/kafka-manager/kafka-manager-1.3.3.16
[info] o.a.z.ZooKeeper - Initiating client connection, connectString=vhostname0002.node-fqdn:2181,vhostname0001.node-fqdn:2181,vhostname0003.node-fqdn:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@63176515
[info] k.m.a.KafkaManagerActor - zk=vhostname0002.node-fqdn:2181,vhostname0001.node-fqdn:2181,vhostname0003.node-fqdn:2181
[info] k.m.a.KafkaManagerActor - baseZkPath=/kafka-manager
[info] o.a.z.Login - successfully logged in.
[info] o.a.z.Login - TGT refresh thread started.
[info] o.a.z.c.ZooKeeperSaslClient - Client will use GSSAPI as SASL mechanism.
[info] o.a.z.ClientCnxn - Opening socket connection to server vhostname0002.node-fqdn/x.x.x.5:2181. Will attempt to SASL-authenticate using Login Context section 'Client'
[info] o.a.z.Login - TGT valid starting at:        Mon Mar 12 17:16:20 UTC 2018
[info] o.a.z.Login - TGT expires:                  Tue Mar 13 03:16:20 UTC 2018
[info] o.a.z.Login - TGT refresh sleeping until: Tue Mar 13 01:23:03 UTC 2018
[info] o.a.z.ClientCnxn - Socket connection established to vhostname0002.node-fqdn/x.x.x.5:2181, initiating session
[info] o.a.z.ClientCnxn - Session establishment complete on server vhostname0002.node-fqdn/x.x.x.5:2181, sessionid = 0x261fd4c2f980024, negotiated timeout = 60000
[info] k.m.a.KafkaManagerActor - Started actor akka://kafka-manager-system/user/kafka-manager
[info] k.m.a.DeleteClusterActor - Started actor akka://kafka-manager-system/user/kafka-manager/delete-cluster
[info] k.m.a.DeleteClusterActor - Starting delete clusters path cache...
[info] k.m.a.KafkaManagerActor - Starting delete clusters path cache...
[info] k.m.a.KafkaManagerActor - Starting kafka manager path cache...
[info] k.m.a.DeleteClusterActor - Adding kafka manager path cache listener...
[info] k.m.a.DeleteClusterActor - Scheduling updater for 10 seconds
[info] k.m.a.KafkaManagerActor - Adding kafka manager path cache listener...
[info] play.api.Play - Application started (Prod)
[info] p.c.s.NettyServer - Listening for HTTP on /0.0.0.0:8080
[info] k.m.a.KafkaManagerActor - Updating internal state...
[info] k.m.a.KafkaManagerActor - Adding new cluster manager for cluster : DEV
[warn] o.a.c.r.ExponentialBackoffRetry - maxRetries too large (100). Pinning to 29
[info] k.m.a.c.ClusterManagerActor - Starting curator...
[info] o.a.z.ZooKeeper - Initiating client connection, connectString=vhostname0002.node-fqdn:2181,vhostname0001.node-fqdn:2181,vhostname0003.node-fqdn:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@769019a3
[info] o.a.z.c.ZooKeeperSaslClient - Client will use GSSAPI as SASL mechanism.
[info] o.a.z.ClientCnxn - Opening socket connection to server vhostname0002.node-fqdn/x.x.x.5:2181. Will attempt to SASL-authenticate using Login Context section 'Client'
[info] o.a.z.ClientCnxn - Socket connection established to vhostname0002.node-fqdn/x.x.x.5:2181, initiating session
[warn] o.a.c.r.ExponentialBackoffRetry - maxRetries too large (100). Pinning to 29
[info] k.m.a.c.ClusterManagerActor - Starting shared curator...
[info] o.a.z.ZooKeeper - Initiating client connection, connectString=vhostname0002.node-fqdn:2181,vhostname0001.node-fqdn:2181,vhostname0003.node-fqdn:2181/kafka sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@2772a03
[info] o.a.z.ClientCnxn - Session establishment complete on server vhostname0002.node-fqdn/x.x.x.5:2181, sessionid = 0x261fd4c2f980025, negotiated timeout = 60000
[info] o.a.z.c.ZooKeeperSaslClient - Client will use GSSAPI as SASL mechanism.
[info] o.a.z.ClientCnxn - Opening socket connection to server vhostname0003.node-fqdn/x.x.x.6:2181. Will attempt to SASL-authenticate using Login Context section 'Client'
[info] o.a.z.ClientCnxn - Socket connection established to vhostname0003.node-fqdn/x.x.x.6:2181, initiating session
[info] o.a.z.ClientCnxn - Session establishment complete on server vhostname0003.node-fqdn/x.x.x.6:2181, sessionid = 0x361fd4c2f8e002c, negotiated timeout = 60000
[info] k.m.a.c.KafkaAdminClientActor - KafkaAdminClientActorConfig(ClusterContext(ClusterFeatures(Set(KMJMXMetricsFeature, KMDisplaySizeFeature, KMDeleteTopicFeature, KMPollConsumersFeature)),ClusterConfig(DEV,CuratorConfig(vhostname0002.node-fqdn:2181,vhostname0001.node-fqdn:2181,vhostname0003.node-fqdn:2181/kafka,100,100,1000),true,0.10.2.0,true,None,None,false,true,false,false,true,true,Some(ClusterTuning(Some(30),Some(2),Some(100),Some(2),Some(100),Some(2),Some(100),Some(30),Some(5),Some(8),Some(1000),Some(8),Some(1000),Some(8),Some(1000))),SASL_SSL)),LongRunningPoolConfig(8,1000),akka://kafka-manager-system/user/kafka-manager/DEV/kafka-state,None)
[info] k.m.a.c.KafkaCommandActor - Started actor akka://kafka-manager-system/user/kafka-manager/DEV/kafka-command
[info] k.m.a.c.BrokerViewCacheActor - Started actor akka://kafka-manager-system/user/kafka-manager/DEV/broker-view
[info] k.m.a.c.BrokerViewCacheActor - Scheduling updater for 30 seconds
[info] k.m.a.c.ClusterManagerActor - Started actor akka://kafka-manager-system/user/kafka-manager/DEV
[info] k.m.a.c.ClusterManagerActor - Starting cluster manager topics path cache...
[info] k.m.a.c.BrokerViewCacheActor - Updating broker view...
[info] k.m.a.c.KafkaStateActor - KafkaStateActorConfig(org.apache.curator.framework.imps.CuratorFrameworkImpl@75f14743,pinned-dispatcher,ClusterContext(ClusterFeatures(Set(KMJMXMetricsFeature, KMDisplaySizeFeature, KMDeleteTopicFeature, KMPollConsumersFeature)),ClusterConfig(DEV,CuratorConfig(vhostname0002.node-fqdn:2181,vhostname0001.node-fqdn:2181,vhostname0003.node-fqdn:2181/kafka,100,100,1000),true,0.10.2.0,true,None,None,false,true,false,false,true,true,Some(ClusterTuning(Some(30),Some(2),Some(100),Some(2),Some(100),Some(2),Some(100),Some(30),Some(5),Some(8),Some(1000),Some(8),Some(1000),Some(8),Some(1000))),SASL_SSL)),LongRunningPoolConfig(8,1000),LongRunningPoolConfig(8,1000),5,10000,None)
[info] k.m.a.c.KafkaStateActor - Started actor akka://kafka-manager-system/user/kafka-manager/DEV/kafka-state
[info] k.m.a.c.KafkaStateActor - Starting topics tree cache...
[info] k.m.a.c.KafkaStateActor - Starting topics config path cache...
[info] k.m.a.c.KafkaStateActor - Starting brokers path cache...
[info] k.m.a.c.KafkaStateActor - Starting admin path cache...
[info] k.m.a.c.KafkaStateActor - Starting delete topics path cache...
[info] k.m.a.c.KafkaStateActor - Adding topics tree cache listener...
[info] k.m.a.c.KafkaStateActor - Adding admin path cache listener...
[info] k.m.a.c.KafkaStateActor - Starting offset cache...
[info] k.m.a.c.OffsetCacheActive - Starting kafka managed offset cache ...
[info] k.m.a.c.OffsetCacheActive - Starting consumers tree cache...
[info] k.m.a.c.OffsetCacheActive - Adding consumers tree cache listener...
[info] k.m.a.c.KafkaStateActor - Starting kafka managed Topic Offset Getter ...
[info] k.m.a.c.KafkaManagedOffsetCache - Constructing new kafka consumer client using these properties:
[info] k.m.a.c.KafkaManagedOffsetCache - key.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
[info] k.m.a.c.KafkaManagedOffsetCache - auto.offset.reset=latest
[info] k.m.a.c.KafkaManagedOffsetCache - bootstrap.servers=vhostname0001.node-fqdn:6668,vhostname0002.node-fqdn:6668,vhostname0003.node-fqdn:6668,vhostname0004.node-fqdn:6668,vhostname0005.node-fqdn:6668
[info] k.m.a.c.KafkaManagedOffsetCache - enable.auto.commit=false
[info] k.m.a.c.KafkaManagedOffsetCache - group.id=KMOffsetCache-vhostname0001.node-fqdn
[info] k.m.a.c.KafkaManagedOffsetCache - value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
[info] k.m.a.c.KafkaManagedOffsetCache - exclude.internal.topics=false
[info] k.m.a.c.KafkaManagedOffsetCache - security.protocol=SASL_SSL
[info] k.m.a.c.KafkaManagedOffsetCache - Consumer created for kafka offset topic consumption for cluster DEV
[error] k.m.a.c.KafkaStateActor - KafkaTopicOffsetGetter exception |
java.io.EOFException: null
        at org.apache.kafka.common.network.NetworkReceive.readFromReadableChannel(NetworkReceive.java:99) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na]
        at kafka.network.BlockingChannel.readCompletely(BlockingChannel.scala:129) ~[org.apache.kafka.kafka_2.11-0.10.0.1.jar:na]
        at kafka.network.BlockingChannel.receive(BlockingChannel.scala:120) ~[org.apache.kafka.kafka_2.11-0.10.0.1.jar:na]
        at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:99) ~[org.apache.kafka.kafka_2.11-0.10.0.1.jar:na]
        at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:83) ~[org.apache.kafka.kafka_2.11-0.10.0.1.jar:na]
        at kafka.consumer.SimpleConsumer.getOffsetsBefore(SimpleConsumer.scala:149) ~[org.apache.kafka.kafka_2.11-0.10.0.1.jar:na]
        at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7$$anonfun$apply$11$$anonfun$apply$mcV$sp$14.apply(KafkaStateActor.scala:1393) ~[kafka-manager.kafka-manager-1.3.3.16-sans-externalized.jar:na]
        at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7$$anonfun$apply$11$$anonfun$apply$mcV$sp$14.apply(KafkaStateActor.scala:1383) ~[kafka-manager.kafka-manager-1.3.3.16-sans-externalized.jar:na]
        at scala.collection.Iterator$class.foreach(Iterator.scala:893) ~[org.scala-lang.scala-library-2.11.8.jar:na]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336) ~[org.scala-lang.scala-library-2.11.8.jar:na]
[error] k.m.a.c.KafkaStateActor - KafkaTopicOffsetGetter exception |
java.io.EOFException: null
        at org.apache.kafka.common.network.NetworkReceive.readFromReadableChannel(NetworkReceive.java:99) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na]
        at kafka.network.BlockingChannel.readCompletely(BlockingChannel.scala:129) ~[org.apache.kafka.kafka_2.11-0.10.0.1.jar:na]
        at kafka.network.BlockingChannel.receive(BlockingChannel.scala:120) ~[org.apache.kafka.kafka_2.11-0.10.0.1.jar:na]
        at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:99) ~[org.apache.kafka.kafka_2.11-0.10.0.1.jar:na]
        at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:83) ~[org.apache.kafka.kafka_2.11-0.10.0.1.jar:na]
        at kafka.consumer.SimpleConsumer.getOffsetsBefore(SimpleConsumer.scala:149) ~[org.apache.kafka.kafka_2.11-0.10.0.1.jar:na]
        at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7$$anonfun$apply$11$$anonfun$apply$mcV$sp$14.apply(KafkaStateActor.scala:1393) ~[kafka-manager.kafka-manager-1.3.3.16-sans-externalized.jar:na]
        at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7$$anonfun$apply$11$$anonfun$apply$mcV$sp$14.apply(KafkaStateActor.scala:1383) ~[kafka-manager.kafka-manager-1.3.3.16-sans-externalized.jar:na]
        at scala.collection.Iterator$class.foreach(Iterator.scala:893) ~[org.scala-lang.scala-library-2.11.8.jar:na]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336) ~[org.scala-lang.scala-library-2.11.8.jar:na]
[info] k.m.a.KafkaManagerActor - Updating internal state...
[error] k.m.a.c.KafkaStateActor - KafkaTopicOffsetGetter exception |
java.io.EOFException: null
        at org.apache.kafka.common.network.NetworkReceive.readFromReadableChannel(NetworkReceive.java:99) ~[org.apache.kafka.kafka-clients-0.10.0.1.jar:na]
        at kafka.network.BlockingChannel.readCompletely(BlockingChannel.scala:129) ~[org.apache.kafka.kafka_2.11-0.10.0.1.jar:na]
        at kafka.network.BlockingChannel.receive(BlockingChannel.scala:120) ~[org.apache.kafka.kafka_2.11-0.10.0.1.jar:na]
        at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:99) ~[org.apache.kafka.kafka_2.11-0.10.0.1.jar:na]
        at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:83) ~[org.apache.kafka.kafka_2.11-0.10.0.1.jar:na]
        at kafka.consumer.SimpleConsumer.getOffsetsBefore(SimpleConsumer.scala:149) ~[org.apache.kafka.kafka_2.11-0.10.0.1.jar:na]
        at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7$$anonfun$apply$11$$anonfun$apply$mcV$sp$14.apply(KafkaStateActor.scala:1393) ~[kafka-manager.kafka-manager-1.3.3.16-sans-externalized.jar:na]
        at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7$$anonfun$apply$11$$anonfun$apply$mcV$sp$14.apply(KafkaStateActor.scala:1383) ~[kafka-manager.kafka-manager-1.3.3.16-sans-externalized.jar:na]
        at scala.collection.Iterator$class.foreach(Iterator.scala:893) ~[org.scala-lang.scala-library-2.11.8.jar:na]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336) ~[org.scala-lang.scala-library-2.11.8.jar:na]

**Comment by wadhwasam** [comment]
I am facing the same issue, how can we fix it?

**Comment by thammuio** [comment]
I was trying to develop this.. let you know if I have luck.

**Comment by tyutlt** [comment]
@thammuio Have you fixed it?

**Comment by lllewellyn** [comment]
I commented on #495 with some possibly useful info; saw that issue before this one.

**Comment by thammuio** [comment]
Thank you @kingmorning. can I plls the master to have these changes ?

**Comment by kingmorning** [comment]
I tested it , This issue has been fix on the master branch. version:1.3.3.21

**Comment by jia2** [comment]
Hi kingmorning,
is the version 1.3.3.21 already released? I could not find it under release [https://github.com/yahoo/kafka-manager/releases](https://github.com/yahoo/kafka-manager/releases).

Thanks
Dingjun

**Comment by jsargiot** [comment]
> Can anyone advise where I can download version: 1.3.3.21

@Gavin-An It's currently the HEAD of `master` (commit: 63c5804a8dc896840a557f781813d322481cda91).

**Comment by Gavin-An** [comment]
@jsargiot Thanks a lot for the information.  I am new about it.  I will try and see if I can build a new docker image with it.  Cheers

**Comment by jsargiot** [comment]
@Gavin-An If you are building a docker image check: https://github.com/hleb-albau/kafka-manager-docker

You can use `KAFKA_MANAGER_VERSION=master` here: https://github.com/hleb-albau/kafka-manager-docker/blob/master/Dockerfile#L5

**Comment by Gavin-An** [comment]
@jsargiot Thanks for the suggestion.  I tried to build a docker image using the sheepkiller Dockerfile yesterday.  Looks like that Kafka-manager-1.3.3.21 fixed the issue.  I am going to do more tests on it in next few days and advise.  Have a good weekend.   Cheers Gavin

**Comment by thammuio** [comment]
I built the version 1.3.3.21, but i am still getting below error.. and not able to see the latest offset... am I missing Something here....


[info] k.m.a.c.KafkaStateActor - SASL Mechanism =SASL_MECHANISM_GSSAPI
[info] k.m.a.c.KafkaStateActor - SASL JAAS config=/home/admin-user/km-properties/jaas.conf
[error] k.m.a.c.KafkaStateActor - consumerProperties:{sasl.mechanism=GSSAPI, bootstrap.servers=kafka.server.com:6668, group.id=kafka-manager-flow, ssl.truststore.location=/security/tls/truststore/truststore.jks, ssl.truststore.password=PASS, sasl.kerberos.service.name=kafka, sasl.jaas.config=/home/admin-user/km-properties/jaas.conf, security.protocol=SASL_SSL} WARNING arguments left: 1
[error] k.m.a.c.KafkaStateActor - KafkaTopicOffsetGetter exception
org.apache.kafka.common.config.ConfigException: Missing required configuration "key.deserializer" which has no default value.
        at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:472) ~[org.apache.kafka.kafka-clients-1.1.0.jar:na]
        at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:462) ~[org.apache.kafka.kafka-clients-1.1.0.jar:na]
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62) ~[org.apache.kafka.kafka-clients-1.1.0.jar:na]
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:75) ~[org.apache.kafka.kafka-clients-1.1.0.jar:na]
        at org.apache.kafka.clients.consumer.ConsumerConfig.<init>(ConsumerConfig.java:485) ~[org.apache.kafka.kafka-clients-1.1.0.jar:na]
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:644) ~[org.apache.kafka.kafka-clients-1.1.0.jar:na]
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:624) ~[org.apache.kafka.kafka-clients-1.1.0.jar:na]
        at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7$$anonfun$apply$10$$anonfun$apply$mcV$sp$14.apply(KafkaStateActor.scala:1490) ~[kafka-manager.kafka-manager-1.3.3.21-sans-externalized.jar:na]
        at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7$$anonfun$apply$10$$anonfun$apply$mcV$sp$14.apply(KafkaStateActor.scala:1468) ~[kafka-manager.kafka-manager-1.3.3.21-sans-externalized.jar:na]
        at scala.collection.Iterator$class.foreach(Iterator.scala:891) ~[org.scala-lang.scala-library-2.11.12.jar:na]
[info] k.m.a.KafkaManagerActor - Updating internal state...



![image](https://user-images.githubusercontent.com/6325610/44301167-f2349200-a2d7-11e8-8297-e6b9c004d931.png)

**Comment by thammuio** [comment]
@Gavin-An  Yes I did have -Djava.security.auth.login.config property while starting the process. Not sure what else is missing here.

**Comment by sangcheolroh** [comment]
@thammuio 
i had same issue. 
But after updating security configuration of cluster on web-ui like below, it works to me.
![image](https://user-images.githubusercontent.com/558661/45333489-73b6d180-b5b1-11e8-83da-879beaa87fa2.png)

**Comment by thammuio** [comment]
@sangcheolroh  Great. It is working for me now.. Thanks...

**Comment by thammuio** [comment]
Closing this issue.. as it is resolved for me now...

**Comment by bthodla** [comment]
I am having a hard time configuring Kafka Manager to work with my Kafka Cluster which is encrypted using SASL and authenticated using SASL_PLAIN.

Here is my setup:
# kafka_manager_jaas.conf
Client {
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="username"
        password="password";
};

# consumer.properties
security.protocol=SASL_PLAINTEXT
sasl.mechanism=PLAIN
ssl.truststore.location=<path2_truststore>
ssl.truststore.password=<password>
z
When I run the Kafka Manger, everything goes through fine including connection to ZK but I get the following error:

java.util.NoSuchElementException: key not found: PLAINTEXT

Does the "basicAuthentication.enabled=false" in the "application.conf" relate to authentication to access the Kafka Manager web UI?

I would appreciate any help to fix this issue. I am running 1.3.3.21 version of Kafka Manager.
