### ISSUE TITLE
Kafka manager does not handle tombstones in consumer offsets topic

### ISSUE THREAD

**Issue by csueiras** [yahoo/kafka-manager#494]
Kafka manager appears to not be handling tombstones in the offsets topic. Whenever a tombstone is seen by the KafkaManagedOffsetCache it causes an NullPointerException.

The offending line appears to be in app/kafka/manager/actor/cluster/KafkaStateActor.scala, specifically:
`val value: OffsetAndMetadata = readOffsetMessageValue(ByteBuffer.wrap(record.value()))`

This code is not handling tombstones which come in the form of a message with a null value. I'm not proficient enough in Scala or this codebase, but with some guidance I would be happy to donate a pull request that handles this issue.

The side effects of these NPEs appear to only be WARN logs generated with the NPE stack trace, however we are also observing some issues in Kafka Manager that seem to correlate with the times when we see these NPEs such as certain consumer groups having their offsets displayed as "-1" for various partitions. We haven't quite root caused that, but we can confirm that the issue appears to be exclusive to Kafka Manager as using the consumer offsets tool in Kafka displays valid offset values whenever this occurs.

Version of Kafka we are using is 1.0.1.

The stack trace:

```
java.lang.NullPointerException: null
	at java.nio.ByteBuffer.wrap(ByteBuffer.java:396) ~[na:1.8.0_131]
	at kafka.manager.actor.cluster.KafkaManagedOffsetCache$$anonfun$run$3.apply(KafkaStateActor.scala:293) [kafka-manager.kafka-manager-1.3.3.7-sans-externalized.jar:na]
	at kafka.manager.actor.cluster.KafkaManagedOffsetCache$$anonfun$run$3.apply(KafkaStateActor.scala:243) [kafka-manager.kafka-manager-1.3.3.7-sans-externalized.jar:na]
	at scala.util.Success.foreach(Try.scala:236) [org.scala-lang.scala-library-2.11.8.jar:na]
	at kafka.manager.actor.cluster.KafkaManagedOffsetCache.run(KafkaStateActor.scala:243) [kafka-manager.kafka-manager-1.3.3.7-sans-externalized.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```

Edit: I see two issues referencing this same problem, I'll leave my issue open since it has a little bit more details.

**Comment by patelh** [comment]
Can you let us know if u still see this issue with version 1.3.3.18
