### ISSUE TITLE
No Data available for consumer

### ISSUE THREAD

**Issue by wadhwasam** [yahoo/kafka-manager#496]
I have kafka cluster with SSL enabled.  I just configured Kafka manager which is able to do see all topics etc but I am not seeing anything under consumer tab.  No data available for consumer.  Let me know how Kafka manager can see all the consumer information.

Thanks,
Sam

**Comment by myusuf3** [comment]
I am having the same issue and was hoping if you found something, are you using Sarama as well?

**Comment by patelh** [comment]
You need to configure SSL in the consumer properties file and for SASL you need to pass in jaas conf.  We have SSL and SASL working with our KM and clusters.  It's all a matter of configuration.

**Comment by ceeeekay** [comment]
@patelh , this isn't a very helpful response to close an issue on.

You're basically saying "it works for me", and "you just need to configure things correctly".

**Comment by patelh** [comment]
It's the same config you are using to get other kafka consumers working, just put it in the consumer properties file.  Check kafka documentation under "Configuring Kafka Consumers" for SSL security: http://kafka.apache.org/documentation/#security_ssl

**Comment by patelh** [comment]
http://kafka.apache.org/documentation/#security_configclients

**Comment by montana-ua** [comment]
@patelh Could you please point here your kafka manager application.conf and consumer.properties?

I have the following configuration (see below) but it doesn't work for me and seems I'm not a single person who faced the similar issue. Thanks!

My application.conf
```
$ cat conf/application.conf 

# Copyright 2015 Yahoo Inc. Licensed under the Apache License, Version 2.0
# See accompanying LICENSE file.

# This is the main configuration file for the application.
# ~~~~~

# Secret key
# ~~~~~
# The secret key is used to secure cryptographics functions.
# If you deploy your application to several instances be sure to use the same key!
play.crypto.secret="^<csmm5Fx4d=r2HEX8pelM3iBkFVv?k[mc;IZE<_Qoq8EkX_/7@Zt6dP05Pzea3U"
play.crypto.secret=${?APPLICATION_SECRET}

# The application languages
# ~~~~~
play.i18n.langs=["en"]

play.http.requestHandler = "play.http.DefaultHttpRequestHandler"
play.http.context = "/"
play.application.loader=loader.KafkaManagerLoader

kafka-manager.zkhosts="chwxapphot020.datawarehouse.expecn.com:2181,chwxapphot021.datawarehouse.expecn.com:2181,chwxapphot023.datawarehouse.expecn.com:2181"
kafka-manager.zkhosts=${?ZK_HOSTS}
kafka-manager.base-zk-path="/hcom/kafka-manager/edw-kafka_ldp-01"
pinned-dispatcher.type="PinnedDispatcher"
pinned-dispatcher.executor="thread-pool-executor"
application.features=["KMClusterManagerFeature","KMTopicManagerFeature","KMPreferredReplicaElectionFeature","KMReassignPartitionsFeature"]

akka {
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel = "INFO"
}

akka.logger-startup-timeout = 60s

basicAuthentication.enabled=false
basicAuthentication.enabled=${?KAFKA_MANAGER_AUTH_ENABLED}
basicAuthentication.username="admin"
basicAuthentication.username=${?KAFKA_MANAGER_USERNAME}
basicAuthentication.password="password"
basicAuthentication.password=${?KAFKA_MANAGER_PASSWORD}
basicAuthentication.realm="Kafka-Manager"
basicAuthentication.excluded=["/api/health"] # ping the health of your instance without authentification

kafka-manager.consumer.properties.file=/hcom/kafka-manager/edw-kafka_ldp-01/conf/consumer.properties
#kafka-manager.consumer.properties.file=${?CONSUMER_PROPERTIES_FILE}
```

My consumer.properties
```
$ cat conf/consumer.properties 
key.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

################# SSL Section ################################
security.protocol=SSL
ssl.truststore.location=/hcom/share/ssl/edw-kafka_ldp.truststore.jks
ssl.truststore.password=*********
```

Kafka Manager Release - 1.3.3.18

I see the following errors in my application.log
```
2018-07-09 07:11:39,405 - [ERROR] - from kafka.manager.actor.cluster.KafkaStateActor in kafka-manager-system-akka.actor.default-dispatcher-4
KafkaTopicOffsetGetter exception
java.util.NoSuchElementException: key not found: PLAINTEXT
	at scala.collection.MapLike$class.default(MapLike.scala:228) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at scala.collection.AbstractMap.default(Map.scala:59) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at scala.collection.MapLike$class.apply(MapLike.scala:141) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at scala.collection.AbstractMap.apply(Map.scala:59) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7$$anonfun$apply$10$$anonfun$apply$mcV$sp$14.apply(KafkaStateActor.scala:1456) ~[kafka-manager.kafka-manager-1.3.3.18-sans-externalized.jar:na]
	at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7$$anonfun$apply$10$$anonfun$apply$mcV$sp$14.apply(KafkaStateActor.scala:1450) ~[kafka-manager.kafka-manager-1.3.3.18-sans-externalized.jar:na]
	at scala.collection.Iterator$class.foreach(Iterator.scala:891) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:174) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7$$anonfun$apply$10.apply$mcV$sp(KafkaStateActor.scala:1450) ~[kafka-manager.kafka-manager-1.3.3.18-sans-externalized.jar:na]
	at scala.util.control.Breaks.breakable(Breaks.scala:38) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7.apply(KafkaStateActor.scala:1449) ~[kafka-manager.kafka-manager-1.3.3.18-sans-externalized.jar:na]
	at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7.apply(KafkaStateActor.scala:1418) ~[kafka-manager.kafka-manager-1.3.3.18-sans-externalized.jar:na]
	at scala.Option.fold(Option.scala:158) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter.run(KafkaStateActor.scala:1418) ~[kafka-manager.kafka-manager-1.3.3.18-sans-externalized.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_152]
```

I see in the log file that all consumer.properties were successfully loaded
```
2018-07-09 07:03:24,659 - [INFO] - from kafka.manager.actor.cluster.KafkaManagedOffsetCache in KafkaManagedOffsetCache
security.protocol=SSL

2018-07-09 07:03:24,659 - [INFO] - from kafka.manager.actor.cluster.KafkaManagedOffsetCache in KafkaManagedOffsetCache
ssl.truststore.location=/hcom/share/ssl/edw-kafka_ldp.truststore.jks

2018-07-09 07:03:24,659 - [INFO] - from kafka.manager.actor.cluster.KafkaManagedOffsetCache in KafkaManagedOffsetCache
ssl.truststore.password=*************
```

Security protocol was selected SSL in the UI
<img width="818" alt="image" src="https://user-images.githubusercontent.com/16386332/42449904-1c9bc318-838b-11e8-9067-222cda10c17b.png">

I use only encrypted kafka cluster (SASL is not configured). My clients (consumers/producers) can successfully connect to my kafka cluster uses the same truststore and truststore password. Unfortunately the issue appear only on kafka manager.

Please share your experience.
Thanks.

**Comment by montana-ua** [comment]
@Leon-WTF I don't see the issue above anymore. Kafka Manager 1.3.3.19 works as expected with Kafka SSL cluster.

**Comment by Leon-WTF** [comment]
Thanks @montana-ua for your last post, my Kafka Manager works as expected after changing the security protocol in the UI and restart it.

**Comment by YiGene** [comment]
i am still seeing the same issue even with the latest version of kafka-manager 3.22 now.
GUI already update to SSL
consumer.propertities file already configured SSL information.
no errors in the application.log file

**Comment by maojing0609** [comment]
i`m facing the problem.
**application.log is bellow**

2019-06-01 13:04:44,713 - [ERROR] o.a.k.c.NetworkClient - [Consumer clientId=consumer-8, groupId=KMOffsetCache-xxxxxxxxxx] Connection to node -4 (/xxxxxx:9093) failed authentication due to: SSL handshake failed
2019-06-01 13:04:44,713 - [WARN] k.m.a.c.KafkaManagedOffsetCache - Failed to process a message from offset topic on cluster PROD!
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed

**and consumer.properties likes follow**

[root@iZbp1gf15gbzzr0k4e2pyjZ kafka-manager-2.0.0.2]# cat conf/consumer.properties
#security.protocol=PLAINTEXT
#key.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
#value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
key.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
security.protocol=SSL
ssl.truststore.location=/var/private/ssl/kafka/0620/client.truststore.jks
ssl.keystore.location=/var/private/ssl/kafka/0620/client.keystore.jks
ssl.keystore.password=mypassword
ssl.truststore.password=mypassword

the jks works well in my project, but cant works in kafka-manager2.0.0.2

Look forward to your favourable reply

**Comment by cwienands1** [comment]
@maojing0609 Did you set the CONSUMER_PROPERTIES_FILE variable to point to your consumer.properties file? Take a look at KM's application.conf file where you will find the reference to this env var. Alternatively, you can directly specify the consumer properties files in application.conf.
