### ISSUE TITLE
rpmbuild for kafka-manager failing

### ISSUE THREAD

**Issue by puneetsaha** [yahoo/kafka-manager#53]
I am getting following error. Anybody faced the same?If yes, any idea what is to be fixed?

[info] Loading project definition from /Users/pukumar/dev/kafka-manager/kafka-manager-master/project
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* com.typesafe.sbt:sbt-native-packager:0.7.4 -> 1.0.0-M4
[warn] Run 'evicted' to see detailed eviction warnings
[info] Set current project to kafka-manager (in build file:/Users/pukumar/dev/kafka-manager/kafka-manager-master/)
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* org.webjars:jquery:(2.1.1, 1.11.1) -> 2.1.3
[warn] Run 'evicted' to see detailed eviction warnings
[info] Wrote /Users/pukumar/dev/kafka-manager/kafka-manager-master/target/scala-2.11/kafka-manager_2.11-1.2.0.pom
[info] Packaging /Users/pukumar/dev/kafka-manager/kafka-manager-master/target/kafka-manager-1.2.0-assets.jar ...
[info] Done packaging.
[info] Building target platforms: noarch-yahoo-Linux
[info] Executing(%install): /bin/sh -e /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/sbt_44c3e8c6/rpm-tmp.3898
[error] + umask 022
[error] + cd /Users/pukumar/dev/kafka-manager/kafka-manager-master/target/rpm/BUILD
[error] + /bin/rm -rf /Users/pukumar/dev/kafka-manager/kafka-manager-master/target/rpm/buildroot
[error] + /bin/mkdir -p /Users/pukumar/dev/kafka-manager/kafka-manager-master/target/rpm/buildroot
[error] + '[' -e /Users/pukumar/dev/kafka-manager/kafka-manager-master/target/rpm/buildroot ']'
[error] + mv /Users/pukumar/dev/kafka-manager/kafka-manager-master/target/rpm/tmp-buildroot/etc /Users/pukumar/dev/kafka-manager/kafka-manager-master/target/rpm/tmp-buildroot/usr /Users/pukumar/dev/kafka-manager/kafka-manager-master/target/rpm/tmp-buildroot/var /Users/pukumar/dev/kafka-manager/kafka-manager-master/target/rpm/buildroot
[error] + '%{_rpmconfigdir}/brp-compress'
[error] /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/sbt_44c3e8c6/rpm-tmp.3898: line 32: fg: no job control
[error] error: Bad exit status from /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/sbt_44c3e8c6/rpm-tmp.3898 (%install)
[info] 
[info] 
[info] RPM build errors:
[error]     Bad exit status from /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/sbt_44c3e8c6/rpm-tmp.3898 (%install)
java.lang.RuntimeException: Unable to run rpmbuild, check output for details. Errorcode 1
	at scala.sys.package$.error(package.scala:27)
	at com.typesafe.sbt.packager.rpm.RpmHelper$$anonfun$buildPackage$1.apply(RpmHelper.scala:89)
	at com.typesafe.sbt.packager.rpm.RpmHelper$$anonfun$buildPackage$1.apply(RpmHelper.scala:74)
	at sbt.IO$.withTemporaryDirectory(IO.scala:291)
	at com.typesafe.sbt.packager.rpm.RpmHelper$.buildPackage(RpmHelper.scala:74)
	at com.typesafe.sbt.packager.rpm.RpmHelper$.buildRpm(RpmHelper.scala:20)
	at com.typesafe.sbt.packager.rpm.RpmPlugin$$anonfun$projectSettings$31.apply(RpmPlugin.scala:100)
	at com.typesafe.sbt.packager.rpm.RpmPlugin$$anonfun$projectSettings$31.apply(RpmPlugin.scala:98)
	at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:35)
	at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] (rpm:packageBin) Unable to run rpmbuild, check output for details. Errorcode 1
[error] Total time: 2 s, completed Apr 29, 2015 2:51:28 PM

**Comment by petere** [comment]
I have seen this issue with rpm 5, but not with rpm 4. Which version are you using?

**Comment by isaias-b** [comment]
I could reproduce this with:
```
$ rpmbuild --version
rpmbuild (RPM) 5.4.15
```
I will need to check version 4.

However, my stack traces look a little different in comparison to @puneetsaha 's:
```
> rpm:packageBin
[info] Building target platforms: noarch-kaufhof-Linux
[info] Executing(%install): /bin/sh -e /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/sbt_fc5f2fc8/rpm-tmp.8964
[error] + umask 022
[error] + cd /Users/isaias/Projects/pillar2/target/rpm/BUILD
[error] + /bin/rm -rf /Users/isaias/Projects/pillar2/target/rpm/buildroot
[error] + /bin/mkdir -p /Users/isaias/Projects/pillar2/target/rpm/buildroot
[error] + '[' -e /Users/isaias/Projects/pillar2/target/rpm/buildroot ']'
[error] + mv '/Users/isaias/Projects/pillar2/target/rpm/tmp-buildroot/*' /Users/isaias/Projects/pillar2/target/rpm/buildroot
[error] mv: rename /Users/isaias/Projects/pillar2/target/rpm/tmp-buildroot/* to /Users/isaias/Projects/pillar2/target/rpm/buildroot/*: No such file or directory
[error] error: Bad exit status from /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/sbt_fc5f2fc8/rpm-tmp.8964 (%install)
[info]
[info]
[error]     Bad exit status from /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/sbt_fc5f2fc8/rpm-tmp.8964 (%install)
[info] RPM build errors:
java.lang.RuntimeException: Unable to run rpmbuild, check output for details. Errorcode 1
	at scala.sys.package$.error(package.scala:27)
	at com.typesafe.sbt.packager.rpm.RpmHelper$$anonfun$buildPackage$1.apply(RpmHelper.scala:110)
	at com.typesafe.sbt.packager.rpm.RpmHelper$$anonfun$buildPackage$1.apply(RpmHelper.scala:87)
[trace] Stack trace suppressed: run last rpm:packageBin for the full output.
[error] (rpm:packageBin) Unable to run rpmbuild, check output for details. Errorcode 1
[error] Total time: 0 s, completed Jul 5, 2017 7:12:26 PM
> last rpm:packageBin
java.lang.RuntimeException: Unable to run rpmbuild, check output for details. Errorcode 1
	at scala.sys.package$.error(package.scala:27)
	at com.typesafe.sbt.packager.rpm.RpmHelper$$anonfun$buildPackage$1.apply(RpmHelper.scala:110)
	at com.typesafe.sbt.packager.rpm.RpmHelper$$anonfun$buildPackage$1.apply(RpmHelper.scala:87)
	at sbt.IO$.withTemporaryDirectory(IO.scala:358)
	at com.typesafe.sbt.packager.rpm.RpmHelper$.buildPackage(RpmHelper.scala:87)
	at com.typesafe.sbt.packager.rpm.RpmHelper$.buildRpm(RpmHelper.scala:39)
	at com.typesafe.sbt.packager.rpm.RpmPlugin$$anonfun$projectSettings$47.apply(RpmPlugin.scala:158)
	at com.typesafe.sbt.packager.rpm.RpmPlugin$$anonfun$projectSettings$47.apply(RpmPlugin.scala:158)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (rpm:packageBin) Unable to run rpmbuild, check output for details. Errorcode 1
```

I also tried reducing the overall dependencies to generate a rpm enabled minimal working example with this `build.sbt` file:
```
import sbt._
import Keys._

fork in Test := true

val rpmSettings = {
  Seq(
    rpmVendor := "kaufhof",
    rpmUrl := Some("https://github.com/Galeria-Kaufhof/pillar"),
    rpmGroup := Some("Development/Others"),
    linuxPackageMappings in Rpm := linuxPackageMappings.value,
    packageName in Rpm := "de.kaufhof",
    packageDescription in Rpm := """Pillar manages migrations for your Cassandra data stores.""",
//    packageArchitecture in Rpm := "noarch",
    version in Rpm := version.value,
    rpmRelease in Rpm := "1",
    packageSummary in Rpm := "Pillar manages migrations for your Cassandra data stores.",
    rpmLicense := Some("http://www.opensource.org/licenses/mit-license.php")
  )
}

lazy val root = Project(
  id = "pillar",
  base = file("."),
  settings = Defaults.coreDefaultSettings
).settings(
    traceLevel := 0,
    name := "pillar",
    organization := "de.kaufhof",
    version := "4.1.0",
    scalaVersion := "2.12.2"
  )
  .settings(
    parallelExecution in Test := false
  )
  .settings(rpmSettings)
  .enablePlugins(RpmPlugin)

//rpmBrpJavaRepackJars := false
```

I also removed all the code in `src` and replaced it with a HelloWorld application.

Due to the stacktrace given by @puneetsaha  i looked up the sources of [RpmHelper.scala at Line 89](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/rpm/RpmHelper.scala#L89) but the `packageArchitecture := "noarch"` didn't seem to influence the problem.

**Comment by disizjay** [comment]
I have uploaded the build files, RPM and DEB packages. Hope that's useful!
https://github.com/disizjay/kafka-manager
