### ISSUE TITLE
kafka manager stops after some 20-30 days on it's own

### ISSUE THREAD

**Issue by mimani** [yahoo/kafka-manager#550]
Version: 1.3.3.1

We are seeing kafka manager hangs after some 20-30 days of running and we get only following error in the logs:

```

java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable@7e7bb27a rejected from java.util.concurrent.ThreadPoolExecutor@6463050b[Shutting down, pool size = 8, active th
reads = 8, queued tasks = 0, completed tasks = 26387522]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
        at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:109)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
        at scala.concurrent.Promise$class.complete(Promise.scala:55)
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by k3vinwan** [comment]
+1
