### ISSUE TITLE
Failed to connect to service:jmx:rmi: javax.net.ssl.SSLHandshakeException but "JMX with SSL" isn't checked

### ISSUE THREAD

**Issue by zwindler** [yahoo/kafka-manager#552]
Hi,

I'm using kafka manager 1.3.3.18 inside a container in a kubernetes cluster. I'm correctly connected to zookeeper clusters but I'm having trouble configuring JMX to get kafka nodes metrics.

I have configured a few clusters with JMX on port 10030, with no SSL, but for some reason I'm getting an error when trying to establish connection to JMX endpoints.

I checked multiple time, "JMX with SSL" is **not** enabled (checkbox not checked in Kafka manager config).

```
[[31merror[0m] k.m.a.c.BrokerViewCacheActor - Failed to get broker metrics for BrokerIdentity(3,10.100.1.167,10030,true,true,Map(SASL_SSL -> 9092, PLAINTEXT -> 9091))
java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is:
        javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:307) ~[na:1.8.0_171]
        at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202) ~[na:1.8.0_171]
        at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:129) ~[na:1.8.0_171]
        at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:227) ~[na:1.8.0_171]
        at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:179) ~[na:1.8.0_171]
        at com.sun.proxy.$Proxy5.newClient(Unknown Source) ~[na:na]
        at javax.management.remote.rmi.RMIConnector.getConnection(RMIConnector.java:2430) ~[na:1.8.0_171]
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:308) ~[na:1.8.0_171]
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270) ~[na:1.8.0_171]
        at kafka.manager.jmx.KafkaJMX$.doWithConnection(KafkaJMX.scala:57) ~[kafka-manager.kafka-manager-1.3.3.18-sans-externalized.jar:na]
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_171]
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:154) ~[na:1.8.0_171]
        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2038) ~[na:1.8.0_171]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1135) ~[na:1.8.0_171]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385) ~[na:1.8.0_171]
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:757) ~[na:1.8.0_171]
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123) ~[na:1.8.0_171]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[na:1.8.0_171]
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[na:1.8.0_171]
        at java.io.DataOutputStream.flush(DataOutputStream.java:123) ~[na:1.8.0_171]
```

Here are the options I added in my kafka servers

```
-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=10030 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=10.100.1.167
```

At first I had "-Dcom.sun.management.jmxremote.local.only=false" so I guess it's normal that it didn't work, but now, I wonder what I'm doing wrong

**Comment by zwindler** [comment]
Update: a workaround for this issue is to force the use of SSL for JMX... not what I wanted to do in the first place but it works, so why not...

**Comment by yctn** [comment]
i just ran into the same issue. i added -Dcom.sun.management.jmxremote.ssl=false to disable ssl for jmx after that it worked fine. it seems that JMX uses SSL per default
