### ISSUE TITLE
Consuming offsets error (KafkaTopicOffsetGetter exception)

### ISSUE THREAD

**Issue by xmariachi** [yahoo/kafka-manager#553]
I have a cluster from which I used to manage with earlier versions of Kafka-Manager, like a year old or more. Docker repo got outdated, so I changed to a different, up-to-date docker repo, I have tried several ones and all of them are giving me this problem.

I have a remote Kafka cluster, with a separate ZK cluster. 
If I just check "Poll Consumer Information", Kafka Manager will not show consumer offsets info, and printing the following exception repeteadly in the logs. 

```
kafka-manager_1            | [error] k.m.a.c.KafkaStateActor - KafkaTopicOffsetGetter exception 
kafka-manager_1            | java.nio.channels.ClosedChannelException: null
kafka-manager_1            | 	at kafka.network.BlockingChannel.send(BlockingChannel.scala:110) ~[org.apache.kafka.kafka_2.11-0.10.0.1.jar:na]
kafka-manager_1            | 	at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:98) ~[org.apache.kafka.kafka_2.11-0.10.0.1.jar:na]
kafka-manager_1            | 	at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:83) ~[org.apache.kafka.kafka_2.11-0.10.0.1.jar:na]
kafka-manager_1            | 	at kafka.consumer.SimpleConsumer.getOffsetsBefore(SimpleConsumer.scala:149) ~[org.apache.kafka.kafka_2.11-0.10.0.1.jar:na]
kafka-manager_1            | 	at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7$$anonfun$apply$11$$anonfun$apply$mcV$sp$14.apply(KafkaStateActor.scala:1393) ~[kafka-manager.kafka-manager-1.3.3.17-sans-externalized.jar:na]
kafka-manager_1            | 	at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7$$anonfun$apply$11$$anonfun$apply$mcV$sp$14.apply(KafkaStateActor.scala:1383) ~[kafka-manager.kafka-manager-1.3.3.17-sans-externalized.jar:na]
kafka-manager_1            | 	at scala.collection.Iterator$class.foreach(Iterator.scala:893) ~[org.scala-lang.scala-library-2.11.8.jar:na]
kafka-manager_1            | 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336) ~[org.scala-lang.scala-library-2.11.8.jar:na]
kafka-manager_1            | 	at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:174) ~[org.scala-lang.scala-library-2.11.8.jar:na]
kafka-manager_1            | 	at kafka.manager.actor.cluster.KafkaStateActor$KafkaTopicOffsetGetter$$anonfun$run$7$$anonfun$apply$11.apply$mcV$sp(KafkaStateActor.scala:1383) ~[kafka-manager.kafka-manager-1.3.3.17-sans-externalized.jar:na]
```

However if I also check the Active OffsetCache activation(which I usually didn't use before), then it will show offsets, apparently fine and without complaints in the log.

**Comment by cbrucato** [comment]
Hi!

Were you able to resolve this?  I would greatly appreciate a response!

Thank you!

**Comment by xmariachi** [comment]
Hi! I didn't _solve_ it, but AFAIK newer versions (or different docker images) have different behaviour here. You can try using different versions, if this is happening to you. But I can't tell about the cause.

**Comment by cbrucato** [comment]
Appreciate the prompt reply!

Cheers,
