### ISSUE TITLE
./sbt clean list    failed

### ISSUE THREAD

**Issue by mljctt** [yahoo/kafka-manager#556]
[debug] 	report for default#kafka-manager-build;0.1-SNAPSHOT pom produced in /usr/local/kafka-manager/project/target/resolution-cache/reports/default-kafka-manager-build-pom.xml
[debug] 	report for default#kafka-manager-build;0.1-SNAPSHOT scala-tool produced in /usr/local/kafka-manager/project/target/resolution-cache/reports/default-kafka-manager-build-scala-tool.xml
[debug] 	resolve done (17215ms resolve - 89ms download)
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		net.virtual-void:sbt-dependency-graph:0.8.2 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 		org.scoverage:sbt-scoverage:1.3.3 (scalaVersion=2.10, sbtVersion=0.13)
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		net.virtual-void:sbt-dependency-graph:0.8.2 (scalaVersion=2.10, sbtVersion=0.13) (/usr/local/kafka-manager/project/plugins.sbt#L29-30)
[warn] 		  +- default:kafka-manager-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
[warn] 		org.scoverage:sbt-scoverage:1.3.3 (scalaVersion=2.10, sbtVersion=0.13) (/usr/local/kafka-manager/project/plugins.sbt#L38-39)
[warn] 		  +- default:kafka-manager-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
[debug] Forcing garbage collection...
sbt.ResolveException: unresolved dependency: net.virtual-void#sbt-dependency-graph;0.8.2: not found
unresolved dependency: org.scoverage#sbt-scoverage;1.3.3: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:294)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)

**Comment by GlowingRuby** [comment]
I also encountered this problem.Have you solved it?

**Comment by shylinfon** [comment]
I got a similar error, when I run command:  ./sbt clean dist
` module not found: net.virtual-void#sbt-dependency-graph;0.8.2`

I've solved this problem by doing the following:
(1) create file: ~/.sbt/repositories
(2) add the config
`[repositories]
local
aliyun: http://maven.aliyun.com/nexus/content/groups/public
jcenter: http://jcenter.bintray.com/
typesafe: http://repo.typesafe.com/typesafe/ivy-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext], bootOnly
maven-central: http://repo1.maven.org/maven2/
`

**Comment by jocelyndrean** [comment]
Yes. Fixed this issue with 
1. creating a file ~/.sbt/repositories
2. adding :
```
[repositories]
local
aliyun: http://maven.aliyun.com/nexus/content/groups/public/
typesafe: http://repo.typesafe.com/typesafe/ivy-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext], bootOnly
sonatype-oss-releases
maven-central
sonatype-oss-snapshots
```

**Comment by AveiShriety** [comment]
> ```
> [repositories]
> local
> aliyun: http://maven.aliyun.com/nexus/content/groups/public/
> typesafe: http://repo.typesafe.com/typesafe/ivy-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext], bootOnly
> sonatype-oss-releases
> maven-central
> sonatype-oss-snapshots
> ```

Now, it doesn't work. Every site above seems that they don't have the `sbt-dependency-graph-0.8.2` index.. 
Any other help?
