### ISSUE TITLE
kafka-manager Consumers is not display with kafka2.1.0 version

### ISSUE THREAD

**Issue by mailfly** [yahoo/kafka-manager#592]
hi every one ,
i use the latest kafka verson 2.1.0, using the kafka-manager1.3.3.18, the Consumers tab is not display?
any one who encounter this problem ? or how to fixed it ?  the kafak manager not support the latest kafka version ?

**Comment by mailfly** [comment]
[warn] k.m.a.c.KafkaManagedOffsetCache - Failed to process a message from offset topic on cluster InvestMatchDeal-Kafka!
kafka.common.KafkaException: Unknown offset schema version 3
        at kafka.manager.utils.one10.GroupMetadataManager$.schemaForOffset(GroupMetadataManager.scala:428) ~[kafka-manager.kafka-manager-1.3.3.18-sans-externalized.jar:na]
        at kafka.manager.utils.one10.GroupMetadataManager$.readOffsetMessageValue(GroupMetadataManager.scala:532) ~[kafka-manager.kafka-manager-1.3.3.18-sans-externalized.jar:na]
        at kafka.manager.actor.cluster.KafkaManagedOffsetCache$$anonfun$run$4.apply(KafkaStateActor.scala:332) [kafka-manager.kafka-manager-1.3.3.18-sans-externalized.jar:na]
        at kafka.manager.actor.cluster.KafkaManagedOffsetCache$$anonfun$run$4.apply(KafkaStateActor.scala:308) [kafka-manager.kafka-manager-1.3.3.18-sans-externalized.jar:na]
        at scala.util.Success.foreach(Try.scala:236) [org.scala-lang.scala-library-2.11.12.jar:na]
        at kafka.manager.actor.cluster.KafkaManagedOffsetCache.run(KafkaStateActor.scala:308) [kafka-manager.kafka-manager-1.3.3.18-sans-externalized.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]

**Comment by mailfly** [comment]
@brandonpalmer  could you give me the full code of : app/kafka/manager/utils/one10/GroupMetadataManager.scala, 
thanks a lot?
could you send me via mail? my mail is : mailfly@163.com

**Comment by mailfly** [comment]
@brandonpalmer  i using you code ,fixed this problem ,thanks a lot

**Comment by mailfly** [comment]
@brandonpalmer  btw ,i thanks you should commit you code to this project!

**Comment by tianfen** [comment]
I have the same problem. Can you help me? @brandonpalmer 
2019-04-03 03:17:20 ERROR KafkaOffsetGetter$:103 - The message was malformed and does not conform to a type of (BaseKey, OffsetAndMetadata. Ignoring this message.
kafka.common.KafkaException: Unknown offset schema version 3
        at kafka.coordinator.GroupMetadataManager$.schemaForOffset(GroupMetadataManager.scala:739)
        at kafka.coordinator.GroupMetadataManager$.readOffsetMessageValue(GroupMetadataManager.scala:884)
        at com.quantifind.kafka.core.KafkaOffsetGetter$.tryParseOffsetMessage(KafkaOffsetGetter.scala:277)
        at com.quantifind.kafka.core.KafkaOffsetGetter$.startCommittedOffsetListener(KafkaOffsetGetter.scala:351)
        at com.quantifind.kafka.OffsetGetter$$anon$3.run(OffsetGetter.scala:289)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)








my mail is: 1557034472@qq.com
