### ISSUE TITLE
Consumers Page show "No data available in table"

### ISSUE THREAD

**Issue by bcube** [yahoo/kafka-manager#623]
Kafka Version : 2.12-2.1.1
Kafka Manager : 1.3.3.23
OS : Windows 10

I found that the consumer page shows "No data available in table". However, when i run the following commands, i can see the active consumer

`bin/windows/kafka-consumer-groups.bat -bootstrap-server localhost:9092 -describe -group console-consumer-47558`

May I know if there is any setting I could miss? 

Cheers, 
Benny

**Comment by amolfasale** [comment]
+1

**Comment by StBlackwood** [comment]
This is the error being thrown by CMAK when a new consumer is added 
`2020-06-05 02:46:07,035 - [WARN] k.m.a.c.KafkaManagedOffsetCache - Failed to process a message from offset topic on cluster localhost!
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'owned_partitions': java.nio.BufferUnderflowException
	at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:110)
	at org.apache.kafka.clients.consumer.internals.ConsumerProtocol.deserializeSubscriptionV1(ConsumerProtocol.java:190)
	at org.apache.kafka.clients.consumer.internals.ConsumerProtocol.deserializeSubscription(ConsumerProtocol.java:219)
	at kafka.manager.utils.two40.GroupMetadataManager$.$anonfun$readGroupMessageValue$1(GroupMetadataManager.scala:769)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
`
maybe since CMAK consumer from offset topic, due to that failure the available consumers cache might not have been updated
Needs digging into the issue, will update if found anything new

**Comment by poyyi** [comment]
i'm also running exactly into same errors for 'owned_partition' not sure where it is refering it...
cmak..3.0.0.5
kafka version: 2.3.1 (upgraded from 0.11.0.0)

server.properties
inter.broker.protocol.version=2.3-IV1
log.message.format.version=0.11.0-IV2
connecting thru sasl_ssl and plain
Tried multiple kafkaversion from drop down while setting it up with  Addcluster option when i chose 2.3.1(which is kafka version), i get  nothing comes up

**Ask timed out on [ActorSelection[Anchor(akka://kafka-manager-system/), Path(/user/kafka-manager/PROD_SSAF_DADC_v231/kafka-state)]] after [2000 ms]. Message of type [kafka.manager.model.ActorModel$KSGetBrokers$] was sent by [Actor[akka://kafka-manager-system/user/kafka-manager/PROD_SSAF_DADC_v231#-1454503522]]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply.**
 
But with 0.11.0.0  except of consumer lags (Lag unavailable ) everything shows up..
at the start up i see schema exception shown above and repeatedly 
timeout exception 
org.apache.kafka.common.errors.TimeoutException: Failed to get offsets by times in 30000ms
2020-09-15 21:23:52,779 - [ERROR] k.m.a.c.KafkaStateActor - KafkaTopicOffsetGetter exception

Very fustrating and also tried to tweaking acls  to give describe and read access Kmoffsetcache...nothing seems 
Any Help is appreciated...
