### ISSUE TITLE
Enable JMX Polling timeout

### ISSUE THREAD

**Issue by lianfulei** [yahoo/kafka-manager#654]
2019-06-13 14:37:22,205 - [ERROR] k.m.a.c.BrokerViewCacheActor - Failed to get broker metrics for BrokerIdentity(0,vpc-alian-1,9999,true,false,Map(SASL_PLAINTEXT -> 9092))
java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: vpc-alian-1; nested exception is: 
	java.net.ConnectException: Connection timed out (Connection timed out)]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
	at kafka.manager.jmx.KafkaJMX$.doWithConnection(KafkaJMX.scala:57)
	at kafka.manager.actor.cluster.BrokerViewCacheActor.$anonfun$updateBrokerMetrics$3(BrokerViewCacheActor.scala:359)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
Caused by: javax.naming.ServiceUnavailableException: null

**Comment by lianfulei** [comment]
我已经解决了，除了在java 里加ip参数外，还要绑定hosts，ip对应的主机名
