### ISSUE TITLE
Error reading field 'version': java.nio.BufferUnderflowException

### ISSUE THREAD

**Issue by bwf93** [yahoo/kafka-manager#687]
Repeatedly seeing the message
k.m.a.c.KafkaAdminClientActor - Failed to get group summary with admin client : ireNetwork
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'version': java.nio.BufferUnderflowException
	at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:76) ~[org.apache.kafka.kafka-clients-1.1.0.jar:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerProtocol.deserializeAssignment(ConsumerProtocol.java:105) ~[org.apache.kafka.kafka-clients-1.1.0.jar:na]
	at kafka.manager.utils.one10.MemberMetadata$.from(MemberMetadata.scala:28) ~[kafka-manager.kafka-manager-1.3.3.22-sans-externalized.jar:na]
	at kafka.manager.actor.cluster.KafkaAdminClientActor$$anonfun$processQueryRequest$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$13$$anonfun$apply$14.apply(KafkaStateActor.scala:136) ~[kafka-manager.kafka-manager-1.3.3.22-sans-externalized.jar:na]
	at kafka.manager.actor.cluster.KafkaAdminClientActor$$anonfun$processQueryRequest$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$13$$anonfun$apply$14.apply(KafkaStateActor.scala:136) ~[kafka-manager.kafka-manager-1.3.3.22-sans-externalized.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at scala.collection.Iterator$class.foreach(Iterator.scala:891) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[org.scala-lang.scala-library-2.11.12.jar:na]
[kafka-manager] [error] k.m.a.c.KafkaAdminClientActor - Forcing new admin client initialization...
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'version': java.nio.BufferUnderflowException
	at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:76) ~[org.apache.kafka.kafka-clients-1.1.0.jar:na]
	at org.apache.kafka.clients.consumer.internals.ConsumerProtocol.deserializeAssignment(ConsumerProtocol.java:105) ~[org.apache.kafka.kafka-clients-1.1.0.jar:na]
	at kafka.manager.utils.one10.MemberMetadata$.from(MemberMetadata.scala:28) ~[kafka-manager.kafka-manager-1.3.3.22-sans-externalized.jar:na]
	at kafka.manager.actor.cluster.KafkaAdminClientActor$$anonfun$processQueryRequest$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$13$$anonfun$apply$14.apply(KafkaStateActor.scala:136) ~[kafka-manager.kafka-manager-1.3.3.22-sans-externalized.jar:na]
	at kafka.manager.actor.cluster.KafkaAdminClientActor$$anonfun$processQueryRequest$1$$anonfun$apply$mcV$sp$4$$anonfun$apply$13$$anonfun$apply$14.apply(KafkaStateActor.scala:136) ~[kafka-manager.kafka-manager-1.3.3.22-sans-externalized.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at scala.collection.Iterator$class.foreach(Iterator.scala:891) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334) ~[org.scala-lang.scala-library-2.11.12.jar:na]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) ~[org.scala-lang.scala-library-2.11.12.jar:na]

I am using Kafka 1.1.0 and Kafka manager 1.3.3.22

**Comment by woozhijun** [comment]
I have the same problem..
