### ISSUE TITLE
./sbt clean dist  given bellow error

### ISSUE THREAD

**Issue by isharakaru** [yahoo/kafka-manager#689]
[info] Loading settings for project kafka-manager-build from plugins.sbt ...
[info] Loading project definition from /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to kafka-manager (in build file:/home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/)
[success] Total time: 0 s, completed Sep 24, 2019, 3:25:29 PM
[info] Updating ...
[info] Packaging /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/target/scala-2.12/kafka-manager_2.12-2.0.0.2-sources.jar ...
[info] Done packaging.
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Wrote /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/target/scala-2.12/kafka-manager_2.12-2.0.0.2.pom
[info] Main Scala API documentation to /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/target/scala-2.12/api...
[info] Compiling 131 Scala sources and 2 Java sources to /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/target/scala-2.12/classes ...
[info] LESS compiling on 1 source(s)
[info] Packaging /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/target/scala-2.12/kafka-manager_2.12-2.0.0.2-web-assets.jar ...
[info] Done packaging.
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/actor/cluster/KafkaStateActor.scala:102:19: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Properties)
[error]       cp => props.putAll(cp)
[error]                   ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/actor/cluster/KafkaStateActor.scala:265:19: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Properties)
[error]       cp => props.putAll(cp)
[error]                   ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/actor/cluster/KafkaStateActor.scala:102:19: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Properties)
[error]       cp => props.putAll(cp)
[error]                   ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/actor/cluster/KafkaStateActor.scala:265:19: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Properties)
[error]       cp => props.putAll(cp)
[error]                   ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/utils/logkafka81/LogConfig.scala:176:11: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Properties)
[error]     props.putAll(overrides)
[error]           ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/utils/logkafka82/LogConfig.scala:176:11: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Properties)
[error]     props.putAll(overrides)
[error]           ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/utils/logkafka81/LogConfig.scala:176:11: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Properties)
[error]     props.putAll(overrides)
[error]           ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/utils/logkafka82/LogConfig.scala:176:11: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Properties)
[error]     props.putAll(overrides)
[error]           ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/utils/zero10/LogConfig.scala:312:11: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Map[_$3,_$4])
[error]     props.putAll(defaults)
[error]           ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/utils/zero10/LogConfig.scala:313:11: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Properties)
[error]     props.putAll(overrides)
[error]           ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/utils/zero11/LogConfig.scala:272:11: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Map[_$3,_$4])
[error]     props.putAll(defaults)
[error]           ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/utils/zero11/LogConfig.scala:273:11: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Properties)
[error]     props.putAll(overrides)
[error]           ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/utils/zero81/LogConfig.scala:117:11: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Properties)
[error]     props.putAll(overrides)
[error]           ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/utils/zero82/LogConfig.scala:184:11: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Properties)
[error]     props.putAll(overrides)
[error]           ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/utils/zero90/LogConfig.scala:176:11: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Map[_$3,_$4])
[error]     props.putAll(defaults)
[error]           ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/utils/zero90/LogConfig.scala:177:11: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Properties)
[error]     props.putAll(overrides)
[error]           ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/utils/zero10/LogConfig.scala:312:11: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Map[_$3,_$4])
[error]     props.putAll(defaults)
[error]           ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/utils/zero10/LogConfig.scala:313:11: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Properties)
[error]     props.putAll(overrides)
[error]           ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/utils/zero11/LogConfig.scala:272:11: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Map[_$3,_$4])
[error]     props.putAll(defaults)
[error]           ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/utils/zero11/LogConfig.scala:273:11: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Properties)
[error]     props.putAll(overrides)
[error]           ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/utils/zero81/LogConfig.scala:117:11: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Properties)
[error]     props.putAll(overrides)
[error]           ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/utils/zero82/LogConfig.scala:184:11: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Properties)
[error]     props.putAll(overrides)
[error]           ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/utils/zero90/LogConfig.scala:176:11: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Map[_$3,_$4])
[error]     props.putAll(defaults)
[error]           ^
[error] /home/ishara/Documents/Zimpler/kafkaManager/kafka-manager/app/kafka/manager/utils/zero90/LogConfig.scala:177:11: ambiguous reference to overloaded definition,
[error] both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
[error] and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
[error] match argument types (java.util.Properties)
[error]     props.putAll(overrides)
[error]           ^
[error] 12 errors found
[info] No documentation generated with unsuccessful compiler run
[error] 12 errors found
[error] (Compile / compileIncremental) Compilation failed
[error] (Compile / doc) Scaladoc generation failed

**Comment by unixunion** [comment]
+1 also cannot compile, master and tag 2.0.0.2 don't compile.

**Comment by r0perice** [comment]
> --- kafka-manager/kafka-manager-2.0.0.2 » ./sbt clean dist        
> [info] Loading settings for project kafka-manager-2-0-0-2-build from plugins.sbt ...
> [info] Loading project definition from /home/vagrant/tools/kafka-manager/kafka-manager-2.0.0.2/project
> [info] Updating ProjectRef(uri("file:/home/vagrant/tools/kafka-manager/kafka-manager-2.0.0.2/project/"), "kafka-manager-2-0-0-2-build")...
> [info] Done updating.
> [warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
> [info] Loading settings for project root from build.sbt ...
> [info] Set current project to kafka-manager (in build file:/home/vagrant/tools/kafka-manager/kafka-manager-2.0.0.2/)
> [success] Total time: 0 s, completed 28-Oct-2019 16:35:32
> [info] Packaging /home/vagrant/tools/kafka-manager/kafka-manager-2.0.0.2/target/scala-2.12/kafka-manager_2.12-2.0.0.2-sources.jar ...
> [info] Done packaging.
> [info] Updating ...
> [info] Done updating.
> [warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
> [info] Wrote /home/vagrant/tools/kafka-manager/kafka-manager-2.0.0.2/target/scala-2.12/kafka-manager_2.12-2.0.0.2.pom
> [info] Main Scala API documentation to /home/vagrant/tools/kafka-manager/kafka-manager-2.0.0.2/target/scala-2.12/api...
> [info] Compiling 131 Scala sources and 2 Java sources to /home/vagrant/tools/kafka-manager/kafka-manager-2.0.0.2/target/scala-2.12/classes ...
> [error] ## Exception when compiling 133 sources to /home/vagrant/tools/kafka-manager/kafka-manager-2.0.0.2/target/scala-2.12/classes
> [error] xsbt.CompilerInterface
> [error] java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> [error] java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> [error] java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> [error] java.lang.Class.forName0(Native Method)
> [error] java.lang.Class.forName(Class.java:348)
> [error] sbt.internal.inc.AnalyzingCompiler.getInterfaceClass(AnalyzingCompiler.scala:267)
> [error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:234)
> [error] sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:134)
> [error] sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:121)
> [error] sbt.internal.inc.FreshCompilerCache.apply(CompilerCache.scala:78)
> [error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:88)
> [error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
> [error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
> [error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
> [error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
> [error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
> [error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
> [error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
> [error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
> [error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
> [error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
> [error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
> [error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
> [error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
> [error] sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
> [error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
> [error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
> [error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
> [error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
> [error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
> [error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
> [error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1549)
> [error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1523)
> [error] scala.Function1.$anonfun$compose$1(Function1.scala:44)
> [error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
> [error] sbt.std.Transform$$anon$4.work(System.scala:67)
> [error] sbt.Execute.$anonfun$submit$2(Execute.scala:269)
> [error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
> [error] sbt.Execute.work(Execute.scala:278)
> [error] sbt.Execute.$anonfun$submit$1(Execute.scala:269)
> [error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
> [error] sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
> [error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [error] java.lang.Thread.run(Thread.java:748)
> [error]            
> [info] LESS compiling on 1 source(s)
> [info] Packaging /home/vagrant/tools/kafka-manager/kafka-manager-2.0.0.2/target/scala-2.12/kafka-manager_2.12-2.0.0.2-web-assets.jar ...
> [info] Done packaging.
> [error] java.lang.ClassNotFoundException: xsbt.CompilerInterface
> [error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> [error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> [error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> [error] 	at java.lang.Class.forName0(Native Method)
> [error] 	at java.lang.Class.forName(Class.java:348)
> [error] 	at sbt.internal.inc.AnalyzingCompiler.getInterfaceClass(AnalyzingCompiler.scala:267)
> [error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:234)
> [error] 	at sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:134)
> [error] 	at sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:121)
> [error] 	at sbt.internal.inc.FreshCompilerCache.apply(CompilerCache.scala:78)
> [error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:88)
> [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
> [error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
> [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
> [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
> [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
> [error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
> [error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
> [error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
> [error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
> [error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
> [error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
> [error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
> [error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
> [error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
> [error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
> [error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
> [error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
> [error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
> [error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
> [error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
> [error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1549)
> [error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1523)
> [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
> [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
> [error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
> [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
> [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
> [error] 	at sbt.Execute.work(Execute.scala:278)
> [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
> [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
> [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
> [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [error] 	at java.lang.Thread.run(Thread.java:748)
> [error] java.lang.ClassNotFoundException: xsbt.ScaladocInterface
> [error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> [error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> [error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> [error] 	at java.lang.Class.forName0(Native Method)
> [error] 	at java.lang.Class.forName(Class.java:348)
> [error] 	at sbt.internal.inc.AnalyzingCompiler.getInterfaceClass(AnalyzingCompiler.scala:267)
> [error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:234)
> [error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:166)
> [error] 	at sbt.internal.inc.AnalyzingCompiler.doc(AnalyzingCompiler.scala:147)
> [error] 	at sbt.Doc$.$anonfun$scaladoc$1(Doc.scala:39)
> [error] 	at sbt.Doc$.$anonfun$scaladoc$1$adapted(Doc.scala:39)
> [error] 	at sbt.RawCompileLike$.$anonfun$prepare$1(RawCompileLike.scala:83)
> [error] 	at sbt.RawCompileLike$.$anonfun$prepare$1$adapted(RawCompileLike.scala:76)
> [error] 	at sbt.RawCompileLike$.$anonfun$cached$3(RawCompileLike.scala:67)
> [error] 	at sbt.RawCompileLike$.$anonfun$cached$3$adapted(RawCompileLike.scala:65)
> [error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
> [error] 	at sbt.RawCompileLike$.$anonfun$cached$1(RawCompileLike.scala:72)
> [error] 	at sbt.RawCompileLike$.$anonfun$cached$1$adapted(RawCompileLike.scala:55)
> [error] 	at sbt.Defaults$.$anonfun$docTaskSettings$3(Defaults.scala:1427)
> [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
> [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
> [error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
> [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
Hi,
On CentOS 7 with openjdk 1.8.0_151, I have:

>[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
> [error] 	at sbt.Execute.work(Execute.scala:278)
> [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
> [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
> [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
> [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [error] 	at java.lang.Thread.run(Thread.java:748)
> [error] (Compile / compileIncremental) java.lang.ClassNotFoundException: xsbt.CompilerInterface
> [error] (Compile / doc) java.lang.ClassNotFoundException: xsbt.ScaladocInterface
> [error] Total time: 8 s, completed 28-Oct-2019 16:35:40

Any help appreciated.

**Comment by r0perice** [comment]
I managed to compile by removing those folders:

> ~/.ivy2 
> ~/.sbt
